import type {
  AiAgentProfile,
  AiBusinessContext,
  AiDataSource,
  AiOutput,
  AiOutputReview,
  AiPromptChain,
  AiPromptSop,
  AiVerificationCheck,
} from "./types";
import {
  aiAgentEmotionRules,
  emotionalAuditChecklist,
  homeReachEmotionalPositioning,
  politicalEmotionCopy,
  procurementEmotionCopy,
  sharedPostcardEmotionCopy,
} from "@/lib/brand/emotional-positioning";

const now = "2026-05-22T00:00:00.000Z";

export const seedBusinessContext: AiBusinessContext = {
  id: "seed-business-context",
  title: "HomeReach Master Business Context",
  category: "master",
  companyOverview:
    `${homeReachEmotionalPositioning.platformStatement} ${homeReachEmotionalPositioning.mission}`,
  offers:
    "Shared postcards, targeted neighborhood campaigns, political mail, procurement/inventory savings intelligence, AI website assistant, reputation/review support, local SEO, SAM.gov/government contract operating support, creative/proposal assets.",
  pricing:
    "Keep pricing factual and tied to the current approved offer. Do not invent discounts, guarantees, or campaign ROI. Payment, Stripe, subscriptions, and proposal terms require human approval before customer-facing use.",
  targetCustomers:
    "Local service businesses, contractors, restaurants, professional services, political campaigns, county parties, local organizations, procurement-sensitive small businesses, and government-contracting operators.",
  brandVoice:
    homeReachEmotionalPositioning.voice,
  salesPositioning:
    `${homeReachEmotionalPositioning.customerPromise} Postcards are the wedge, but HomeReach is an AI-powered growth and operations execution platform. Lead with relief, protection, growth, confidence, clarity, control, and operational superiority.`,
  complianceRules:
    "No unsupported claims, no misleading ROI, no legal/compliance guarantees, no autonomous payments, no high-volume outreach without approval, no political targeting based on individual beliefs.",
  politicalMailRules:
    "Use geographic and operational planning only. Do not infer individual political beliefs, create ideology scores, or use prohibited persuasion scoring. Public political messaging and mail creative require human approval.",
  procurementDashboardRules:
    `${procurementEmotionCopy.reportLanguage} Prioritize savings, simplicity, landed cost, vendor reliability, delivery visibility, receiving speed, invoice mismatch detection, and owner approval before spend commitments.`,
  sharedPostcardRules:
    `${sharedPostcardEmotionCopy.socialFramework} Preserve category exclusivity logic, available spots, payment flow, and intake flow.`,
  targetedCampaignRules:
    "Use route/geography/household planning, maps, proposal-ready visuals, and approved pricing. Do not overpromise response rates.",
  samGovRules:
    "Assist bid/no-bid, pricing, compliance checklists, proposal organization, subcontractor planning, and post-award execution. Never submit bids or certify compliance autonomously.",
  humanApprovalRequirements:
    "Human approval is required for pricing changes, political/public messaging, mass outreach, legal/compliance-sensitive claims, SAM.gov submissions, customer guarantees, payment actions, and vendor/spend commitments.",
  tags: ["master-context", "approval-required", "brand-voice", "compliance"],
  status: "active",
  lastReviewedAt: null,
  notes: "Seed fallback until ai_business_context has production rows.",
  updatedAt: now,
};

const promptDefaults = {
  outputFormat: "Return a concise executive-ready draft, assumptions, required inputs used, verification risks, and next best action.",
  approvalRequirement: "Human approval required before customer-facing, political, legal, pricing, payment, or mass-outreach use.",
  status: "active" as const,
  lastReviewedAt: null,
  updatedAt: now,
};

export const seedPromptSops: AiPromptSop[] = [
  ["Facebook Group Post", "Facebook group posts", "Draft local group posts that acknowledge visibility pressure and sound human without fake local cheerleading.", ["city", "industry", "offer", "emotional driver", "CTA"]],
  ["Facebook DM Outreach", "Facebook DMs", "Create short direct messages that invite a reply by naming a real local visibility, savings, or campaign execution problem.", ["business name", "city", "category", "offer", "emotional driver"]],
  ["SMS Follow-Up", "SMS outreach", "Create opt-in friendly SMS drafts with STOP language when needed.", ["first name", "request source", "offer", "next step"]],
  ["Email Outreach", "Email outreach", "Draft concise premium emails with a clear CTA and no inflated claims.", ["recipient", "offer", "proof asset", "CTA"]],
  ["Lead Follow-Up", "Lead follow-up", "Turn a stale lead into a warm next action without pressure.", ["lead stage", "last contact", "offer", "objection"]],
  ["Objection Handling", "Objection handling", "Respond to price, timing, trust, and category-fit objections.", ["objection", "customer type", "offer", "proof"]],
  ["Sales Call Script", "Sales call scripts", "Create simple owner-facing talking points for discovery and close calls.", ["business type", "pain", "offer", "CTA"]],
  ["Political Campaign Plan", "Political campaign planning", "Create compliant political mail plans using geography and operations only.", ["candidate", "race", "geography", "timeline"]],
  ["Candidate Research", "Candidate research", "Summarize public campaign context without inferring voter beliefs.", ["candidate", "office", "county", "sources"]],
  ["Postcard Creative Brief", "Postcard creative briefs", "Create premium direct-mail creative briefs with front/back direction and a clear emotional job: relief, pride, trust, urgency, or confidence.", ["offer", "audience", "emotion", "CTA"]],
  ["Procurement Pitch", "Procurement pitches", "Explain the savings dashboard as margin protection and owner relief, not software.", ["industry", "current pain", "savings angle", "demo CTA"]],
  ["Inventory Savings Audit", "Inventory savings audits", "Convert vendor/pricing/delivery signals into simple savings recommendations that show what is leaking and why it matters.", ["items", "vendors", "prices", "delivery fees"]],
  ["SAM.gov Opportunity Review", "SAM.gov opportunity reviews", "Summarize federal opportunities with bid/no-bid and risk framing.", ["solicitation", "NAICS", "due date", "requirements"]],
  ["Proposal Generator", "Proposal generation", "Create premium proposal sections tied to proof, pricing, and next step.", ["offer", "scope", "pricing", "visuals"]],
  ["Client Onboarding", "Client onboarding", "Create simple onboarding instructions and next actions for new customers.", ["product", "customer", "timeline", "missing items"]],
  ["SEO Opportunity Brief", "SEO opportunity planning", "Research local SEO opportunities and convert them into revenue-prioritized page briefs.", ["market", "service", "search intent", "existing assets", "approval gate"]],
  ["SEO Landing Page Draft", "SEO content drafts", "Draft review-ready local SEO page copy using approved positioning, structured answers, and a clear conversion path.", ["page brief", "approved offer", "city or category", "internal links", "CTA"]],
  ["SEO Authority Asset Brief", "SEO authority assets", "Plan reusable authority assets such as guides, tools, case studies, benchmarks, visuals, and image SEO files.", ["topic", "proof source", "asset type", "target audience", "internal link path"]],
  ["SEO Quality Review", "SEO quality review", "Review SEO drafts for factual support, metadata, schema, internal links, inventory/offer accuracy, and approval readiness.", ["draft URL or content", "target keyword", "source notes", "quality check", "publish status"]],
  ["Dashboard QA", "Dashboard QA", "Review a dashboard for broken actions, confusing UX, and missing operational visibility.", ["route", "feature area", "expected workflow"]],
  ["System Health Check", "System health checks", "Summarize system health, blockers, and owner actions.", ["systems", "errors", "last checked", "risk"]],
  ["Daily Revenue Integrity Audit", "Daily revenue integrity audits", "Find revenue leakage, missing follow-ups, broken payments, and stuck deals.", ["leads", "payments", "messages", "campaigns"]],
  ["Technical SEO Audit", "SEO audits", "Audit HomeReach-owned routes for crawlability, indexability, metadata, schema, internal linking, performance, and revenue-path risk.", ["route list", "sitemap", "robots", "metadata", "schema", "analytics context"]],
  ["Local SEO Authority Brief", "Local SEO", "Create review-ready city, county, and service-area briefs that build legitimate HomeReach local authority without doorway pages or fake local claims.", ["geography", "service", "existing pages", "proof points", "local source notes"]],
  ["Topic Cluster Plan", "SEO content strategy", "Plan useful HomeReach topic clusters, pillar pages, supporting pages, FAQs, internal links, and refresh opportunities.", ["topic", "audience", "service", "existing pages", "source requirements"]],
  ["Conversion SEO Review", "Conversion SEO", "Review organic landing pages for search-intent match, proof, CTA clarity, mobile readability, and lead-path friction.", ["page URL", "audience", "offer", "conversion goal", "current copy", "approved proof"]],
  ["SEO QA Review", "SEO QA", "Verify SEO outputs before implementation by checking sources, claims, metadata, internal links, local assertions, and approval status.", ["SEO artifact", "target route", "sources", "verification checklist", "approval state"]],
].map(([promptName, category, purpose, requiredInputs], index) => ({
  id: `seed-sop-${index + 1}`,
  promptName: promptName as string,
  category: category as string,
  purpose: purpose as string,
  requiredInputs: requiredInputs as string[],
  promptText: `Use the HomeReach master business context, approved offer rules, relevant examples, emotional positioning rules, and verification checklist. Task: ${purpose}. Keep output premium, simple, human, specific, and actionable. Recognize the user's pressure, show the operational path, and state assumptions plus approval requirements.`,
  tags: [(category as string).toLowerCase().replaceAll(" ", "-"), "human-approval"],
  relatedWorkflow: category as string,
  relatedOffer: null,
  notes: "Seed SOP; replace with proven winning prompt language as outputs improve.",
  ...promptDefaults,
}));

export const seedDataSources: AiDataSource[] = ([
  ["Best Local Facebook Post", "Best Facebook posts", "Pattern for high-trust city/group posts.", "Short local opener, clear business outcome, soft CTA, no spam tone."],
  ["Best First DM", "Best DMs", "Pattern for first-touch DMs.", "One sentence of relevance, one sentence of value, one easy reply question."],
  ["Compliant Opt-In SMS", "Best SMS messages", "SMS pattern for requested information.", "HomeReach: Hi [First Name], thanks for requesting information about [offer]. Reply STOP to opt out."],
  ["Premium Outreach Email", "Best emails", "Short email structure for lead follow-up.", "Subject, local relevance, proof asset, simple CTA, signature."],
  ["Customer Reply Examples", "Customer replies", "Common replies and intent clues.", "Interested, pricing question, timing objection, wrong contact, stop request."],
  ["Sales Call Notes", "Sales call transcripts", "Discovery and close call patterns.", "Pain, route/visibility explanation, pricing checkpoint, next step."],
  ["Objection Bank", "Objection examples", "Reusable objection examples.", "Too expensive, already advertising, not now, need to ask partner, does direct mail work?"],
  ["Proof / Testimonials", "Testimonials", "Customer proof language.", "Use only real testimonial text when available; otherwise request proof, do not invent."],
  ["Website Positioning", "Website copy", "Approved public positioning.", "Simple, premium, done-for-you local visibility and growth execution."],
  ["Pricing Guardrails", "Pricing pages", "Approved pricing source reminder.", "Reference live pricing system before quoting. Never invent prices."],
  ["Campaign Deck Structure", "Pitch decks", "Proposal/pitch deck outline.", "Problem, plan, visuals, proof, pricing, timeline, CTA."],
  ["Dashboard Screenshots", "Dashboard screenshots", "Visual proof source category.", "Use screenshots only as visual proof; do not expose admin complexity publicly."],
  ["Campaign Example", "Campaign examples", "Campaign planning pattern.", "Audience, geography, offer, route logic, postcard concept, follow-up."],
  ["Political Mail Example", "Political postcard examples", "Political creative reference category.", "Compliant front/back mail concept with disclaimer and approval requirements."],
  ["Procurement Savings Example", "Procurement examples", "Savings insight pattern.", "Vendor price comparison, landed cost, savings, difficulty, approval action."],
  ["SEO Engine Registry", "SEO engine registry", "Existing SEO page registry and publish-state source category.", "Use seo_pages, seo_page_versions, publish gates, quality checks, inventory snapshots, and review status as the canonical SEO execution source."],
  ["SEO Authority Library", "SEO authority assets", "Existing public authority assets for guides, case studies, benchmarks, tools, visuals, image SEO, and internal links.", "Use approved authority pages and visual assets as reusable proof. Keep every claim tied to a source, page, or approved HomeReach capability."],
  ["Local SEO Keyword Targets", "SEO keyword targets", "Revenue-prioritized market, service, city, county, and category opportunities.", "Store keyword target, search intent, geography, offer fit, page type, CTA, and internal link plan before drafting."],
  ["SEO Quality Gates", "SEO quality review", "Review checklist for drafts before any publish action.", "Confirm factual support, metadata, schema, canonical slug, internal links, CTA, inventory/availability fit, and human approval before publishing."],
  ["Search Console / Analytics Signals", "SEO performance signals", "Performance and opportunity notes from search analytics, rankings, traffic, conversions, and crawls.", "Store only sourced performance observations. Label estimates and never guarantee ranking, traffic, leads, or revenue."],
  ["FAQ Core", "FAQs", "Reusable FAQ source.", "How it works, pricing, targeting, timelines, proofs, approvals, opt-outs."],
  ["Onboarding Script", "Onboarding scripts", "Customer onboarding source.", "What we need, what happens next, approval steps, timeline."],
  ["Winning Prompt Library", "Prior winning prompts", "Prompts proven to produce good outputs.", "Mark outputs as winning and save them here over time."],
  ["Emotional Positioning System", "Website copy", "HomeReach emotional strategy source.", `${homeReachEmotionalPositioning.mission} Core emotions: relief, protection, growth, confidence, clarity, control, pride, community, and operational superiority.`],
  ["Shared Postcard Mission Copy", "Best Facebook posts", "Shared postcard emotional framework.", sharedPostcardEmotionCopy.socialFramework],
  ["Procurement Profit Protection Copy", "Procurement examples", "Procurement emotional framework.", procurementEmotionCopy.reportLanguage],
  ["Political Campaign Confidence Copy", "Political postcard examples", "Political mail emotional framework.", politicalEmotionCopy.subtitle],
  ["SEO Authority Guardrails", "SEO examples", "HomeReach SEO quality rules.", "Create useful, source-backed, conversion-focused pages. Do not create thin AI pages, duplicate location spam, doorway pages, fake local claims, keyword stuffing, unsupported ranking guarantees, or fabricated proof."],
  ["HomeReach Authority Clusters", "SEO examples", "Existing HomeReach SEO clusters and authority hubs.", "Ohio city pages, county pages, political mail pages, case studies, interactive tools, visual galleries, benchmark datasets, and service pages should be linked into topical clusters with clear CTAs."],
  ["SEO Conversion Proof Library", "SEO examples", "Proof signals for organic landing pages.", "Use approved examples, visuals, maps, proposal previews, testimonials, case studies, dashboard screenshots, and operational explanations only when the source is known and approved."],
] as const).map(([title, category, description, content], index) => ({
  id: `seed-source-${index + 1}`,
  title,
  category,
  description,
  content,
  tags: [category.toLowerCase().replaceAll(" ", "-")],
  relatedWorkflow: category,
  relatedOffer: null,
  qualityRating: index < 4 ? 4 : 3,
  status: "active",
  lastReviewedAt: null,
  notes: "Seed source; replace with real examples as HomeReach captures winning assets.",
  updatedAt: now,
}));

export const seedAgentProfiles: AiAgentProfile[] = [
  ["Outreach Agent", "Draft and prioritize safe outreach across HomeReach offers.", ["draft messages", "recommend channel", "prepare follow-up"], ["send mass outreach", "ignore opt-outs", "invent claims"]],
  ["Political Campaign Agent", "Research, plan, and draft compliant political campaign assets.", ["summarize campaign", "draft mail plan", "recommend geography"], ["infer voter beliefs", "score ideology", "publish political content"]],
  ["Procurement Agent", "Find savings, vendor issues, delivery risks, and owner-simple recommendations.", ["summarize savings", "flag price spikes", "prepare approval"], ["place orders", "switch vendors", "commit spend"]],
  ["Shared Postcard Agent", "Support shared postcard sales, intake, category exclusivity, and follow-up.", ["draft posts", "draft DMs", "explain offer"], ["override exclusivity", "change pricing"]],
  ["Targeted Campaign Agent", "Plan targeted routes, proposals, creative briefs, and next steps.", ["draft proposal", "summarize geography", "recommend CTA"], ["promise response rate", "launch without payment/approval"]],
  ["SAM.gov Contract Agent", "Assist federal opportunity review, bid/no-bid, pricing, compliance, and subcontractor planning.", ["summarize solicitation", "flag compliance", "draft response sections"], ["submit bids", "certify compliance", "fabricate past performance"]],
  ["Client Onboarding Agent", "Help customers complete onboarding and approvals without friction.", ["list missing items", "draft reminder", "summarize timeline"], ["charge customers", "change orders"]],
  ["Follow-Up Agent", "Identify stale leads, draft follow-ups, and move deals toward next actions.", ["prioritize leads", "draft follow-up", "recommend timing"], ["send high-volume messages", "bypass approval"]],
  ["QA / System Health Agent", "Inspect workflows, buttons, dashboards, and system health for production readiness.", ["summarize issue", "rank severity", "recommend fix"], ["hide failures", "modify production autonomously"]],
  ["Revenue Integrity Agent", "Detect broken revenue paths, payment blockers, stuck proposals, and leakage.", ["audit payments", "flag stuck deals", "summarize revenue risk"], ["modify payments", "discount without approval"]],
  ["Design Brief Agent", "Create premium creative briefs for postcards, proposals, maps, and social visuals.", ["draft brief", "recommend visual angle", "prepare Canva/Figma prompt"], ["publish final creative", "ignore disclaimer needs"]],
  [
    "Technical SEO Agent",
    "Improve HomeReach organic visibility by finding crawlability, indexability, metadata, schema, performance, internal link, and route-level SEO issues.",
    ["audit routes", "draft metadata/schema recommendations", "prioritize fix lists"],
    ["publish changes", "change redirects/indexing without approval", "keyword stuff"],
    ["SEO Engine Registry", "SEO Authority Guardrails", "Search Console / Analytics Signals", "Website Positioning"],
    ["Technical SEO Audit", "SEO QA Review"],
  ],
  [
    "Local SEO Authority Agent",
    "Build legitimate HomeReach local authority for Ohio and service-area pages without spam or fake local proof.",
    ["draft local briefs", "identify proof gaps", "recommend internal links"],
    ["create doorway pages", "fabricate offices/reviews/customers", "mass-generate local spam"],
    ["HomeReach Authority Clusters", "SEO Authority Guardrails", "Website Positioning"],
    ["Local SEO Authority Brief", "SEO QA Review"],
  ],
  [
    "Content / Topic Cluster Agent",
    "Plan useful HomeReach topic clusters, pillar pages, supporting content, FAQs, and refresh opportunities.",
    ["draft topic maps", "create briefs", "recommend internal links"],
    ["publish thin AI content", "plagiarize", "invent stats or outcomes"],
    ["HomeReach Authority Clusters", "SEO Authority Library", "SEO Conversion Proof Library"],
    ["Topic Cluster Plan", "SEO Authority Asset Brief", "SEO QA Review"],
  ],
  [
    "Conversion SEO Agent",
    "Improve organic pages so visitors understand the offer, trust HomeReach, and take the next approved action.",
    ["review page intent", "draft CTA variants", "flag proof gaps"],
    ["alter pricing", "change checkout flows", "make ROI/ranking guarantees"],
    ["SEO Conversion Proof Library", "Pricing Guardrails", "Customer Reply Examples", "Website Positioning"],
    ["Conversion SEO Review", "SEO Landing Page Draft", "SEO QA Review"],
  ],
  [
    "SEO QA Agent",
    "Review SEO outputs before implementation or publication for source support, spam risk, brand alignment, and approval status.",
    ["verify sources", "flag SEO risks", "request revisions"],
    ["publish", "approve its own work as final human approval", "waive gates"],
    ["SEO Quality Gates", "SEO Authority Guardrails", "Website Positioning"],
    ["SEO QA Review", "SEO Quality Review"],
  ],
  [
    "SEO Research Agent",
    "Find high-intent local SEO opportunities and turn them into source-backed briefs for HomeReach growth pages.",
    ["research markets", "prioritize page opportunities", "draft SEO briefs", "recommend internal links"],
    ["publish pages", "guarantee rankings", "invent performance data", "bypass review gates"],
    ["SEO Engine Registry", "SEO Authority Library", "Local SEO Keyword Targets", "Search Console / Analytics Signals", "Website Positioning"],
    ["SEO Opportunity Brief", "SEO Authority Asset Brief", "SEO Quality Review"],
  ],
  [
    "SEO Content Agent",
    "Draft approval-ready local SEO pages, authority assets, metadata, and structured answer sections from approved briefs.",
    ["draft SEO copy", "prepare metadata", "recommend schema and internal links", "queue approval artifacts"],
    ["publish pages", "make ranking guarantees", "change live inventory", "use unsupported claims"],
    ["SEO Engine Registry", "SEO Authority Library", "SEO Quality Gates", "Pricing Guardrails", "Proof / Testimonials"],
    ["SEO Landing Page Draft", "SEO Quality Review", "Proposal Generator"],
  ],
].map(([agentName, mission, allowedActions, disallowedActions, requiredDataSources, requiredPromptSops], index) => ({
  id: `seed-agent-${index + 1}`,
  agentName: agentName as string,
  mission: mission as string,
  allowedActions: allowedActions as string[],
  disallowedActions: disallowedActions as string[],
  requiredDataSources: (requiredDataSources as string[] | undefined) ?? ["HomeReach Master Business Context", "Approved pricing and compliance rules"],
  requiredPromptSops: (requiredPromptSops as string[] | undefined) ?? ["Workflow-specific SOP prompt", "Verification checklist"],
  approvalRules: "Human approval required before customer-facing, political, legal, pricing, payment, or mass-outreach use.",
  complianceRules: "Use HomeReach compliance rules. Never invent facts, pricing, legal claims, qualifications, or guarantees.",
  escalationRules: "Escalate unclear compliance, pricing, legal, political, payment, or high-risk operational decisions to Jason/admin.",
  outputFormat: "Recommendation, draft, required inputs used, risks, verification checklist, next action.",
  toneRules: `Calm, premium, human, concise, locally relevant, not robotic. ${aiAgentEmotionRules.join(" ")}`,
  successMetrics: ["approved outputs", "revision rate", "conversion support", "errors avoided"],
  status: "active",
  lastReviewedAt: null,
  notes: "Instruction profile seed for the AI Assets Command Center.",
  updatedAt: now,
}));

const chainBlueprints = [
  ["Offer Chain", "Offer", ["Offer Architect", "Sales Page", "Sales Script", "Demo/VSL Script", "Email/SMS Follow-Up"]],
  ["Political Campaign Chain", "Political", ["Candidate Research", "Campaign Strategy", "Target Area Plan", "Postcard Creative Brief", "Proposal", "Follow-Up"]],
  ["Procurement Chain", "Procurement", ["Business Intake", "Spend Analysis", "Savings Angle", "Pitch Message", "Demo Script", "Follow-Up"]],
  ["SAM.gov Chain", "Government Contracts", ["Opportunity Scan", "Fit Analysis", "Bid/No-Bid", "Partner/Subcontractor Need", "Proposal Draft", "Follow-Up"]],
  ["Shared Postcard Chain", "Shared Postcards", ["City/Category Research", "Offer Positioning", "Facebook Post", "DM Follow-Up", "Intake Link", "Close Sequence"]],
  ["SEO Authority Chain", "SEO", ["Market/Intent Research", "Opportunity Brief", "Page or Asset Draft", "Metadata + Schema Plan", "Internal Link Plan", "Quality Review + Approval Handoff"]],
] as const;

export const seedPromptChains: AiPromptChain[] = chainBlueprints.map(([chainName, category, steps], index) => ({
  id: `seed-chain-${index + 1}`,
  chainName,
  category,
  purpose: `Move ${category.toLowerCase()} work from raw context to approved, reusable execution assets.`,
  requiredInputs: ["Business context", "Approved offer", "Relevant source examples", "Target customer/workflow"],
  sourceAssets: ["HomeReach Master Business Context", "SOP / Prompt Repository", "Data Sources"],
  approvalPoints: ["Before customer-facing use", "Before political/public messaging", "Before pricing/payment/compliance claims"],
  runStatus: index === 0 ? "waiting_approval" : "ready",
  status: "active",
  lastReviewedAt: null,
  notes: "Prebuilt chain. Use copy/export until live AI execution is wired.",
  updatedAt: now,
  steps: steps.map((stepName, stepIndex) => ({
    id: `seed-chain-${index + 1}-step-${stepIndex + 1}`,
    chainId: `seed-chain-${index + 1}`,
    stepOrder: stepIndex + 1,
    stepName,
    requiredInputs: stepIndex === 0 ? ["Business context", "source assets"] : ["Previous step output", "verification notes"],
    sourceAssets: ["Business Context", "Prompt SOP", "Relevant data source"],
    outputSummary: `Draft ${stepName.toLowerCase()} output and pass verified context forward.`,
    approvalRequired: chainName === "SEO Authority Chain" ? stepIndex > 0 : stepIndex >= steps.length - 2,
    runStatus: stepIndex === 0 && index === 0 ? "complete" : "ready",
    notes: chainName === "SEO Authority Chain" && stepIndex > 0
      ? "SEO review or approval point."
      : stepIndex >= steps.length - 2
        ? "Human approval point."
        : null,
  })),
}));

export const seedVerificationChecks: AiVerificationCheck[] = ([
  ["Facts verified", "accuracy"],
  ["Numbers verified", "accuracy"],
  ["Pricing verified", "revenue"],
  ["Claims verified", "compliance"],
  ["Legal/compliance reviewed", "compliance"],
  ["Political targeting rules followed", "political"],
  ["No prohibited persuasion scoring", "political"],
  ["No voter belief inference", "political"],
  ["No unsupported guarantees", "sales"],
  ["No misleading ROI claims", "sales"],
  ["Brand tone reviewed", "brand"],
  ["SEO source support verified", "seo"],
  ["SEO metadata and schema reviewed", "seo"],
  ["Internal links and CTA reviewed", "seo"],
  ["No thin or duplicate SEO content", "seo"],
  ["No keyword stuffing or doorway-page pattern", "seo"],
  ["Local claims verified", "seo"],
  ["No SEO ranking or traffic guarantees", "seo"],
  ["SEO publish approval completed", "seo"],
  ["Human approval completed", "approval"],
  ...emotionalAuditChecklist.map((item) => [item, "emotional-positioning"] as const),
] as const).map(([label, category], index) => ({
  id: `seed-check-${index + 1}`,
  outputId: null,
  label,
  category,
  status: "not_started",
  required: true,
  completedAt: null,
  notes: null,
}));

export const seedOutputs: AiOutput[] = [
  {
    id: "seed-output-1",
    title: "Procurement savings pitch draft",
    agentName: "Procurement Agent",
    workflow: "Procurement Chain",
    outputType: "pitch",
    content:
      "HomeReach can review your vendor pricing, delivery fees, and reorder patterns to find savings without giving you another complicated system to manage.",
    dataSources: ["HomeReach Master Business Context", "Procurement Savings Example"],
    promptSopName: "Procurement Pitch",
    chainName: "Procurement Chain",
    approvalStatus: "needs_review",
    verificationStatus: "pending",
    winningOutput: false,
    status: "active",
    notes: "Seed review item.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-output-2",
    title: "Political mail compliance reminder",
    agentName: "Political Campaign Agent",
    workflow: "Political Campaign Chain",
    outputType: "compliance_note",
    content:
      "Use geography, race timing, campaign phase, and operational execution needs. Do not infer voter beliefs or use ideology scoring.",
    dataSources: ["HomeReach Master Business Context"],
    promptSopName: "Political Campaign Plan",
    chainName: "Political Campaign Chain",
    approvalStatus: "approved",
    verificationStatus: "verified",
    winningOutput: true,
    status: "active",
    notes: "Seed approved rule.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-output-3",
    title: "Local SEO opportunity brief draft",
    agentName: "Content / Topic Cluster Agent",
    workflow: "SEO Authority Chain",
    outputType: "seo_brief",
    content:
      "Draft a source-backed local SEO page brief that ties the market, service, search intent, approved HomeReach offer, internal links, CTA, and publish gate into one review-ready artifact.",
    dataSources: ["SEO Engine Registry", "SEO Authority Library", "Local SEO Keyword Targets"],
    promptSopName: "SEO Opportunity Brief",
    chainName: "SEO Authority Chain",
    approvalStatus: "needs_review",
    verificationStatus: "pending",
    winningOutput: false,
    status: "active",
    notes: "Seed SEO review item. Do not publish without human approval.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-output-4",
    title: "HomeReach SEO authority review starter",
    agentName: "Technical SEO Agent",
    workflow: "SEO Authority Chain",
    outputType: "seo_audit",
    content:
      "Review sitemap, robots, authority routes, local pages, metadata, schema, internal links, and conversion CTAs. Draft only. No SEO changes should publish until source support, QA, and human approval are complete.",
    dataSources: ["HomeReach Master Business Context", "SEO Authority Guardrails", "HomeReach Authority Clusters"],
    promptSopName: "Technical SEO Audit",
    chainName: "SEO Authority Chain",
    approvalStatus: "needs_review",
    verificationStatus: "pending",
    winningOutput: false,
    status: "active",
    notes: "Seed SEO review item.",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedOutputReviews: AiOutputReview[] = [
  {
    id: "seed-review-1",
    outputId: "seed-output-1",
    reviewStatus: "needs_review",
    reviewNotes: "Confirm exact offer and CTA before use.",
    checklist: { pricingVerified: false, brandToneReviewed: true },
    createdAt: now,
  },
];
