"use client";

import { useState, useRef, useEffect } from "react";
import type { AutomationMessage, AutomationMode, IntentType, LeadStatus } from "@/lib/engine/types";
import { AutomationEngine } from "@/lib/engine/automation";
// MOCK_CONVERSATIONS removed — inbox now loads from real DB via /api/conversations

// ─────────────────────────────────────────────────────────────────────────────
// Unified Inbox — Enhanced with Automation Engine
// ─────────────────────────────────────────────────────────────────────────────

export interface InboxConversation {
  id: string;
  leadId: string;
  leadName: string;
  businessName: string;
  phone: string;
  email: string;
  city: string;
  category: string;
  status: LeadStatus;
  lastMessage: string;
  lastMessageAt: string;
  unreadCount: number;
  channel: "sms" | "email";
  automationMode: AutomationMode;
  lastIntent?: IntentType;
  messages: AutomationMessage[];
}

const STATUS_STYLES: Record<LeadStatus, string> = {
  lead:        "bg-gray-100 text-gray-600",
  interested:  "bg-amber-50 text-amber-700",
  sold:        "bg-green-50 text-green-700",
  churned:     "bg-red-50 text-red-600",
  closed_won:  "bg-emerald-50 text-emerald-700",
  closed_lost: "bg-gray-100 text-gray-500",
};

function formatTime(iso: string) {
  const date = new Date(iso);
  const now = new Date();
  const diffDays = Math.floor((now.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));
  if (diffDays === 0) return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
  if (diffDays === 1) return "Yesterday";
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function IntentBadge({ intent }: { intent?: IntentType }) {
  if (!intent || intent === "unknown") return null;
  const badge = AutomationEngine.getIntentBadge(intent);
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${badge.color}`}>
      {badge.label}
    </span>
  );
}

function MessageBubble({ msg }: { msg: AutomationMessage }) {
  const isOut = msg.direction === "outbound";
  const intentBadge = msg.intent ? AutomationEngine.getIntentBadge(msg.intent) : null;
  return (
    <div className={`flex flex-col ${isOut ? "items-end" : "items-start"}`}>
      {/* Intent badge on inbound messages */}
      {!isOut && msg.intent && msg.intent !== "unknown" && (
        <div className="mb-1 ml-1">
          <IntentBadge intent={msg.intent} />
        </div>
      )}
      <div
        className={`max-w-xs lg:max-w-sm rounded-2xl px-4 py-3 text-sm ${
          isOut
            ? msg.isAutoGenerated
              ? "bg-violet-600 text-white rounded-br-sm"
              : "bg-blue-600 text-white rounded-br-sm"
            : "bg-white border border-gray-200 text-gray-800 rounded-bl-sm shadow-sm"
        }`}
      >
        {isOut && msg.isAutoGenerated && (
          <div className="text-violet-200 text-xs mb-1 font-medium">🤖 Auto-sent</div>
        )}
        <p className="leading-relaxed whitespace-pre-wrap">{msg.body}</p>
        <p className={`text-xs mt-1 ${isOut ? "text-blue-200" : "text-gray-400"}`}>
          {isOut ? "You · " : ""}{formatTime(msg.sentAt)}
        </p>
      </div>
    </div>
  );
}

function ConversationRow({
  conv,
  isActive,
  onClick,
}: {
  conv: InboxConversation;
  isActive: boolean;
  onClick: () => void;
}) {
  const intentBadge = conv.lastIntent ? AutomationEngine.getIntentBadge(conv.lastIntent) : null;
  // Compute lead score from conversation messages
  const score      = AutomationEngine.scoreConversation(conv as unknown as import("@/lib/engine/types").ConversationContext);
  const scoreBadge = AutomationEngine.getScoreBadge(score);

  return (
    <button
      onClick={onClick}
      className={`w-full text-left px-4 py-4 border-b border-gray-100 transition-colors ${
        isActive ? "bg-blue-50 border-l-2 border-l-blue-500" : "hover:bg-gray-50"
      }`}
    >
      <div className="flex items-start justify-between gap-2">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-1.5 mb-0.5">
            <p className="font-semibold text-sm text-gray-900 truncate">{conv.leadName}</p>
            {conv.unreadCount > 0 && (
              <span className="shrink-0 w-4 h-4 rounded-full bg-blue-600 text-white text-xs font-bold flex items-center justify-center">
                {conv.unreadCount}
              </span>
            )}
          </div>
          <p className="text-xs text-gray-500 truncate">{conv.businessName}</p>
          <p className="text-xs text-gray-400 truncate mt-0.5">{conv.lastMessage}</p>
          <div className="flex items-center gap-1.5 mt-1 flex-wrap">
            {intentBadge && (
              <span className={`inline-flex items-center rounded-full px-1.5 py-0.5 text-xs font-medium ${intentBadge.color}`}>
                {intentBadge.label}
              </span>
            )}
            {/* Lead score chip */}
            <span className={`inline-flex items-center gap-0.5 rounded-full border px-1.5 py-0.5 text-xs font-semibold ${scoreBadge.color}`}>
              {scoreBadge.emoji} {score} · {scoreBadge.label}
            </span>
          </div>
        </div>
        <div className="flex flex-col items-end gap-1 shrink-0">
          <span className="text-xs text-gray-400">{formatTime(conv.lastMessageAt)}</span>
          <div className="flex gap-1">
            <span className="text-xs px-1.5 py-0.5 rounded-full font-medium"
              style={{
                backgroundColor: conv.channel === "sms" ? "#eff6ff" : "#fdf4ff",
                color: conv.channel === "sms" ? "#1d4ed8" : "#7c3aed",
              }}>
              {conv.channel.toUpperCase()}
            </span>
            {conv.automationMode === "auto" && (
              <span className="text-xs px-1.5 py-0.5 rounded-full bg-violet-100 text-violet-700 font-medium">
                AUTO
              </span>
            )}
          </div>
        </div>
      </div>
    </button>
  );
}

export function InboxClient() {
  const [conversations, setConversations] = useState<InboxConversation[]>([]);
  const [loading, setLoading]   = useState(true);
  const [loadErr, setLoadErr]   = useState<string | null>(null);
  const [activeId, setActiveId] = useState<string>("");
  const [replyText, setReplyText] = useState("");
  const [sending, setSending]   = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const active = conversations.find((c) => c.id === activeId) ?? null;

  // ── Load real conversations from DB on mount ────────────────────────────────
  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        setLoading(true);
        setLoadErr(null);
        const res = await fetch("/api/conversations");
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        const data = await res.json() as { conversations: InboxConversation[] };
        if (cancelled) return;
        // Enrich with automation fields and intent detection
        const enriched: InboxConversation[] = (data.conversations ?? []).map((c) => ({
          ...c,
          automationMode: c.automationMode ?? "manual",
          lastIntent: c.lastIntent ?? undefined,
          messages: (c.messages ?? []).map((m) => ({
            ...m,
            intent: m.direction === "inbound" && !m.intent
              ? AutomationEngine.detectIntent(m.body).type
              : m.intent,
            isAutoGenerated: m.isAutoGenerated ?? false,
          })),
          // Fill missing contact fields with empty strings so UI doesn't crash
          phone: c.phone ?? "",
          email: c.email ?? "",
          city: c.city ?? "",
          category: c.category ?? "",
          status: c.status ?? "lead",
          channel: c.channel ?? "sms",
        }));
        setConversations(enriched);
        if (enriched.length > 0 && !activeId) {
          setActiveId(enriched[0]!.id);
        }
      } catch (err) {
        if (!cancelled) {
          console.error("[InboxClient] load error:", err);
          setLoadErr(err instanceof Error ? err.message : "Failed to load conversations");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [active?.messages.length]);

  function handleSelectConv(id: string) {
    setActiveId(id);
    setReplyText("");
    setConversations((prev) =>
      prev.map((c) => (c.id === id ? { ...c, unreadCount: 0 } : c))
    );
    // Mark read in DB
    fetch(`/api/conversations/${id}/read`, { method: "POST" }).catch(() => {});
  }

  function toggleAutomation(id: string) {
    setConversations((prev) =>
      prev.map((c) =>
        c.id === id
          ? { ...c, automationMode: c.automationMode === "auto" ? "manual" : "auto" }
          : c
      )
    );
  }

  function handleSimulateInbound() {
    if (!active) return;
    const samples = [
      "Yeah send me the link",
      "How much does it cost?",
      "That's too expensive",
      "Not interested thanks",
      "How many homes is that again?",
    ];
    const body = samples[Math.floor(Math.random() * samples.length)];
    const detected = AutomationEngine.detectIntent(body);
    const inboundMsg: AutomationMessage = {
      id: `msg-${Date.now()}-in`,
      direction: "inbound",
      channel: active.channel,
      body,
      sentAt: new Date().toISOString(),
      read: true,
      intent: detected.type,
    };

    let autoReply: AutomationMessage | null = null;
    if (active.automationMode === "auto") {
      const firstName = active.leadName.split(" ")[0];
      const responseBody = AutomationEngine.generateResponse(detected.type, active.channel, {
        firstName,
        city: active.city,
        category: active.category,
      });
      autoReply = {
        id: `msg-${Date.now()}-auto`,
        direction: "outbound",
        channel: active.channel,
        body: responseBody,
        sentAt: new Date(Date.now() + 3000).toISOString(),
        read: true,
        isAutoGenerated: true,
      };
    }

    setConversations((prev) =>
      prev.map((c) => {
        if (c.id !== activeId) return c;
        const newMessages = autoReply
          ? [...c.messages, inboundMsg, autoReply]
          : [...c.messages, inboundMsg];
        return {
          ...c,
          messages: newMessages,
          lastMessage: autoReply ? autoReply.body : body,
          lastMessageAt: new Date().toISOString(),
          lastIntent: detected.type,
          status:
            detected.type === "ready_to_buy"
              ? "closed_won"
              : detected.type === "not_interested"
              ? "churned"
              : c.status,
        };
      })
    );
  }

  async function handleSend(e: React.FormEvent) {
    e.preventDefault();
    if (!replyText.trim() || !active) return;
    setSending(true);
    const body = replyText.trim();

    try {
      const res = await fetch(`/api/conversations/${active.id}/reply`, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({
          body,
          channel:       active.channel,
          sendViaTwilio: !!(active.phone),   // send via Twilio if we have a phone number
          isAutoGenerated: false,
        }),
      });

      const data = await res.json().catch(() => ({})) as { message?: AutomationMessage };
      const newMsg: AutomationMessage = data.message ?? {
        id:              `msg-${Date.now()}`,
        direction:       "outbound",
        channel:         active.channel,
        body,
        sentAt:          new Date().toISOString(),
        read:            true,
        isAutoGenerated: false,
      };

      setConversations((prev) =>
        prev.map((c) =>
          c.id === activeId
            ? { ...c, messages: [...c.messages, newMsg], lastMessage: newMsg.body, lastMessageAt: newMsg.sentAt }
            : c
        )
      );
      setReplyText("");
    } catch (err) {
      console.error("[InboxClient] send error:", err);
    } finally {
      setSending(false);
    }
  }

  function handleUseTemplate(intent: IntentType = "interested") {
    if (!active) return;
    const firstName = active.leadName.split(" ")[0];
    const body = AutomationEngine.generateResponse(intent, active.channel, {
      firstName,
      city: active.city,
      category: active.category,
    });
    setReplyText(body);
  }

  const totalUnread = conversations.reduce((s, c) => s + c.unreadCount, 0);
  const needsHandoff = active && active.automationMode === "auto" &&
    (active.lastIntent === "ready_to_buy" || active.lastIntent === "not_interested");

  if (loading) {
    return (
      <div className="flex h-[calc(100vh-6rem)] max-w-6xl rounded-2xl border border-gray-200 bg-white shadow-sm items-center justify-center">
        <div className="text-center space-y-3">
          <div className="text-2xl animate-pulse">💬</div>
          <p className="text-sm text-gray-500">Loading conversations…</p>
        </div>
      </div>
    );
  }

  if (loadErr) {
    return (
      <div className="flex h-[calc(100vh-6rem)] max-w-6xl rounded-2xl border border-red-200 bg-red-50 shadow-sm items-center justify-center p-8">
        <div className="text-center space-y-3 max-w-md">
          <div className="text-2xl">⚠️</div>
          <p className="font-semibold text-red-800">Failed to load conversations</p>
          <p className="text-sm text-red-600">{loadErr}</p>
          <button
            onClick={() => window.location.reload()}
            className="mt-2 px-4 py-2 text-sm bg-red-600 text-white rounded-lg hover:bg-red-700"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-[calc(100vh-6rem)] max-w-6xl rounded-2xl border border-gray-200 bg-white shadow-sm overflow-hidden">

      {/* ── Left: conversation list ── */}
      <div className="w-80 shrink-0 flex flex-col border-r border-gray-200">
        <div className="px-4 py-4 border-b border-gray-100 bg-gray-50">
          <div className="flex items-center justify-between">
            <h1 className="font-bold text-gray-900">Inbox</h1>
            {totalUnread > 0 && (
              <span className="text-xs font-bold text-blue-600 bg-blue-50 rounded-full px-2 py-0.5">
                {totalUnread} unread
              </span>
            )}
          </div>
          <p className="text-xs text-gray-500 mt-0.5">{conversations.length} conversations</p>
        </div>
        <div className="overflow-y-auto flex-1">
          {conversations.map((conv) => (
            <ConversationRow
              key={conv.id}
              conv={conv}
              isActive={conv.id === activeId}
              onClick={() => handleSelectConv(conv.id)}
            />
          ))}
        </div>
      </div>

      {/* ── Right: thread ── */}
      {active ? (
        <div className="flex-1 flex flex-col min-w-0">

          {/* Thread header */}
          <div className="px-5 py-4 border-b border-gray-100 bg-white">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <p className="font-bold text-gray-900">{active.leadName}</p>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${STATUS_STYLES[active.status]}`}>
                    {active.status.replace("_", " ")}
                  </span>
                  <IntentBadge intent={active.lastIntent} />
                </div>
                <p className="text-sm text-gray-500 mt-0.5">
                  {active.businessName} · {active.city} · {active.category}
                </p>
                <div className="flex gap-3 mt-1">
                  <a href={`tel:${active.phone}`} className="text-xs text-blue-600 hover:underline">📞 {active.phone}</a>
                  <a href={`mailto:${active.email}`} className="text-xs text-blue-600 hover:underline">✉️ {active.email}</a>
                </div>
              </div>

              {/* Automation toggle */}
              <div className="flex flex-col items-end gap-2 shrink-0">
                <button
                  onClick={() => toggleAutomation(active.id)}
                  className={`flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold border transition-colors ${
                    active.automationMode === "auto"
                      ? "bg-violet-600 text-white border-violet-600"
                      : "bg-white text-gray-600 border-gray-300 hover:bg-gray-50"
                  }`}
                >
                  {active.automationMode === "auto" ? "🤖 Auto ON" : "👤 Manual"}
                </button>
                <button
                  onClick={handleSimulateInbound}
                  className="text-xs text-gray-400 hover:text-gray-600 transition-colors"
                  title="Simulate an inbound message (dev only)"
                >
                  ⚡ Simulate reply
                </button>
              </div>
            </div>

            {/* Handoff alert */}
            {needsHandoff && (
              <div className="mt-3 rounded-lg bg-green-50 border border-green-200 px-4 py-2.5 flex items-center justify-between">
                <p className="text-sm font-medium text-green-800">
                  {active.lastIntent === "ready_to_buy"
                    ? "🟢 This lead is ready to buy — intake link was auto-sent!"
                    : "🔴 Lead marked not interested — automation paused."}
                </p>
                <button
                  onClick={() => toggleAutomation(active.id)}
                  className="text-xs font-semibold text-green-700 hover:underline ml-3"
                >
                  Switch to manual
                </button>
              </div>
            )}
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto px-5 py-5 space-y-4 bg-gray-50">
            {active.automationMode === "auto" && (
              <div className="text-center">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-violet-100 text-violet-700 px-3 py-1 text-xs font-medium">
                  🤖 Automation active — responding automatically
                </span>
              </div>
            )}
            {active.messages.map((msg) => (
              <MessageBubble key={msg.id} msg={msg} />
            ))}
            <div ref={messagesEndRef} />
          </div>

          {/* Reply area */}
          <form onSubmit={handleSend} className="px-5 py-4 border-t border-gray-100 bg-white">
            {/* Quick templates */}
            <div className="flex gap-2 mb-2.5 flex-wrap">
              <span className="text-xs text-gray-400 self-center">Templates:</span>
              {(["interested", "objection", "ready_to_buy"] as IntentType[]).map((intent) => {
                const badge = AutomationEngine.getIntentBadge(intent);
                return (
                  <button
                    key={intent}
                    type="button"
                    onClick={() => handleUseTemplate(intent)}
                    className={`text-xs px-2 py-1 rounded-full border font-medium transition-colors hover:opacity-80 ${badge.color}`}
                  >
                    {badge.label}
                  </button>
                );
              })}
              <button
                type="button"
                onClick={() => {
                  const firstName = active.leadName.split(" ")[0];
                  setReplyText(
                    `Hi ${firstName}, this is Jason from HomeReach — here's your intake link to lock in the ${active.category} spot in ${active.city}: ${process.env.NEXT_PUBLIC_APP_URL ?? "https://home-reach.com"}/get-started\n\nTakes about 3 minutes!`
                  );
                }}
                className="text-xs px-2 py-1 rounded-full border font-medium bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100 transition-colors"
              >
                📋 Send Intake Link
              </button>
            </div>

            <div className="flex items-end gap-3">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-medium text-gray-500">
                    via {active.channel.toUpperCase()} → {active.channel === "sms" ? active.phone : active.email}
                  </span>
                </div>
                <textarea
                  value={replyText}
                  onChange={(e) => setReplyText(e.target.value)}
                  onKeyDown={(e) => { if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) handleSend(e as any); }}
                  placeholder={`Type a ${active.channel === "sms" ? "text" : "reply"}… (Cmd+Enter to send)`}
                  rows={3}
                  className="w-full rounded-xl border border-gray-300 px-3 py-2.5 text-sm resize-none focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <button
                type="submit"
                disabled={sending || !replyText.trim()}
                className="shrink-0 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50 transition-colors"
              >
                {sending ? "…" : "Send"}
              </button>
            </div>
          </form>
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center text-gray-400 text-sm">
          Select a conversation
        </div>
      )}
    </div>
  );
}
