import { PRODUCT_OVERVIEW_PATHS, PRODUCT_START_PATHS } from "@/lib/marketing/product-routes";

export const REVENUE_REEL_BLUEPRINT_VERSION = "offer-led-direct-response-v1-2026-05-29";

export type RevenueReelBlueprint = {
  id: string;
  offer: string;
  route: string;
  startRoute: string;
  audience: string;
  pain: string;
  promise: string;
  hook: string;
  cta: string;
  commentKeyword: string;
  visualStory: string[];
  dmGoal: string;
  proofAssets: string[];
  productionMethod: string;
  qualityBar: string[];
  complianceNotes: string[];
};

export const revenueReelBlueprints: RevenueReelBlueprint[] = [
  {
    id: "supplyfy-savings-review",
    offer: "Supplyfy Supply Cost Review",
    route: PRODUCT_OVERVIEW_PATHS.inventoryIntelligence,
    startRoute: PRODUCT_START_PATHS.inventoryIntelligence,
    audience: "Restaurants, bakeries, pizza shops, coffee shops, food businesses, contractors, and local operators with recurring supply spend.",
    pain: "Owners feel rising costs every week but rarely have time to compare vendor pricing line by line.",
    promise: "Find hidden savings opportunities, compare vendors, and protect margin without adding another complicated operating system.",
    hook: "Still overpaying for supplies?",
    cta: "Comment SAVE for a free supply cost review.",
    commentKeyword: "SAVE",
    visualStory: [
      "Owner pays a supplier a visibly large cash stack for recurring supplies.",
      "The same recurring items are compared with controlled HomeReach overlays, not AI-rendered text.",
      "Owner pays a smaller cash stack for the same quantity from a better option.",
      "Final frame: You deserve the money you work for. Supply savings done for you.",
    ],
    dmGoal: "Start a free savings review conversation and collect business type, monthly supply spend, vendor categories, and the biggest purchasing pain point.",
    proofAssets: ["Supplyfy dashboard screenshots", "cash-stack comparison", "vendor comparison cards", "monthly and annual savings examples"],
    productionMethod: "Use real footage or textless AI b-roll for owner emotion and supplier handoff. Add all pricing, dashboard, and CTA text with the controlled overlay layer.",
    qualityBar: [
      "Shows financial pain before showing the dashboard.",
      "No fake vendor names or guaranteed savings.",
      "Owner emotion must feel believable, not influencer-polished.",
      "CTA keyword is visible for at least two seconds.",
    ],
    complianceNotes: ["Frame all savings as review opportunities until verified with customer data."],
  },
  {
    id: "route-density-lawncare",
    offer: "HomeReach Targeted Route Density",
    route: PRODUCT_OVERVIEW_PATHS.targetedCampaigns,
    startRoute: PRODUCT_START_PATHS.targetedCampaigns,
    audience: "Lawn care, landscaping, roofing, HVAC, pest control, concrete, remodeling, and home-service companies.",
    pain: "Service businesses finish great work in one neighborhood, then spend money chasing random leads across town instead of reactivating the homes around that job.",
    promise: "Turn one completed job into a targeted neighborhood reactivation plan so nearby homeowners see the business while local proof is still fresh.",
    hook: "One job. One neighborhood.",
    cta: "Comment MAP for a free route-density example.",
    commentKeyword: "MAP",
    visualStory: [
      "A completed home-service job is shown as the local proof point.",
      "Camera moves to a bird's-eye neighborhood view and spotlights the original customer address.",
      "Surrounding homes activate with red-and-white route circles, like a neighborhood reactivation map.",
      "Postcard markers move from the completed job to nearby homes and mailboxes.",
      "Scattered city marketing collapses into one dense route cluster around the job.",
      "Final 3D HomeReach logo: Route Density Made Simple.",
    ],
    dmGoal: "Capture trade, city, current service area, and one recent job address to create a free route-density map example.",
    proofAssets: ["Targeted route map", "postcard preview", "service radius visualization", "before and after route cluster"],
    productionMethod: "Use actual home-service footage when available. Use AI only for textless aerial b-roll, then build delivery icons and final copy with HomeReach overlays.",
    qualityBar: [
      "Must show one job becoming the center of the neighborhood map.",
      "Must show nearby homes as the actual target, not a broad citywide blast.",
      "Must explain route density in plain English within the first 10 seconds.",
      "CTA asks for a MAP example, not a vague consultation.",
    ],
    complianceNotes: ["Do not guarantee customers, delivery dates, or USPS performance in the reel."],
  },
  {
    id: "shared-postcard-local-visibility",
    offer: "Co-op Shared Postcards",
    route: PRODUCT_OVERVIEW_PATHS.sharedPostcards,
    startRoute: PRODUCT_START_PATHS.sharedPostcards,
    audience: "Local businesses that want homeowner visibility without paying for an entire solo mail campaign.",
    pain: "Owners need consistent local awareness, but solo direct mail often feels too expensive or too risky to test.",
    promise: "Share premium postcard space with other local businesses and get mailed directly to homeowners at a lower entry cost.",
    hook: "Want mail visibility without the full bill?",
    cta: "Comment POSTCARD to see open spots.",
    commentKeyword: "POSTCARD",
    visualStory: [
      "Small business owner looks at a full campaign quote and hesitates.",
      "The postcard splits into clean premium sections for multiple local businesses.",
      "Homeowners receive one high-visibility shared postcard in the mail.",
      "Owner sees a simple spot reservation screen.",
    ],
    dmGoal: "Identify the business category and city, then route them to available shared postcard spots.",
    proofAssets: ["Shared postcard mockup", "category exclusivity note", "city spot availability", "homeowner mailbox scene"],
    productionMethod: "Use controlled postcard mockups, real mail handling footage, and simple spot-availability overlays.",
    qualityBar: [
      "Explains shared cost in under five seconds.",
      "Makes category exclusivity clear without overcomplicating it.",
      "Does not compete with Supplyfy as the primary offer on procurement pages.",
    ],
    complianceNotes: ["Respect city/category exclusivity logic and existing spot-selection flow."],
  },
  {
    id: "political-mail-command-center",
    offer: "Political Mail Command Center",
    route: PRODUCT_OVERVIEW_PATHS.politicalCampaigns,
    startRoute: PRODUCT_START_PATHS.politicalCampaigns,
    audience: "Candidates, campaign managers, consultants, treasurers, and local political teams.",
    pain: "Campaigns lose time guessing at mail plans, budget tradeoffs, routes, creative status, and print execution.",
    promise: "Plan, price, approve, and execute campaign mail with geography, cost, timeline, and approval visibility.",
    hook: "Your campaign mail plan should not be a guess.",
    cta: "Comment CAMPAIGN for mail options.",
    commentKeyword: "CAMPAIGN",
    visualStory: [
      "Campaign team reviews a messy calendar, budget sheet, and map wall.",
      "HomeReach turns the campaign into mail options with geography, timing, and cost visibility.",
      "Candidate or manager reviews clear options before approval.",
      "Final frame: Clear options. Faster execution. Human approval required.",
    ],
    dmGoal: "Collect office, geography, election date, budget range, and whether campaign copy is already approved.",
    proofAssets: ["Political mail option cards", "district map visual", "campaign timeline", "approval queue"],
    productionMethod: "Use neutral campaign office b-roll and controlled map/mail overlays. No voter profiling visuals.",
    qualityBar: [
      "Uses neutral political logistics language.",
      "No ideology targeting, voter belief inference, or persuasion scoring.",
      "Every claim is about planning, timing, geography, approval, or execution.",
    ],
    complianceNotes: ["Human approval required before any political creative is published or sent."],
  },
  {
    id: "government-contract-bid-os",
    offer: "Government Contract Bid OS",
    route: PRODUCT_OVERVIEW_PATHS.governmentContracts,
    startRoute: PRODUCT_START_PATHS.governmentContracts,
    audience: "Small businesses, contractors, service providers, and suppliers that want to pursue public-sector opportunities.",
    pain: "Owners miss bids because solicitations are hard to read, deadlines move quickly, and requirements are scattered.",
    promise: "Find, organize, and prepare bid opportunities faster with an AI-assisted workflow and human approval gates.",
    hook: "Missing bids you could have chased?",
    cta: "Comment BID for an opportunity review.",
    commentKeyword: "BID",
    visualStory: [
      "Owner scrolls through dense contract listings and looks overwhelmed.",
      "The opportunity is turned into deadline, fit, requirement, and document cards.",
      "A bid room organizes next actions and approval requirements.",
      "Final frame: Stop missing opportunities hidden in paperwork.",
    ],
    dmGoal: "Collect industry, location, capacity, certifications, and contract categories to start an opportunity review.",
    proofAssets: ["Bid room UI", "fit analysis cards", "deadline checklist", "document requirement list"],
    productionMethod: "Use business-office b-roll and controlled checklist overlays. Avoid showing readable solicitation text from AI video.",
    qualityBar: [
      "Makes the bid problem emotionally clear.",
      "Does not imply guaranteed awards.",
      "Shows organization and speed without promising submission.",
    ],
    complianceNotes: ["Do not submit bids, certify compliance, or fabricate qualifications without human approval."],
  },
  {
    id: "ai-website-assistant-lead-capture",
    offer: "AI Website Assistant",
    route: PRODUCT_OVERVIEW_PATHS.aiWebsiteAssistant,
    startRoute: PRODUCT_START_PATHS.aiWebsiteAssistant,
    audience: "Local businesses with websites that do not answer common questions, capture leads, or route prospects after hours.",
    pain: "Visitors leave when the website feels static, confusing, or slow to answer basic buying questions.",
    promise: "Add an assistant that answers, qualifies, and routes visitors while keeping the business in control.",
    hook: "Your website may be losing leads tonight.",
    cta: "Comment WEBSITE for a quick review.",
    commentKeyword: "WEBSITE",
    visualStory: [
      "A customer taps around a local business website and leaves without contacting anyone.",
      "The assistant answers the buying question and captures contact intent.",
      "The owner receives a clear lead summary instead of a missed visitor.",
      "Final frame: Turn more visitors into conversations.",
    ],
    dmGoal: "Collect business website URL, service category, after-hours pain points, and common customer questions.",
    proofAssets: ["assistant demo", "lead summary card", "question flow examples", "after-hours capture visual"],
    productionMethod: "Use real phone and desktop b-roll with deterministic UI mockups added in post.",
    qualityBar: [
      "Shows a specific missed-lead moment.",
      "Does not claim the assistant replaces human sales.",
      "CTA routes to a website review, not a generic demo.",
    ],
    complianceNotes: ["Do not publish customer-facing assistant copy without approval."],
  },
  {
    id: "local-seo-visibility-gap",
    offer: "Local SEO and Visibility",
    route: PRODUCT_OVERVIEW_PATHS.localSeo,
    startRoute: PRODUCT_START_PATHS.localSeo,
    audience: "Local service companies and storefront businesses that rely on nearby buyers finding them first.",
    pain: "Competitors show up ahead of them in local search while their best work stays invisible.",
    promise: "Find visibility gaps, clean up local presence, and create a practical plan for being easier to find.",
    hook: "Can nearby customers find you first?",
    cta: "Comment LOCAL for a visibility review.",
    commentKeyword: "LOCAL",
    visualStory: [
      "Owner searches for their service and sees competitors getting attention.",
      "HomeReach identifies local visibility gaps and profile issues.",
      "Local service area, reviews, and content actions become a simple checklist.",
      "Final frame: Be easier to find before buyers choose someone else.",
    ],
    dmGoal: "Collect business name, city, website, primary service, and current Google Business Profile status.",
    proofAssets: ["visibility scan", "local profile checklist", "service-area map", "content action list"],
    productionMethod: "Use textless phone b-roll and controlled local-search style overlays. Avoid fake ranking screenshots.",
    qualityBar: [
      "Frames the problem as visibility, not guaranteed rankings.",
      "Shows a practical review path.",
      "No fake reviews, fake offices, or ranking promises.",
    ],
    complianceNotes: ["No ranking guarantees, fake citations, doorway pages, or fake review tactics."],
  },
  {
    id: "reputation-review-recovery",
    offer: "Reputation Engine",
    route: PRODUCT_OVERVIEW_PATHS.reputation,
    startRoute: PRODUCT_START_PATHS.reputation,
    audience: "Local businesses that need more review consistency and better response workflows.",
    pain: "A few bad or unanswered reviews can quietly damage trust while happy customers never get asked.",
    promise: "Organize review requests, response drafts, and reputation follow-up with human approval.",
    hook: "Your reviews are costing trust.",
    cta: "Comment REVIEWS for a reputation check.",
    commentKeyword: "REVIEWS",
    visualStory: [
      "Owner sees a concerning review notification and an empty request workflow.",
      "Happy customer moment turns into an approved review request draft.",
      "Response drafts and review follow-ups appear in a simple approval queue.",
      "Final frame: Protect trust before the next customer decides.",
    ],
    dmGoal: "Collect business profile links, review concerns, customer touchpoints, and preferred response style.",
    proofAssets: ["review request workflow", "approval queue", "response draft examples", "trust dashboard"],
    productionMethod: "Use customer-service b-roll and controlled review cards with anonymized examples.",
    qualityBar: [
      "Avoids fear-heavy reputation language.",
      "Clearly shows human approval.",
      "No fake reviews or review-gating implication.",
    ],
    complianceNotes: ["Do not fabricate reviews, suppress negative reviews, or publish responses without approval."],
  },
  {
    id: "property-intelligence-targeting",
    offer: "Property Intelligence",
    route: PRODUCT_OVERVIEW_PATHS.propertyIntelligence,
    startRoute: PRODUCT_START_PATHS.propertyIntelligence,
    audience: "Service businesses and campaigns that need smarter geographic targeting before spending on outreach.",
    pain: "Businesses waste money reaching areas that do not match their service, job type, or best customer profile.",
    promise: "Use property, neighborhood, and geographic context to target better campaigns.",
    hook: "Stop guessing where to market.",
    cta: "Comment MAP for a targeting example.",
    commentKeyword: "MAP",
    visualStory: [
      "Owner looks at a city map and cannot tell where to focus.",
      "HomeReach narrows the area using property and neighborhood intelligence.",
      "Campaign zones become clear, prioritized, and easy to explain.",
      "Final frame: Better targeting before you spend.",
    ],
    dmGoal: "Collect service type, target customer, geography, and recent best-customer examples.",
    proofAssets: ["property overlay", "neighborhood zone map", "route and ZIP comparison", "targeting criteria cards"],
    productionMethod: "Use map-style motion graphics controlled by HomeReach. Avoid fake homeowner-specific claims.",
    qualityBar: [
      "Makes targeting feel practical, not creepy.",
      "Uses geography and property context only.",
      "Does not imply sensitive personal data or individual beliefs.",
    ],
    complianceNotes: ["No sensitive targeting or unsupported claims about individual households."],
  },
  {
    id: "market-capture-multi-channel",
    offer: "Market Capture",
    route: PRODUCT_OVERVIEW_PATHS.marketCapture,
    startRoute: PRODUCT_START_PATHS.marketCapture,
    audience: "Local businesses that need direct mail, digital follow-up, and local visibility working together.",
    pain: "Marketing gets scattered across posts, mailers, ads, and follow-ups with no single execution plan.",
    promise: "Coordinate local visibility, targeted mail, and follow-up into one market-capture workflow.",
    hook: "Your marketing is too scattered.",
    cta: "Comment GROWTH for a capture plan.",
    commentKeyword: "GROWTH",
    visualStory: [
      "Owner jumps between social posts, mail ideas, website leads, and follow-up notes.",
      "HomeReach turns those pieces into one prioritized local growth plan.",
      "Neighborhood targeting, follow-up, and proof assets connect in one view.",
      "Final frame: One plan. More local conversations.",
    ],
    dmGoal: "Collect industry, city, current channels, monthly marketing spend, and the biggest growth bottleneck.",
    proofAssets: ["market capture dashboard", "channel plan", "neighborhood campaign", "follow-up task list"],
    productionMethod: "Use real owner workflow b-roll and controlled dashboard cards. No abstract AI effects.",
    qualityBar: [
      "Explains scattered marketing in plain language.",
      "Shows the plan as execution, not theory.",
      "Keeps CTA focused on a plan request.",
    ],
    complianceNotes: ["No lead volume or revenue guarantees."],
  },
  {
    id: "yard-sign-local-presence",
    offer: "Yard Signs",
    route: PRODUCT_OVERVIEW_PATHS.targetedCampaigns,
    startRoute: PRODUCT_START_PATHS.yardSigns,
    audience: "Campaigns and local service businesses that need visible, offline neighborhood presence.",
    pain: "People forget businesses and campaigns they only see once online.",
    promise: "Add physical visibility that supports neighborhood awareness and campaign recall.",
    hook: "Local visibility should be seen offline too.",
    cta: "Comment SIGNS for options.",
    commentKeyword: "SIGNS",
    visualStory: [
      "A block has no visible local brand presence.",
      "A clean yard sign appears near a completed job or campaign route.",
      "Neighbors see repeated name recognition as they drive or walk by.",
      "Final frame: Pair signs with smarter local targeting.",
    ],
    dmGoal: "Collect business or campaign type, city, quantity range, and whether signs support a larger campaign.",
    proofAssets: ["yard sign mockup", "route placement concept", "campaign bundle card", "local visibility shot"],
    productionMethod: "Use clean product mockups and real neighborhood footage with all text added in post.",
    qualityBar: [
      "Keeps signs as a supporting offer.",
      "Avoids cluttered design samples.",
      "CTA asks for options, not immediate checkout pressure.",
    ],
    complianceNotes: ["Political sign creative requires compliance review and human approval."],
  },
  {
    id: "door-hanger-route-saturation",
    offer: "Door Hangers",
    route: PRODUCT_OVERVIEW_PATHS.targetedCampaigns,
    startRoute: PRODUCT_START_PATHS.doorHangers,
    audience: "Home-service businesses that want a focused neighborhood saturation touchpoint.",
    pain: "Some homeowners ignore broad ads, and businesses need a physical local reminder near active work.",
    promise: "Build a door-hanger campaign around neighborhoods, routes, and service areas.",
    hook: "Make the neighborhood notice you.",
    cta: "Comment DOORS for a route plan.",
    commentKeyword: "DOORS",
    visualStory: [
      "Service crew finishes work on one street.",
      "Nearby doors become a focused route, not a random drop.",
      "A clean door hanger appears at the right homes with controlled offer copy.",
      "Final frame: Local saturation without random guessing.",
    ],
    dmGoal: "Collect trade, service area, desired route size, and offer type.",
    proofAssets: ["door hanger mockup", "route map", "street saturation view", "offer card"],
    productionMethod: "Use real street b-roll and deterministic route graphics. Do not use AI-generated readable door hanger text.",
    qualityBar: [
      "Explains why the route matters.",
      "Does not imply unattended placement where restricted.",
      "Connects the product to campaign execution.",
    ],
    complianceNotes: ["Confirm local placement rules before fulfillment."],
  },
  {
    id: "business-cards-follow-up",
    offer: "Business Cards and Branded Materials",
    route: PRODUCT_OVERVIEW_PATHS.services,
    startRoute: PRODUCT_START_PATHS.businessCards,
    audience: "Local owners, sales teams, contractors, and campaign staff that need credible handoff materials.",
    pain: "A good conversation loses momentum when the follow-up material feels cheap, unclear, or forgettable.",
    promise: "Create premium business cards and branded materials that support trust and next-step clarity.",
    hook: "Your first impression should not feel cheap.",
    cta: "Comment CARDS for a brand kit.",
    commentKeyword: "CARDS",
    visualStory: [
      "Owner hands out a generic card that feels forgettable.",
      "A premium card and QR follow-up material connects to a clear offer.",
      "The prospect scans, saves, or follows up instead of losing the contact.",
      "Final frame: Better handoffs. Cleaner follow-up.",
    ],
    dmGoal: "Collect business name, logo status, offer, QR destination, and preferred style.",
    proofAssets: ["business card mockup", "QR landing page preview", "brand kit colors", "follow-up CTA card"],
    productionMethod: "Use controlled product mockups and real handoff footage. Add all card text in the design layer.",
    qualityBar: [
      "Positions cards as conversion support, not commodity print.",
      "Shows why the next step matters.",
      "Keeps copy simple and premium.",
    ],
    complianceNotes: ["Do not claim print-ready approval without final human review."],
  },
];

export function buildBlueprintCopy(blueprint: RevenueReelBlueprint) {
  return [
    `Offer: ${blueprint.offer}`,
    `Audience: ${blueprint.audience}`,
    `Pain: ${blueprint.pain}`,
    `Promise: ${blueprint.promise}`,
    `Hook: ${blueprint.hook}`,
    `CTA: ${blueprint.cta}`,
    "Visual story:",
    ...blueprint.visualStory.map((scene, index) => `${index + 1}. ${scene}`),
    `DM goal: ${blueprint.dmGoal}`,
    `Production method: ${blueprint.productionMethod}`,
    "Quality bar:",
    ...blueprint.qualityBar.map((item) => `- ${item}`),
    "Compliance notes:",
    ...blueprint.complianceNotes.map((item) => `- ${item}`),
  ].join("\n");
}
