export type PoliticalMapPriority = "MVP" | "Phase 2" | "Phase 3";
export type PoliticalMapSourceType =
  | "public"
  | "paid"
  | "api"
  | "file_upload"
  | "manual"
  | "internal";

export interface PoliticalMapSourceRequirement {
  name: string;
  category: string;
  provides: string;
  sourceType: PoliticalMapSourceType;
  expectedFormat: string;
  coverage: string;
  refreshCadence: string;
  licensingNotes: string;
  costEstimate: string;
  difficulty: "Low" | "Medium" | "High";
  priority: PoliticalMapPriority;
  requiredForMvp: boolean;
  url?: string;
}

export const politicalMapSourceRequirements: PoliticalMapSourceRequirement[] = [
  {
    name: "US Census TIGER/Line",
    category: "Geographic boundaries",
    provides: "State, county, place, ZCTA, tract, block group, congressional, and legislative district boundaries.",
    sourceType: "public",
    expectedFormat: "Shapefile, GeoJSON after ETL",
    coverage: "National",
    refreshCadence: "Annual / decennial by layer",
    licensingNotes: "Public government data; still label TIGER/ZCTA as geographic approximations where applicable.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html",
  },
  {
    name: "Ohio 2026-2032 Congressional Districts",
    category: "Political boundaries",
    provides: "Official Ohio congressional district polygons adopted for the 2026 election cycle and effective through 2032.",
    sourceType: "public",
    expectedFormat: "ArcGIS Feature Service / GeoJSON",
    coverage: "Ohio",
    refreshCadence: "After redistricting adoption or official correction",
    licensingNotes: "Public State of Ohio GIS data; keep source date and display confidence label.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://www.arcgis.com/home/item.html?id=a1c97514126540a182851ce914396f5c",
  },
  {
    name: "Ohio Senate Districts 2024-2032",
    category: "Political boundaries",
    provides: "Official Ohio Senate district map, equivalency file, legal description, and SHAPE file package.",
    sourceType: "public",
    expectedFormat: "SHAPE ZIP, XLSX equivalency file, PDF map",
    coverage: "Ohio",
    refreshCadence: "After redistricting adoption or official correction",
    licensingNotes: "Official Ohio Secretary of State publication; store source cycle and downloaded file date.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://www.ohiosos.gov/elections/district-maps",
  },
  {
    name: "Ohio House Districts 2024-2032",
    category: "Political boundaries",
    provides: "Official Ohio House district map, equivalency file, legal description, and SHAPE file package.",
    sourceType: "public",
    expectedFormat: "SHAPE ZIP, XLSX equivalency file, PDF map",
    coverage: "Ohio",
    refreshCadence: "After redistricting adoption or official correction",
    licensingNotes: "Official Ohio Secretary of State publication; store source cycle and downloaded file date.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://www.ohiosos.gov/elections/district-maps",
  },
  {
    name: "Census TIGERweb Legislative Areas",
    category: "Political boundaries",
    provides: "National congressional and state legislative district FeatureServer layers in JSON, GeoJSON, and PBF formats.",
    sourceType: "public",
    expectedFormat: "ArcGIS REST Feature Layer, GeoJSON/PBF query output",
    coverage: "National",
    refreshCadence: "Census vintage releases",
    licensingNotes: "Public Census data; official state sources still win where state-published election-cycle files differ.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Legislative/MapServer/layers",
  },
  {
    name: "Illinois ILBoundaries Legislative Layers",
    category: "Political boundaries",
    provides: "Illinois congressional, State House, State Senate, political township, county, and town boundary layers.",
    sourceType: "public",
    expectedFormat: "ArcGIS REST MapServer / GeoJSON query output",
    coverage: "Illinois",
    refreshCadence: "State GIS service updates",
    licensingNotes: "Public Illinois DOT/State GIS boundary service; retain layer id, source URL, and access date.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://gis1.dot.illinois.gov/arcgis/rest/services/MapBase/ILBoundaries/MapServer",
  },
  {
    name: "Tennessee TNMap Legislative Districts",
    category: "Political boundaries",
    provides: "Tennessee congressional, State Senate, and State House 2022 legislative district boundaries.",
    sourceType: "public",
    expectedFormat: "ArcGIS REST MapServer / GeoJSON/PBF query output",
    coverage: "Tennessee",
    refreshCadence: "After legislative redistricting or state GIS service updates",
    licensingNotes: "Published through TNMap with Tennessee Legislature copyright text; retain source metadata and access date.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://tnmap.tn.gov/arcgis/rest/services/ADMINISTRATIVE_BOUNDARIES/LEGISLATIVE_DISTRICTS/MapServer",
  },
  {
    name: "Ohio School District Boundaries 2025",
    category: "Education boundaries",
    provides: "Ohio local school district polygons with IRN, tax ID, county code, and district name fields.",
    sourceType: "public",
    expectedFormat: "ArcGIS FeatureServer query/export",
    coverage: "Ohio",
    refreshCadence: "State GIS publication cycle",
    licensingNotes: "Official State of Ohio GIS layer; verify state-board-of-education districts separately through Ohio SOS.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://maps.ohio.gov/arcgis/rest/services/Hosted/Ohio_School_Districts_2025/FeatureServer/0",
  },
  {
    name: "Ohio Municipal Boundaries",
    category: "Municipal boundaries",
    provides: "Official Ohio city and village municipal polygons with municipality and population fields.",
    sourceType: "public",
    expectedFormat: "ArcGIS FeatureServer query/export",
    coverage: "Ohio",
    refreshCadence: "State GIS publication cycle",
    licensingNotes: "Official State of Ohio municipal boundary layer; use Census Places as national fallback.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://maps.ohio.gov/arcgis/rest/services/Hosted/Ohio_Municipal_Boundaries/FeatureServer/0",
  },
  {
    name: "Ohio Township Boundaries",
    category: "Local boundaries",
    provides: "Ohio township polygons for county subdivision and local race planning context.",
    sourceType: "public",
    expectedFormat: "ArcGIS FeatureServer query/export",
    coverage: "Ohio",
    refreshCadence: "State GIS publication cycle",
    licensingNotes: "State of Ohio GIS/OGRIP boundary layer; retain source limitations in metadata.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://maps.ohio.gov/arcgis/rest/services/Hosted/Ohio_Township_Boundaries/FeatureServer",
  },
  {
    name: "Census TIGERweb Tracts and Blocks",
    category: "Census geography",
    provides: "Census tract, block group, and block services for aggregate demographic overlays.",
    sourceType: "public",
    expectedFormat: "ArcGIS REST MapServer / TIGER/Line shapefile",
    coverage: "National",
    refreshCadence: "Census vintage releases",
    licensingNotes: "Public Census data; use aggregate ACS joins only.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Tracts_Blocks/MapServer",
  },
  {
    name: "Census TIGERweb Places and County Subdivisions",
    category: "Municipal boundaries",
    provides: "National places, county subdivisions, consolidated cities, and related municipal geography.",
    sourceType: "public",
    expectedFormat: "ArcGIS REST MapServer / TIGER/Line shapefile",
    coverage: "National",
    refreshCadence: "Census vintage releases",
    licensingNotes: "Public Census data; label ZCTA/place/county subdivision distinctions clearly.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Places_CouSub_ConCity_SubMCD/MapServer/layers",
  },
  {
    name: "Ohio Court of Appeals Districts",
    category: "Judicial boundaries",
    provides: "Official Ohio appellate district reference map for judicial race geography.",
    sourceType: "public",
    expectedFormat: "PDF map / county-based conversion",
    coverage: "Ohio",
    refreshCadence: "After statutory district change",
    licensingNotes: "Ohio SOS notes Appeals Court districts are not determined by census data; convert cautiously and retain citation.",
    costEstimate: "Free plus conversion labor",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://www.ohiosos.gov/elections/district-maps",
  },
  {
    name: "USPS EDDM Online Tool",
    category: "USPS mail planning",
    provides: "Route-level EDDM counts and selectable route planning reference.",
    sourceType: "manual",
    expectedFormat: "Manual export/import or verified operator entry until a licensed route source is connected",
    coverage: "National USPS service area",
    refreshCadence: "USPS-managed; verify before proposal/checkout",
    licensingNotes: "Use as official planning/reference surface; do not scrape in a way that violates USPS terms.",
    costEstimate: "Free tool; operational labor required",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://eddm.usps.com/eddm/select-routes.htm",
  },
  {
    name: "Licensed USPS carrier route polygons",
    category: "USPS mail execution",
    provides: "Carrier route boundaries, centroids, ZIP/route keys, and route geometry for spatial overlap.",
    sourceType: "paid",
    expectedFormat: "Shapefile, GeoJSON, WKT, PostGIS-loadable files",
    coverage: "National, usually quarterly vendor releases",
    refreshCadence: "Monthly or quarterly depending on vendor",
    licensingNotes: "Required for production-grade route polygons and redistribution/display rights.",
    costEstimate: "Paid vendor quote",
    difficulty: "High",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://www.precisely.com/data-guide/products/usps-zip-codes-plus-four-carrier-routes/",
  },
  {
    name: "Supabase PostGIS",
    category: "GIS storage and overlap",
    provides: "Spatial storage, indexing, ST_Intersects/ST_Intersection overlap calculations, and server-side geometry QA.",
    sourceType: "internal",
    expectedFormat: "PostGIS geometry/geography columns plus normalized metadata tables",
    coverage: "Internal",
    refreshCadence: "Continuous",
    licensingNotes: "Requires enabling the PostGIS extension in Supabase.",
    costEstimate: "Included with Supabase plan; compute/storage may increase with tiles and geometry volume",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://supabase.com/docs/guides/database/extensions/postgis",
  },
  {
    name: "MapLibre GL JS",
    category: "Mapping UI",
    provides: "Open-source, GPU-accelerated vector map renderer for production polygon overlays.",
    sourceType: "public",
    expectedFormat: "Vector tiles, GeoJSON, PMTiles/MBTiles through compatible servers",
    coverage: "Client library",
    refreshCadence: "Package upgrades",
    licensingNotes: "Open-source renderer; basemap/tile licensing remains separate.",
    costEstimate: "Free library; tile hosting costs separate",
    difficulty: "Medium",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://maplibre.org/projects/gl-js/",
  },
  {
    name: "Turf.js",
    category: "GIS calculation",
    provides: "Client/server fallback spatial intersection, containment, area, and polygon helpers.",
    sourceType: "public",
    expectedFormat: "GeoJSON",
    coverage: "Client/server library",
    refreshCadence: "Package upgrades",
    licensingNotes: "Use for previews; production pricing should use server-side verified data.",
    costEstimate: "Free",
    difficulty: "Low",
    priority: "MVP",
    requiredForMvp: true,
    url: "https://turfjs.org/",
  },
  {
    name: "Ohio Secretary of State DATA/election results",
    category: "Election data",
    provides: "Certified election results, historical voting trends, absentee/early-vote data, and statewide aggregate dashboards.",
    sourceType: "public",
    expectedFormat: "CSV, XLSX, dashboards, public downloads",
    coverage: "Ohio",
    refreshCadence: "Election cycle / certified result updates",
    licensingNotes: "Aggregate geography use only; label as public aggregate.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://www.ohiosos.gov/elections/election-results-and-data/2024/",
  },
  {
    name: "County board of elections precinct shapefiles",
    category: "Political boundaries",
    provides: "Precinct, ward, and local voting district shapes where published by county election offices.",
    sourceType: "public",
    expectedFormat: "Shapefile, GeoJSON, PDF conversion in weaker counties",
    coverage: "County-by-county",
    refreshCadence: "After redistricting and precinct changes",
    licensingNotes: "Availability and field naming vary; must store source date per county.",
    costEstimate: "Free to moderate labor",
    difficulty: "High",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://vote.franklincountyohio.gov/Maps-Data/GIS-Shape-Files",
  },
  {
    name: "Illinois State Board / Illinois Election Data",
    category: "Election data",
    provides: "Illinois precinct-level result data and formatted statewide result files.",
    sourceType: "public",
    expectedFormat: "CSV, flat files, Access sample database",
    coverage: "Illinois",
    refreshCadence: "Election cycle",
    licensingNotes: "Use aggregate geography only and link back to source lineage.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://illinoiselectiondata.com/analysis/precinct/",
  },
  {
    name: "Tennessee Secretary of State election results",
    category: "Election data",
    provides: "Historical results by office, county, precinct, and spreadsheets where available.",
    sourceType: "public",
    expectedFormat: "HTML, PDF, XLSX/CSV where available",
    coverage: "Tennessee",
    refreshCadence: "Election cycle",
    licensingNotes: "Use aggregate geography only; normalize precinct names carefully.",
    costEstimate: "Free",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://sos.tn.gov/elections/results",
  },
  {
    name: "Google Civic Information API",
    category: "Civic data",
    provides: "Civic divisions, representatives, polling and election information during supported elections.",
    sourceType: "api",
    expectedFormat: "JSON API",
    coverage: "US, coverage varies by election",
    refreshCadence: "Google-managed",
    licensingNotes: "Use as supplemental civic context, not as authoritative route pricing data.",
    costEstimate: "Google API terms/quota",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://developers.google.com/civic-information",
  },
  {
    name: "FEC API",
    category: "Campaign data",
    provides: "Federal candidate, committee, and campaign finance records.",
    sourceType: "api",
    expectedFormat: "JSON API / exports",
    coverage: "Federal races",
    refreshCadence: "FEC filing updates",
    licensingNotes: "Useful for lead discovery and context, not voter targeting.",
    costEstimate: "Free API key, rate limits apply",
    difficulty: "Low",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://www.fec.gov/data/",
  },
  {
    name: "Smarty or Melissa address validation",
    category: "Address quality",
    provides: "CASS/DPV address validation, address standardization, deliverability checks, and NCOA options.",
    sourceType: "api",
    expectedFormat: "JSON API / batch files",
    coverage: "US and international depending on product",
    refreshCadence: "Vendor-managed",
    licensingNotes: "Needed for campaign-provided address lists; handle PII under contract and retention rules.",
    costEstimate: "Paid usage tiers",
    difficulty: "Medium",
    priority: "Phase 2",
    requiredForMvp: false,
    url: "https://www.smarty.com/docs",
  },
  {
    name: "Lob or PostGrid",
    category: "Print/mail API",
    provides: "Direct mail APIs, address verification, postcards, letters, and mail status webhooks.",
    sourceType: "api",
    expectedFormat: "JSON API and webhooks",
    coverage: "Vendor-defined",
    refreshCadence: "Operational",
    licensingNotes: "Useful if HomeReach outsources or automates fulfillment; evaluate margin impact.",
    costEstimate: "Paid per piece / platform pricing",
    difficulty: "Medium",
    priority: "Phase 3",
    requiredForMvp: false,
    url: "https://docs.lob.com/",
  },
  {
    name: "Regrid or ATTOM property data",
    category: "Property and household data",
    provides: "Parcel shapes, property attributes, homeownership, valuation, and address-linked property context.",
    sourceType: "paid",
    expectedFormat: "API, bulk files, feature service",
    coverage: "National, vendor-dependent",
    refreshCadence: "Vendor-managed, often monthly/quarterly",
    licensingNotes: "Only use in aggregate or campaign-provided contexts; avoid sensitive individual inference.",
    costEstimate: "Paid vendor quote",
    difficulty: "High",
    priority: "Phase 3",
    requiredForMvp: false,
    url: "https://support.regrid.com/api/using-the-parcel-api",
  },
  {
    name: "Data Axle",
    category: "Consumer/business data",
    provides: "Business/consumer records, contacts, addresses, and enrichment attributes.",
    sourceType: "paid",
    expectedFormat: "API / batch data",
    coverage: "US",
    refreshCadence: "Vendor-managed",
    licensingNotes: "Requires campaign-use legal review, consent/compliance checks, and strict separation from prohibited voter inference.",
    costEstimate: "Paid per-thousand tiers",
    difficulty: "High",
    priority: "Phase 3",
    requiredForMvp: false,
    url: "https://www.data-axle.com/data-solutions/apis/",
  },
];

export const dataQualityLabels = [
  {
    label: "Exact",
    meaning: "Verified from a current authoritative source or HomeReach production record.",
  },
  {
    label: "Estimated",
    meaning: "Calculated from known inputs, public aggregates, or route-level assumptions.",
  },
  {
    label: "Demo/Sample",
    meaning: "Used only for product demonstration until an authoritative dataset is imported.",
  },
  {
    label: "User-Provided",
    meaning: "Uploaded or entered by a campaign, consultant, sales rep, or admin.",
  },
  {
    label: "Public Aggregate",
    meaning: "Published at a geography level such as county, district, precinct, tract, or route.",
  },
  {
    label: "Paid Vendor Data",
    meaning: "Licensed from a third-party data provider with contractual use limits.",
  },
  {
    label: "Unavailable",
    meaning: "Not connected yet; do not use for production pricing or fulfillment decisions.",
  },
];

export function sourceRequirementsByPriority(priority: PoliticalMapPriority) {
  return politicalMapSourceRequirements.filter((source) => source.priority === priority);
}
