import { NextResponse } from "next/server";
import { requireAdmin, requireAdminOrCron, requireCron } from "@/lib/auth/api-guards";
import {
  buildDailyBriefMarkdown,
  loadFoundationControlTower,
  persistDailyExecutiveBrief,
} from "@/lib/control-tower/foundation";
import { logPlatformAuditEvent } from "@/lib/audit/platform-audit";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function GET(req: Request) {
  const cron = requireCron(req);
  if (cron.ok) {
    const result = await persistDailyExecutiveBrief();
    await logPlatformAuditEvent({
      actorType: "cron",
      module: "control_tower",
      actionType: "daily_brief_generated",
      entityType: "platform_daily_brief",
      entityId: result.id,
      resultStatus: result.ok ? "success" : "failure",
      severity: result.ok ? "info" : "high",
      message: result.ok ? "Daily executive brief generated by cron." : "Daily executive brief cron generation failed.",
      errorMessage: result.error,
      metadata: {
        generated_at: result.data.dailyBrief.generatedAt,
        summary: result.data.dailyBrief.summary,
      },
    });

    return NextResponse.json(
      {
        ok: result.ok,
        id: result.id,
        error: result.error,
        brief: result.data.dailyBrief,
        markdown: buildDailyBriefMarkdown(result.data),
      },
      { status: result.ok ? 200 : 500 },
    );
  }

  const guard = await requireAdmin();
  if (!guard.ok) return guard.response;

  const data = await loadFoundationControlTower();
  return NextResponse.json({
    brief: data.dailyBrief,
    markdown: buildDailyBriefMarkdown(data),
  });
}

export async function POST(req: Request) {
  const guard = await requireAdminOrCron(req);
  if (!guard.ok) return guard.response;

  const result = await persistDailyExecutiveBrief({
    actorId: guard.user?.id ?? null,
  });

  await logPlatformAuditEvent({
    actorType: guard.user ? "human" : "cron",
    actorId: guard.user?.id ?? null,
    module: "control_tower",
    actionType: "daily_brief_generated",
    entityType: "platform_daily_brief",
    entityId: result.id,
    resultStatus: result.ok ? "success" : "failure",
    severity: result.ok ? "info" : "high",
    message: result.ok ? "Daily executive brief generated." : "Daily executive brief generation failed.",
    errorMessage: result.error,
    metadata: {
      generated_at: result.data.dailyBrief.generatedAt,
      summary: result.data.dailyBrief.summary,
    },
  });

  return NextResponse.json(
    {
      ok: result.ok,
      id: result.id,
      error: result.error,
      brief: result.data.dailyBrief,
      markdown: buildDailyBriefMarkdown(result.data),
    },
    { status: result.ok ? 200 : 500 },
  );
}
