import type { GovContractDashboardData, GovContractOpportunity } from "./types";
import { recommendedActionFor, scoreGovContractOpportunity } from "./scoring";

function sampleOpportunity(base: Omit<GovContractOpportunity, "fitStatus" | "fitScore" | "riskScore" | "urgencyScore" | "urgency" | "scoreBreakdown" | "recommendedNextAction" | "scoringReason" | "missingItems" | "isSample">): GovContractOpportunity {
  const scored = scoreGovContractOpportunity({
    title: base.title,
    agency: base.agency,
    noticeType: base.noticeType,
    naicsCode: base.naicsCode,
    pscCode: base.pscCode,
    setAsideDescription: base.setAsideDescription,
    dueDate: base.dueDate,
    estimatedValueCents: base.estimatedValueCents,
    locationState: base.location.state,
    summary: base.summary,
  });

  const withScore = {
    ...base,
    ...scored,
    isSample: true,
  };

  return {
    ...withScore,
    recommendedNextAction: recommendedActionFor(withScore),
  };
}

export const SAMPLE_GOV_CONTRACT_OPPORTUNITIES: GovContractOpportunity[] = [
  sampleOpportunity({
    id: "sample-print-mail-001",
    sourceSystem: "sample",
    sourceId: "SAM-SAMPLE-PRINT-001",
    sourceUrl: null,
    title: "Printing, Addressing, and Mailing Services for Public Information Postcards",
    agency: "Sample State Health Agency",
    department: "Sample Department of Administration",
    office: "Procurement Services",
    solicitationNumber: "SAMPLE-RFP-26-104",
    noticeType: "Solicitation",
    baseNoticeType: "Combined Synopsis/Solicitation",
    postedDate: "2026-05-15",
    dueDate: "2026-06-04T21:00:00.000Z",
    questionsDeadline: "2026-05-24T21:00:00.000Z",
    siteVisitAt: null,
    naicsCode: "541860",
    pscCode: "R701",
    setAsideCode: "SBA",
    setAsideDescription: "Total Small Business Set-Aside",
    estimatedValueCents: 27500000,
    awardAmountCents: null,
    location: { city: "Columbus", state: "OH", zip: "43215", country: "USA", label: "Columbus, OH" },
    pipelineStatus: "new",
    summary:
      "Sample opportunity for postcard production, address processing, mail preparation, and delivery reporting. Replace with live SAM.gov data after SAM_GOV_API_KEY is configured.",
    complianceNotes: [
      "Sample planning record only; do not treat as a live solicitation.",
      "Human approval required before pricing, subcontractor commitments, or proposal submission.",
    ],
    attachments: [],
    amendmentCount: 0,
    lastSyncedAt: null,
  }),
  sampleOpportunity({
    id: "sample-courier-002",
    sourceSystem: "sample",
    sourceId: "SAM-SAMPLE-COURIER-002",
    sourceUrl: null,
    title: "Courier and Scheduled Delivery Support for Regional Field Offices",
    agency: "Sample Federal Field Office",
    department: "Sample Federal Agency",
    office: "Logistics Branch",
    solicitationNumber: "SAMPLE-RFQ-26-220",
    noticeType: "Sources Sought",
    baseNoticeType: "Sources Sought",
    postedDate: "2026-05-17",
    dueDate: "2026-05-28T20:00:00.000Z",
    questionsDeadline: "2026-05-22T20:00:00.000Z",
    siteVisitAt: null,
    naicsCode: "492110",
    pscCode: "V119",
    setAsideCode: null,
    setAsideDescription: null,
    estimatedValueCents: 12000000,
    awardAmountCents: null,
    location: { city: "Cleveland", state: "OH", zip: "44114", country: "USA", label: "Cleveland, OH region" },
    pipelineStatus: "reviewing",
    summary:
      "Sample courier logistics opportunity that may require regional subcontractor coverage and proof of insurance.",
    complianceNotes: [
      "Verify insurance, vehicle, and performance requirements before outreach.",
      "No subcontractor commitment without written human approval.",
    ],
    attachments: [],
    amendmentCount: 1,
    lastSyncedAt: null,
  }),
  sampleOpportunity({
    id: "sample-grounds-003",
    sourceSystem: "sample",
    sourceId: "SAM-SAMPLE-GROUNDS-003",
    sourceUrl: null,
    title: "Grounds Maintenance and Seasonal Facilities Support",
    agency: "Sample County Facilities Department",
    department: "Local Government",
    office: "Facilities Procurement",
    solicitationNumber: "SAMPLE-IFB-26-330",
    noticeType: "Presolicitation",
    baseNoticeType: "Presolicitation",
    postedDate: "2026-05-12",
    dueDate: "2026-06-18T19:00:00.000Z",
    questionsDeadline: "2026-06-02T19:00:00.000Z",
    siteVisitAt: "2026-05-29T14:00:00.000Z",
    naicsCode: "561730",
    pscCode: "S208",
    setAsideCode: "SBA",
    setAsideDescription: "Total Small Business Set-Aside",
    estimatedValueCents: 48000000,
    awardAmountCents: null,
    location: { city: "Akron", state: "OH", zip: "44308", country: "USA", label: "Summit County, OH" },
    pipelineStatus: "need_subcontractor",
    summary:
      "Sample grounds and facilities support opportunity. HomeReach would likely need local subcontractor matching and quote collection.",
    complianceNotes: [
      "Site visit and local labor capacity need confirmation.",
      "Bid readiness depends on subcontractor quotes and insurance documents.",
    ],
    attachments: [],
    amendmentCount: 0,
    lastSyncedAt: null,
  }),
  sampleOpportunity({
    id: "sample-fulfillment-004",
    sourceSystem: "sample",
    sourceId: "SAM-SAMPLE-FULFILLMENT-004",
    sourceUrl: null,
    title: "Warehouse Kitting, Packing, and Distribution Services",
    agency: "Sample Public Safety Agency",
    department: "Sample Department of Public Safety",
    office: "Supply Chain Office",
    solicitationNumber: "SAMPLE-RFI-26-410",
    noticeType: "Special Notice",
    baseNoticeType: "Special Notice",
    postedDate: "2026-05-10",
    dueDate: "2026-05-23T21:00:00.000Z",
    questionsDeadline: null,
    siteVisitAt: null,
    naicsCode: "493110",
    pscCode: "R706",
    setAsideCode: null,
    setAsideDescription: null,
    estimatedValueCents: null,
    awardAmountCents: null,
    location: { city: "Dayton", state: "OH", zip: "45402", country: "USA", label: "Dayton, OH" },
    pipelineStatus: "new",
    summary:
      "Sample distribution and fulfillment opportunity. Requires value clarification and warehouse partner availability.",
    complianceNotes: [
      "Estimated value is missing; use only for workflow demonstration.",
      "No pricing commitment until scope and volumes are verified.",
    ],
    attachments: [],
    amendmentCount: 0,
    lastSyncedAt: null,
  }),
];

export function buildSampleGovContractsDashboard(): GovContractDashboardData {
  const opportunities = SAMPLE_GOV_CONTRACT_OPPORTUNITIES;
  return {
    sourceLabel: "sample",
    opportunities,
    sync: {
      configured: false,
      status: "sample_data",
      lastRunAt: null,
      message:
        "SAM.gov is not connected in this environment. These are clearly labeled sample planning records for workflow QA.",
    },
    summary: {
      newOpportunities: opportunities.filter((o) => o.pipelineStatus === "new").length,
      strongFit: opportunities.filter((o) => o.fitStatus === "strong_fit").length,
      deadlinesThisWeek: opportunities.filter((o) => o.urgency === "high" || o.urgency === "critical").length,
      bidsInProgress: opportunities.filter((o) => ["reviewing", "need_subcontractor", "bid_prep"].includes(o.pipelineStatus)).length,
      submittedBids: opportunities.filter((o) => o.pipelineStatus === "submitted").length,
      awardedBids: opportunities.filter((o) => o.pipelineStatus === "awarded").length,
      estimatedPipelineValueCents: opportunities.reduce((sum, o) => sum + (o.estimatedValueCents ?? 0), 0),
      pendingApprovals: 2,
      missingDocuments: opportunities.reduce((sum, o) => sum + o.missingItems.length, 0),
      requiredActionsToday: 3,
    },
  };
}
