import type {
  AgentDefinition,
  CtaAuditItem,
  GrowthEngineBlueprint,
  GrowthEngineSection,
  IntegrationRequirement,
  RevenuePagePlan,
  RevenuePathStep,
  ReviewQueueBlueprintItem,
} from "./types";

export const growthEngineBlueprint: GrowthEngineBlueprint = {
  title: "HomeReach Growth Engine Blueprint",
  summary:
    "A controlled orchestration layer that turns SEO opportunities, local pages, blog briefs, social posts, postcard concepts, and political campaign content into reviewed revenue actions.",
  principle:
    "Codex coordinates research, drafting, QA, and routing while existing HomeReach systems keep ownership of intake, Stripe, dashboards, campaign records, maps, and approvals.",
  flow: [
    "Research signals enter through Content Intelligence, SEO opportunity planning, competitor notes, campaign intelligence, and sales feedback.",
    "Growth agents convert signals into draft briefs for SEO pages, local landing pages, blogs, social posts, postcard concepts, and political campaign content.",
    "Every draft enters Human Review by default with clear source, channel, CTA, owner, and safety notes.",
    "Approved SEO and local pages move into the existing SEO Engine and sitemap flow; social posts move to the social scheduler connector; postcard concepts move to ad designer or political creative review.",
    "Leads and customers continue through existing CTA paths, intake, proposal, Stripe checkout, contracts, admin visibility, sales follow-up, and customer dashboards.",
    "Performance data returns to Growth Intelligence, admin, sales, reporting, and weekly growth summaries.",
  ],
  connections: [
    {
      from: "SEO Command Center",
      to: "Existing SEO Engine",
      handoff: "Approved briefs become draft SEO pages through /api/admin/seo-engine/pages.",
      guardrail: "No page publishes without quality checks, inventory checks, and human approval.",
    },
    {
      from: "Local Landing Page Engine",
      to: "Website CTA and intake",
      handoff: "Local page CTAs route to /get-started, political plan pages, or lead capture.",
      guardrail: "No CTA bypasses account creation, city/category availability, or existing Stripe checkout.",
    },
    {
      from: "Blog Content Engine",
      to: "Human Review Queue",
      handoff: "Blog briefs are drafted with metadata, internal links, FAQ, image prompts, and social repurposing.",
      guardrail: "Drafts remain unpublished until reviewed and marked approved.",
    },
    {
      from: "RSS Repurposing",
      to: "Social Media Engine",
      handoff: "Published content can generate Facebook, LinkedIn, Instagram, X, GBP, email, SMS-safe, and postcard snippets.",
      guardrail: "Repurposed posts default to Needs Review and do not auto-post.",
    },
    {
      from: "Postcard Creative Engine",
      to: "Ad Designer and Political Creative",
      handoff: "Approved concepts become creative briefs for shared postcards, local campaigns, targeted campaigns, or political waves.",
      guardrail: "Creative remains a draft until approved by HomeReach or campaign staff.",
    },
    {
      from: "Performance Dashboard",
      to: "Admin and Sales Dashboards",
      handoff: "Leads, published assets, reviews, campaign assets, and Stripe revenue roll into operational reporting.",
      guardrail: "Margin and admin-only metrics stay out of customer-facing screens.",
    },
  ],
  protectedFlows: [
    "Homepage CTA paths",
    "Get-started intake",
    "City/category exclusivity",
    "Spot availability",
    "Auth/login",
    "Stripe checkout and webhooks",
    "Contracts",
    "Admin dashboard",
    "Sales dashboard",
    "Political dashboard",
    "Customer dashboard",
    "Twilio, Postmark, and email/SMS workflows",
    "Supabase schema integrity",
  ],
  internalApproval: {
    status: "approved_for_additive_mvp",
    reason:
      "The blueprint reuses existing admin, SEO, content intelligence, review, campaign, intake, and payment systems. It adds orchestration, exports, and review visibility without replacing production flows.",
  },
};

export const growthEngineSections: GrowthEngineSection[] = [
  {
    id: "seo-command-center",
    title: "SEO Command Center",
    description:
      "Plan revenue-first SEO pages by service, city, county, ZIP, campaign type, buyer intent, CTA, and internal links.",
    owner: "SEO Research Agent",
    status: "ready",
    connectedSystems: ["SEO Engine", "Sitemap", "Robots", "Human Review Queue"],
    primaryAction: { label: "Review Top 25 Pages", href: "#top-revenue-pages" },
    secondaryAction: { label: "Open SEO Engine", href: "/admin/traffic-engine" },
    metrics: ["opportunities", "drafts", "approved pages", "indexed pages", "leads"],
    safeguards: ["human review", "quality checks", "source notes", "no keyword stuffing"],
  },
  {
    id: "local-landing-page-engine",
    title: "Local Landing Page Engine",
    description:
      "Create city, county, ZIP, and service page briefs with mobile CTAs, FAQ, schema notes, and intake routing.",
    owner: "Local Landing Page Agent",
    status: "ready",
    connectedSystems: ["Existing /[slug] pages", "SEO Engine", "Get Started", "Sales follow-up"],
    primaryAction: { label: "View Landing Page Plan", href: "#top-revenue-pages" },
    secondaryAction: { label: "Start Intake QA", href: "/get-started" },
    metrics: ["local drafts", "service drafts", "CTA clicks", "intake starts"],
    safeguards: ["availability respected", "city/category rules preserved", "pricing not invented"],
  },
  {
    id: "blog-content-engine",
    title: "Blog Content Engine",
    description:
      "Generate article briefs with outlines, metadata, internal links, image prompts, social snippets, and postcard ideas.",
    owner: "Blog Content Agent",
    status: "manual_review",
    connectedSystems: ["Content Intelligence", "Review Queue", "SEO Engine"],
    primaryAction: { label: "Open Content Intelligence", href: "/admin/content-intel" },
    metrics: ["topic clusters", "draft briefs", "reviewed articles", "CTA blocks"],
    safeguards: ["no auto-publish", "local specificity check", "no fake testimonials"],
  },
  {
    id: "social-media-engine",
    title: "Social Media Engine",
    description:
      "Turn approved content into platform-specific posts for Facebook, Instagram, LinkedIn, X, GBP, email, and SMS-safe follow-ups.",
    owner: "Social Media Agent",
    status: "needs_config",
    connectedSystems: ["Blotato connector placeholder", "Human Review Queue", "Sales Engine"],
    primaryAction: { label: "Review Social Workflow", href: "#integrations" },
    metrics: ["posts drafted", "posts approved", "posts scheduled", "clicks", "leads"],
    safeguards: ["review required", "account discovery required", "no posting without API key"],
  },
  {
    id: "political-content-engine",
    title: "Political Content Engine",
    description:
      "Prepare campaign landing copy, mail waves, county/city/ZIP summaries, proposal language, social drafts, and postcard concepts.",
    owner: "Political Campaign Agent",
    status: "connected",
    connectedSystems: ["Political dashboard", "Candidate Agent", "Political maps", "Proposal workflow"],
    primaryAction: { label: "Open Political Agent", href: "/political/candidate-agent" },
    secondaryAction: { label: "Open Admin Political", href: "/admin/political" },
    metrics: ["campaign briefs", "mail plans", "creative drafts", "proposals"],
    safeguards: [
      "aggregate geography only",
      "no ideology scoring",
      "no individual voter inference",
      "human approval before proposal",
    ],
  },
  {
    id: "postcard-creative-engine",
    title: "Postcard Creative Engine",
    description:
      "Generate reviewed creative briefs for shared 9x12 cards, local business campaigns, political mail waves, and targeted route campaigns.",
    owner: "Postcard Creative Agent",
    status: "connected",
    connectedSystems: ["Ad Designer", "Political creative", "Canva Design OS", "Admin review"],
    primaryAction: { label: "Open Ad Designer", href: "/admin/ad-designer" },
    secondaryAction: { label: "Open Canva Design OS", href: "/admin/canva" },
    metrics: ["concepts", "revisions", "approvals", "print-ready files"],
    safeguards: ["draft status by default", "disclaimer reminders", "approval before production"],
  },
  {
    id: "competitor-research-engine",
    title: "Competitor Research Engine",
    description:
      "Track competitor positioning, local gaps, offer gaps, SEO opportunities, and page angles without automated scraping by default.",
    owner: "Competitor Research Agent",
    status: "manual_review",
    connectedSystems: ["Content Intelligence", "SEO planning", "Sales notes"],
    primaryAction: { label: "Open Competitor Insights", href: "/admin/content-intel" },
    metrics: ["competitors", "gaps", "angles", "priority pages"],
    safeguards: ["manual source notes", "SerpAPI paused", "no unsourced claims"],
  },
  {
    id: "cta-button-audit",
    title: "CTA/Button Optimization Audit",
    description:
      "Track revenue-critical CTAs across homepage, services, intake, political, admin, sales, checkout, and campaign flows.",
    owner: "CTA Audit Agent",
    status: "ready",
    connectedSystems: ["Website", "Intake", "Stripe", "Admin", "Sales", "Political"],
    primaryAction: { label: "Review CTA Audit", href: "#cta-audit" },
    metrics: ["audited CTAs", "broken links", "fixed CTAs", "conversion blockers"],
    safeguards: ["no dead links", "auth respected", "no duplicate records"],
  },
  {
    id: "publishing-review",
    title: "Publishing Queue and Human Review",
    description:
      "Single approval lane for SEO pages, articles, social posts, postcard concepts, political content, email/SMS drafts, and image prompts.",
    owner: "Revenue Integrity Agent",
    status: "ready",
    connectedSystems: ["Review Queue", "SEO Engine", "Content Intelligence", "Ad Designer"],
    primaryAction: { label: "Review Queue", href: "#review-queue" },
    metrics: ["drafts", "needs review", "approved", "scheduled", "published"],
    safeguards: ["default status Draft", "approve before publish", "publish action separated from draft"],
  },
  {
    id: "performance-dashboard",
    title: "Performance Dashboard",
    description:
      "Unify SEO, social, sales, political, postcard, lead, and Stripe performance into weekly growth decisions.",
    owner: "Weekly Growth Report Agent",
    status: "ready",
    connectedSystems: ["Growth Intelligence", "Sales dashboard", "Orders", "Campaign metrics"],
    primaryAction: { label: "Open Growth Intelligence", href: "/admin/growth" },
    metrics: ["leads", "published assets", "Stripe revenue", "campaigns", "follow-ups"],
    safeguards: ["sample metrics labeled", "live metrics require source", "admin margin stays admin-only"],
  },
];

export const topRevenuePages: RevenuePagePlan[] = [
  {
    rank: 1,
    title: "Shared Postcards in Akron, Ohio",
    slug: "/ohio/akron/shared-postcards",
    pageType: "local",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "shared postcards Akron Ohio",
    supportingKeywords: ["Akron postcard advertising", "local business postcards Akron", "Akron direct mail"],
    searchIntent: "Local business wants affordable city-level postcard advertising.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Roofers, HVAC, lawn care, dentists, auto shops, and service businesses in Akron.",
    contentAngle: "Category-exclusive shared postcard visibility for Akron homeowners.",
    offerAngle: "Reserve a city/category spot with Founding Member pricing where available.",
    ctaRecommendation: "Check Akron Availability",
    expectedRevenueValue: "Monthly recurring shared postcard revenue.",
    whyItMatters: "Akron is a core Northeast Ohio market with strong local service demand and direct mail fit.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["Akron business spotlight", "category exclusivity post", "postcard route explainer"],
    status: "ready_to_draft",
  },
  {
    rank: 2,
    title: "Roofing Postcards in Canton, Ohio",
    slug: "/ohio/canton/roofing-postcards",
    pageType: "local",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "roofing postcards Canton Ohio",
    supportingKeywords: ["Canton roofer advertising", "roofing direct mail Canton", "roofer postcards"],
    searchIntent: "Roofer wants lead generation in a specific local market.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Roofing companies and exterior contractors around Canton and Stark County.",
    contentAngle: "Get in front of homeowners before roof replacement season.",
    offerAngle: "Own the roofing category in Canton when available.",
    ctaRecommendation: "See If Roofing Is Open",
    expectedRevenueValue: "High-value category reservation and potential targeted upsell.",
    whyItMatters: "Roofing has high customer value and strong postcard economics.",
    internalLinks: [
      { label: "Roofing Postcards", href: "/roofing-postcard-marketing" },
      { label: "Check Availability", href: "/get-started" },
    ],
    socialRepurposing: ["Canton roof season reminder", "before storm season post", "roofer postcard concept"],
    status: "ready_to_draft",
  },
  {
    rank: 3,
    title: "Lawn Care Postcards in Massillon, Ohio",
    slug: "/ohio/massillon/lawncare-postcards",
    pageType: "local",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "lawn care postcards Massillon Ohio",
    supportingKeywords: ["Massillon lawn care advertising", "landscaping postcards Massillon", "lawn postcards"],
    searchIntent: "Seasonal home service business wants local leads.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Lawn care, landscaping, weed control, and outdoor service businesses.",
    contentAngle: "Monthly homeowner visibility before seasonal buying windows.",
    offerAngle: "Reserve lawn care or landscaping exclusivity in Massillon.",
    ctaRecommendation: "Check Lawn Care Availability",
    expectedRevenueValue: "Recurring category reservation plus seasonal campaign upsell.",
    whyItMatters: "Seasonal service categories convert well with repeated neighborhood mail.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["Spring lawn care post", "Massillon homeowner tip", "lawn postcard creative"],
    status: "ready_to_draft",
  },
  {
    rank: 4,
    title: "Political Direct Mail in Ohio",
    slug: "/political-mail/ohio",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political direct mail Ohio",
    supportingKeywords: ["Ohio campaign mail", "Ohio political postcards", "campaign mail vendor Ohio"],
    searchIntent: "Campaign wants a mail partner for statewide or local election execution.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Candidates, campaign managers, consultants, PACs, and party committees.",
    contentAngle: "Operational campaign mail planning with maps, phases, pricing, and approvals.",
    offerAngle: "Build a campaign mail plan and request a proposal.",
    ctaRecommendation: "Build My Campaign Mail Plan",
    expectedRevenueValue: "High-ticket political mail proposals.",
    whyItMatters: "Political mail is a premium category with urgent deadlines and large order sizes.",
    internalLinks: [
      { label: "Political Command", href: "/political" },
      { label: "Candidate Agent", href: "/political/candidate-agent" },
    ],
    socialRepurposing: ["campaign mail timing guide", "Ohio political mail checklist", "route planning explainer"],
    status: "ready_to_draft",
  },
  {
    rank: 5,
    title: "EDDM vs Targeted Mail",
    slug: "/eddm-vs-targeted-mail",
    pageType: "comparison",
    serviceOffering: "Targeted Campaigns",
    primaryKeyword: "EDDM vs targeted mail",
    supportingKeywords: ["EDDM postcards", "targeted direct mail", "USPS route marketing"],
    searchIntent: "Buyer is comparing direct mail options before spending.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Local businesses and campaigns evaluating direct mail strategy.",
    contentAngle: "Plain-English comparison of route-based mail, targeted mail, cost, control, and use cases.",
    offerAngle: "Get a recommended route or targeted campaign plan.",
    ctaRecommendation: "Compare My Mail Options",
    expectedRevenueValue: "Targeted campaign leads and consultation requests.",
    whyItMatters: "Comparison pages capture buyers with near-term intent and help explain HomeReach's product mix.",
    internalLinks: [
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
      { label: "Political Routes", href: "/political/routes" },
    ],
    socialRepurposing: ["EDDM explainer carousel", "targeted mail FAQ", "route selection checklist"],
    status: "ready_to_draft",
  },
  {
    rank: 6,
    title: "Political Mail in Columbus, Ohio",
    slug: "/political-mail/columbus",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political mail Columbus Ohio",
    supportingKeywords: ["Columbus campaign postcards", "Franklin County political mail", "campaign direct mail Columbus"],
    searchIntent: "Central Ohio campaign needs geographic mail execution.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Local candidates, county campaigns, issue committees, and statewide campaigns.",
    contentAngle: "Franklin County and Columbus mail planning for routes, timing, and proposal readiness.",
    offerAngle: "Request a Columbus political mail map and cost plan.",
    ctaRecommendation: "Plan Columbus Mail",
    expectedRevenueValue: "Political proposals and route planning orders.",
    whyItMatters: "Columbus is a major Ohio political and growth market.",
    internalLinks: [
      { label: "Political Maps", href: "/political/maps" },
      { label: "Pricing", href: "/political/pricing" },
    ],
    socialRepurposing: ["Central Ohio mail timing", "Columbus route explainer", "campaign postcard options"],
    status: "needs_source",
  },
  {
    rank: 7,
    title: "Shared Postcards for Small Businesses",
    slug: "/shared-postcards-for-small-businesses",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "shared postcards for small businesses",
    supportingKeywords: ["small business postcard advertising", "shared mail postcards", "local postcard ads"],
    searchIntent: "Small business wants affordable direct mail without buying a full campaign.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Small local businesses that need simple, recurring household reach.",
    contentAngle: "Explain the shared 9x12 model, category exclusivity, and monthly visibility.",
    offerAngle: "Check city/category availability.",
    ctaRecommendation: "Find My Spot",
    expectedRevenueValue: "Core MRR acquisition path.",
    whyItMatters: "This is the primary product education page for the shared postcard model.",
    internalLinks: [
      { label: "Availability", href: "/get-started" },
      { label: "Dashboard", href: "/dashboard" },
    ],
    socialRepurposing: ["how shared postcards work", "category exclusivity story", "local reach explainer"],
    status: "ready_to_draft",
  },
  {
    rank: 8,
    title: "Targeted Postcards Around Existing Customers",
    slug: "/targeted-postcards-around-existing-customers",
    pageType: "service",
    serviceOffering: "Targeted Campaigns",
    primaryKeyword: "postcards around existing customers",
    supportingKeywords: ["neighbor postcard campaign", "targeted postcards", "customer address direct mail"],
    searchIntent: "Business wants to market near recent customers or jobs.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Home service businesses with completed jobs and customer addresses.",
    contentAngle: "Turn recent jobs into neighborhood awareness and repeatable route campaigns.",
    offerAngle: "Upload customer areas or request a route plan.",
    ctaRecommendation: "Build My Targeted Campaign",
    expectedRevenueValue: "Higher-ticket targeted campaign orders.",
    whyItMatters: "This page creates an upsell path beyond shared postcard inventory.",
    internalLinks: [
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["job-neighborhood mail idea", "contractor route campaign", "before/after postcard concept"],
    status: "ready_to_draft",
  },
  {
    rank: 9,
    title: "HVAC Postcards in Medina, Ohio",
    slug: "/ohio/medina/hvac-postcards",
    pageType: "local",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "HVAC postcards Medina Ohio",
    supportingKeywords: ["Medina HVAC advertising", "heating and cooling postcards", "HVAC direct mail"],
    searchIntent: "HVAC company wants recurring homeowner reach in Medina.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "HVAC contractors and home service companies.",
    contentAngle: "Recurring seasonal reminders for heating, cooling, tune-ups, and replacement offers.",
    offerAngle: "Reserve HVAC category if available.",
    ctaRecommendation: "Check HVAC Availability",
    expectedRevenueValue: "Recurring MRR and seasonal targeted campaigns.",
    whyItMatters: "HVAC is a strong direct mail category with high customer lifetime value.",
    internalLinks: [
      { label: "HVAC Postcards", href: "/hvac-postcard-marketing" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["seasonal HVAC reminder", "Medina homeowner post", "tune-up postcard concept"],
    status: "ready_to_draft",
  },
  {
    rank: 10,
    title: "USPS Route Marketing",
    slug: "/usps-route-marketing",
    pageType: "service",
    serviceOffering: "Targeted Campaigns",
    primaryKeyword: "USPS route marketing",
    supportingKeywords: ["carrier route postcards", "route based direct mail", "USPS EDDM routes"],
    searchIntent: "Buyer wants to understand route-based mailing and cost.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Businesses, campaigns, and organizations planning geographic mail.",
    contentAngle: "Explain route-based planning, households, mail pieces, pricing, and validation.",
    offerAngle: "Request a route map and quote.",
    ctaRecommendation: "Build My Route Plan",
    expectedRevenueValue: "Targeted campaign and political route planning leads.",
    whyItMatters: "Route education supports targeted campaigns and political mail.",
    internalLinks: [
      { label: "Political Routes", href: "/political/routes" },
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
    ],
    socialRepurposing: ["carrier route explainer", "route count checklist", "mail cost breakdown"],
    status: "needs_source",
  },
  {
    rank: 11,
    title: "Direct Mail Pricing for Local Businesses",
    slug: "/direct-mail-pricing",
    pageType: "calculator",
    serviceOffering: "Shared Postcards and Targeted Campaigns",
    primaryKeyword: "direct mail pricing for small business",
    supportingKeywords: ["postcard advertising cost", "direct mail cost", "postcard campaign pricing"],
    searchIntent: "Buyer wants price clarity before contacting a vendor.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Local businesses comparing marketing costs.",
    contentAngle: "Explain shared postcard pricing, targeted campaign pricing, print, postage, and minimums.",
    offerAngle: "Get a simple price estimate or check availability.",
    ctaRecommendation: "Estimate My Campaign",
    expectedRevenueValue: "Pricing-qualified leads with lower sales friction.",
    whyItMatters: "Pricing pages attract high-intent buyers and reduce repetitive sales questions.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
    ],
    socialRepurposing: ["postcard cost breakdown", "shared vs targeted pricing", "budget planning post"],
    status: "ready_to_draft",
  },
  {
    rank: 12,
    title: "Political Postcard Timeline",
    slug: "/political-postcard-timeline",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political postcard timeline",
    supportingKeywords: ["campaign mail timing", "GOTV mail schedule", "political mail drop dates"],
    searchIntent: "Campaign needs to know when to mail before an election.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Campaign managers, candidates, consultants, and treasurers.",
    contentAngle: "Phase-based mail timing from intro through GOTV with production and approval deadlines.",
    offerAngle: "Calculate a campaign mail timeline.",
    ctaRecommendation: "Calculate My Timeline",
    expectedRevenueValue: "Political mail planning calls and proposals.",
    whyItMatters: "Timing content captures urgent campaign demand.",
    internalLinks: [
      { label: "Political Calendar", href: "/political/calendar" },
      { label: "Candidate Agent", href: "/political/candidate-agent" },
    ],
    socialRepurposing: ["campaign mail deadline checklist", "GOTV timing post", "mail wave diagram"],
    status: "ready_to_draft",
  },
  {
    rank: 13,
    title: "Roofing Postcard Marketing",
    slug: "/roofing-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards and Targeted Campaigns",
    primaryKeyword: "roofing postcard marketing",
    supportingKeywords: ["roofer direct mail", "roof replacement postcards", "storm damage postcards"],
    searchIntent: "Roofing company wants postcard campaign ideas and pricing.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Roofing companies and exterior contractors.",
    contentAngle: "Show seasonal offers, neighborhood strategy, storm timing, and category exclusivity.",
    offerAngle: "Check roofing category availability or launch a targeted route campaign.",
    ctaRecommendation: "Start Roofing Mail Plan",
    expectedRevenueValue: "High-value industry-specific acquisition page.",
    whyItMatters: "Industry pages scale across cities and support sales scripts.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
    ],
    socialRepurposing: ["roof inspection postcard", "storm readiness post", "contractor lead generation tip"],
    status: "ready_to_draft",
  },
  {
    rank: 14,
    title: "Lawn Care Postcard Marketing",
    slug: "/lawn-care-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards and Targeted Campaigns",
    primaryKeyword: "lawn care postcard marketing",
    supportingKeywords: ["landscaping postcards", "lawn service direct mail", "weed control postcards"],
    searchIntent: "Lawn or landscaping company wants seasonal local leads.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Lawn care, landscaping, fertilization, and weed control businesses.",
    contentAngle: "Use seasonal mail waves to reach homeowners before spring and summer decisions.",
    offerAngle: "Reserve a category or run a spring targeted route plan.",
    ctaRecommendation: "Start Lawn Care Mail Plan",
    expectedRevenueValue: "Seasonal lead generation and MRR.",
    whyItMatters: "Seasonal businesses are a natural fit for repeat direct mail.",
    internalLinks: [
      { label: "Get Started", href: "/get-started" },
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
    ],
    socialRepurposing: ["spring postcard idea", "neighborhood lawn care offer", "seasonal campaign checklist"],
    status: "ready_to_draft",
  },
  {
    rank: 15,
    title: "HVAC Postcard Marketing",
    slug: "/hvac-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards and Targeted Campaigns",
    primaryKeyword: "HVAC postcard marketing",
    supportingKeywords: ["heating postcards", "cooling postcards", "HVAC direct mail campaign"],
    searchIntent: "HVAC contractor wants repeatable direct mail ideas.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Heating and cooling companies.",
    contentAngle: "Plan tune-up, replacement, emergency service, and seasonal reminder postcards.",
    offerAngle: "Check HVAC category availability or build a seasonal drop.",
    ctaRecommendation: "Start HVAC Mail Plan",
    expectedRevenueValue: "MRR plus seasonal targeted drops.",
    whyItMatters: "HVAC demand is seasonal and high value, which suits route-based mail.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["AC tune-up postcard", "winter heating reminder", "HVAC route campaign"],
    status: "ready_to_draft",
  },
  {
    rank: 16,
    title: "Political Direct Mail Pricing",
    slug: "/political-direct-mail-pricing",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political direct mail pricing",
    supportingKeywords: ["campaign mail cost", "political postcard cost", "cost per political mailer"],
    searchIntent: "Campaign wants campaign mail costs before requesting a quote.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Campaigns, treasurers, consultants, and committees.",
    contentAngle: "Break down print, postage, data/list costs, quantity, waves, and route validation.",
    offerAngle: "Generate a verified quote after geography and counts are loaded.",
    ctaRecommendation: "Get Political Mail Estimate",
    expectedRevenueValue: "Qualified political proposal requests.",
    whyItMatters: "Political buyers need cost predictability and fast scenario planning.",
    internalLinks: [
      { label: "Political Pricing", href: "/political/pricing" },
      { label: "Political Simulator", href: "/political/simulator" },
    ],
    socialRepurposing: ["campaign mail cost guide", "per-piece pricing explainer", "budget scenario post"],
    status: "needs_source",
  },
  {
    rank: 17,
    title: "Contractor Postcard Marketing",
    slug: "/contractor-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards and Targeted Campaigns",
    primaryKeyword: "contractor postcard marketing",
    supportingKeywords: ["contractor direct mail", "home service postcards", "contractor advertising ideas"],
    searchIntent: "Contractor wants more local leads from homeowners.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "General contractors, remodelers, painters, electricians, plumbers, and exterior trades.",
    contentAngle: "Neighborhood trust, project photos, repeat visibility, and route targeting.",
    offerAngle: "Reserve a category or launch a route plan around service areas.",
    ctaRecommendation: "Build My Contractor Mail Plan",
    expectedRevenueValue: "Industry-specific acquisition and upsell path.",
    whyItMatters: "Contractor categories can be multiplied across cities and services.",
    internalLinks: [
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
      { label: "Shared Postcards", href: "/shared-postcards" },
    ],
    socialRepurposing: ["contractor postcard ideas", "neighborhood project mail", "service area campaign"],
    status: "ready_to_draft",
  },
  {
    rank: 18,
    title: "City-Exclusive Postcard Advertising",
    slug: "/city-exclusive-postcard-advertising",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "city exclusive postcard advertising",
    supportingKeywords: ["exclusive category advertising", "one business per category", "shared postcard exclusivity"],
    searchIntent: "Business wants to understand category exclusivity.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Businesses worried about competitors on the same postcard.",
    contentAngle: "Explain one category per city and how exclusivity protects local visibility.",
    offerAngle: "Check whether your category is still open.",
    ctaRecommendation: "Check My Category",
    expectedRevenueValue: "MRR acquisition and urgency driver.",
    whyItMatters: "Exclusivity is a core differentiator and conversion lever.",
    internalLinks: [
      { label: "Get Started", href: "/get-started" },
      { label: "Shared Postcards", href: "/shared-postcards" },
    ],
    socialRepurposing: ["exclusive category explainer", "spots filling post", "local competitor-free visibility"],
    status: "ready_to_draft",
  },
  {
    rank: 19,
    title: "Dentist Postcard Marketing",
    slug: "/dentist-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "dentist postcard marketing",
    supportingKeywords: ["dental postcards", "dentist direct mail", "new patient postcards"],
    searchIntent: "Dental practice wants local new patient campaigns.",
    buyerIntent: "medium",
    revenuePotential: "medium",
    conversionLikelihood: "medium",
    targetAudience: "Dental practices and orthodontists.",
    contentAngle: "Local trust, new patient offers, household visibility, and repeat brand recognition.",
    offerAngle: "Reserve dentistry category or request a targeted neighborhood plan.",
    ctaRecommendation: "Check Dental Availability",
    expectedRevenueValue: "Category reservation with potential targeted campaign upsell.",
    whyItMatters: "Healthcare-adjacent local services fit recurring household mail.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["new patient postcard", "family dentist mail idea", "local trust post"],
    status: "ready_to_draft",
  },
  {
    rank: 20,
    title: "Restaurant Postcard Marketing",
    slug: "/restaurant-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "restaurant postcard marketing",
    supportingKeywords: ["restaurant direct mail", "coupon postcards restaurant", "local restaurant advertising"],
    searchIntent: "Restaurant wants affordable local offers and repeat visibility.",
    buyerIntent: "medium",
    revenuePotential: "medium",
    conversionLikelihood: "medium",
    targetAudience: "Restaurants, cafes, pizza shops, and quick service operators.",
    contentAngle: "Neighborhood offers, QR menus, repeat coupons, and monthly brand reminders.",
    offerAngle: "Reserve the restaurant category or run a route campaign.",
    ctaRecommendation: "Start Restaurant Mail Plan",
    expectedRevenueValue: "Shared postcard MRR with offer-based conversion.",
    whyItMatters: "Food offers create easy postcard CTAs and QR engagement.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Targeted Campaigns", href: "/targeted-campaigns" },
    ],
    socialRepurposing: ["coupon postcard idea", "QR menu mailer", "local offer post"],
    status: "ready_to_draft",
  },
  {
    rank: 21,
    title: "Auto Shop Postcard Marketing",
    slug: "/auto-shop-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "auto shop postcard marketing",
    supportingKeywords: ["auto repair direct mail", "oil change postcards", "mechanic postcards"],
    searchIntent: "Auto repair business wants local household visibility.",
    buyerIntent: "medium",
    revenuePotential: "medium",
    conversionLikelihood: "medium",
    targetAudience: "Auto repair shops, tire shops, detailers, and service centers.",
    contentAngle: "Maintenance reminders, trust, coupons, and neighborhood convenience.",
    offerAngle: "Reserve auto repair category if available.",
    ctaRecommendation: "Check Auto Category",
    expectedRevenueValue: "Shared postcard MRR and coupon-driven campaigns.",
    whyItMatters: "Auto service has repeat purchase behavior and simple offers.",
    internalLinks: [
      { label: "Get Started", href: "/get-started" },
      { label: "Shared Postcards", href: "/shared-postcards" },
    ],
    socialRepurposing: ["oil change postcard", "local auto service offer", "maintenance reminder post"],
    status: "ready_to_draft",
  },
  {
    rank: 22,
    title: "Political Mail in Cleveland, Ohio",
    slug: "/political-mail/cleveland",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political mail Cleveland Ohio",
    supportingKeywords: ["Cuyahoga County campaign mail", "Cleveland political postcards", "campaign direct mail Cleveland"],
    searchIntent: "Campaign needs political mail planning for Cleveland or Cuyahoga County.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Campaigns, committees, consultants, and local candidates.",
    contentAngle: "Operational mail planning for Cleveland-area campaign geography and timing.",
    offerAngle: "Request a Cleveland/Cuyahoga mail plan.",
    ctaRecommendation: "Plan Cleveland Mail",
    expectedRevenueValue: "Political proposal pipeline.",
    whyItMatters: "Cleveland/Cuyahoga is a major Ohio political market and turnout geography.",
    internalLinks: [
      { label: "Political Maps", href: "/political/maps" },
      { label: "Candidate Agent", href: "/political/candidate-agent" },
    ],
    socialRepurposing: ["Cleveland campaign mail guide", "Cuyahoga route planning", "political postcard example"],
    status: "needs_source",
  },
  {
    rank: 23,
    title: "Political Mail in Cincinnati, Ohio",
    slug: "/political-mail/cincinnati",
    pageType: "political",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "political mail Cincinnati Ohio",
    supportingKeywords: ["Hamilton County political mail", "Cincinnati campaign postcards", "campaign direct mail Cincinnati"],
    searchIntent: "Campaign needs Cincinnati/Hamilton County mail planning.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "medium",
    targetAudience: "Candidates, consultants, issue campaigns, and party organizations.",
    contentAngle: "Campaign mail planning for Hamilton County, city, suburban, and route geographies.",
    offerAngle: "Request a Cincinnati political mail map and quote.",
    ctaRecommendation: "Plan Cincinnati Mail",
    expectedRevenueValue: "Political mail proposal opportunities.",
    whyItMatters: "Southwest Ohio is strategically important and frequently requested.",
    internalLinks: [
      { label: "Political Maps", href: "/political/maps" },
      { label: "Political Pricing", href: "/political/pricing" },
    ],
    socialRepurposing: ["Hamilton County mail timing", "Cincinnati campaign route post", "political map explainer"],
    status: "needs_source",
  },
  {
    rank: 24,
    title: "Campaign Mail Cost Calculator",
    slug: "/campaign-mail-cost-calculator",
    pageType: "calculator",
    serviceOffering: "Political Campaigns",
    primaryKeyword: "campaign mail cost calculator",
    supportingKeywords: ["political mail estimate", "postcard campaign calculator", "mail quantity calculator"],
    searchIntent: "Campaign wants to model quantity, drops, and budget quickly.",
    buyerIntent: "high",
    revenuePotential: "high",
    conversionLikelihood: "high",
    targetAudience: "Campaigns and consultants with an active budget question.",
    contentAngle: "Estimate mail quantities, drops, cost ranges, and required route verification.",
    offerAngle: "Generate a verified HomeReach proposal after review.",
    ctaRecommendation: "Estimate My Mail Cost",
    expectedRevenueValue: "Quote requests and proposal generation.",
    whyItMatters: "Calculators capture high-intent buyers and route them into proposal workflows.",
    internalLinks: [
      { label: "Political Simulator", href: "/political/simulator" },
      { label: "Political Pricing", href: "/political/pricing" },
    ],
    socialRepurposing: ["campaign budget calculator", "cost per piece explainer", "mail wave calculator"],
    status: "needs_source",
  },
  {
    rank: 25,
    title: "Cleaning Company Postcard Marketing",
    slug: "/cleaning-company-postcard-marketing",
    pageType: "service",
    serviceOffering: "Shared Postcards",
    primaryKeyword: "cleaning company postcard marketing",
    supportingKeywords: ["cleaning service postcards", "house cleaning direct mail", "maid service postcards"],
    searchIntent: "Cleaning company wants local recurring customers.",
    buyerIntent: "medium",
    revenuePotential: "medium",
    conversionLikelihood: "medium",
    targetAudience: "Residential cleaners, commercial cleaners, and maid services.",
    contentAngle: "Neighborhood trust, recurring service offers, and QR estimate requests.",
    offerAngle: "Reserve cleaning category or launch a targeted route campaign.",
    ctaRecommendation: "Start Cleaning Mail Plan",
    expectedRevenueValue: "Category reservation and local service lead flow.",
    whyItMatters: "Cleaning is a repeat service category suited to neighborhood awareness.",
    internalLinks: [
      { label: "Shared Postcards", href: "/shared-postcards" },
      { label: "Get Started", href: "/get-started" },
    ],
    socialRepurposing: ["clean home postcard", "spring cleaning offer", "local cleaner social post"],
    status: "ready_to_draft",
  },
];

export const reviewQueueBlueprint: ReviewQueueBlueprintItem[] = [
  {
    id: "review-seo-local-akron",
    contentType: "SEO Page Brief",
    title: "Shared Postcards in Akron",
    channel: "Website",
    status: "Needs Review",
    createdBy: "SEO Research Agent",
    targetAudience: "Akron local service businesses",
    sourceSystem: "Growth Engine Blueprint",
    nextAction: "Approve brief, then create draft in SEO Engine.",
  },
  {
    id: "review-blog-eddm-targeted",
    contentType: "Blog Brief",
    title: "EDDM vs Targeted Mail",
    channel: "Blog",
    status: "Draft",
    createdBy: "Blog Content Agent",
    targetAudience: "Direct mail buyers comparing options",
    sourceSystem: "Growth Engine Blueprint",
    nextAction: "Add sources, review CTA, then approve for drafting.",
  },
  {
    id: "review-social-shared-postcards",
    contentType: "Social Post Set",
    title: "How Shared Postcards Work",
    channel: "Facebook, LinkedIn, GBP",
    status: "Needs Review",
    createdBy: "Social Media Agent",
    targetAudience: "Small business owners",
    sourceSystem: "RSS Repurposing Workflow",
    nextAction: "Review tone and approve scheduling only after Blotato accounts are configured.",
  },
  {
    id: "review-postcard-roofing",
    contentType: "Postcard Concept",
    title: "Roofing Category Exclusive Creative",
    channel: "Shared 9x12 Postcard",
    status: "Draft",
    createdBy: "Postcard Creative Agent",
    targetAudience: "Roofing contractors",
    sourceSystem: "Postcard Creative Engine",
    nextAction: "Send to Ad Designer for visual proof.",
  },
  {
    id: "review-political-pricing",
    contentType: "Political Content",
    title: "Political Direct Mail Pricing Guide",
    channel: "Political Dashboard and SEO",
    status: "Needs Review",
    createdBy: "Political Campaign Agent",
    targetAudience: "Campaign managers and consultants",
    sourceSystem: "Political Content Engine",
    nextAction: "Verify USPS and print cost language before publishing.",
  },
];

export const integrationRequirements: IntegrationRequirement[] = [
  {
    vendor: "Arvow",
    purpose: "SEO article generation and webhook delivery into review-only publishing.",
    mode: "needs_api_key",
    envVars: ["ARVOW_API_KEY", "SEO_WEBHOOK_SECRET", "SEO_PUBLISHING_MODE", "CMS_WEBHOOK_URL"],
    workflow: [
      "Create or choose an Arvow formula and webhook integration.",
      "Send keyword batches to Arvow only after a HomeReach brief is approved.",
      "Receive generated articles through a webhook endpoint as draft review items.",
      "Store content as draft/needs review, not published.",
      "After human approval, move content into the existing SEO Engine or CMS publishing lane.",
    ],
    sourceUrl: "https://arvow.com/developers-and-ai-agents",
    notes:
      "Arvow supports programmatic batch article generation and webhook delivery. Its docs warn webhooks are not retried, so HomeReach should queue payloads before processing.",
  },
  {
    vendor: "Blotato",
    purpose: "Social publishing and scheduling after human review.",
    mode: "needs_api_key",
    envVars: [
      "BLOTATO_API_KEY",
      "SOCIAL_PUBLISHING_MODE",
      "SOCIAL_REVIEW_REQUIRED",
      "DEFAULT_SOCIAL_TIMEZONE",
    ],
    workflow: [
      "Connect social accounts in Blotato.",
      "Fetch account IDs before scheduling.",
      "Create draft platform-specific posts in HomeReach.",
      "Approve post in Human Review Queue.",
      "Submit approved post to Blotato with scheduledTime or useNextFreeSlot.",
      "Poll status and store the result in performance reporting.",
    ],
    sourceUrl: "https://help.blotato.com/api/start",
    notes:
      "Blotato uses a blotato-api-key header, account discovery, and async post creation. Scheduling fields must be top-level, not nested inside the post payload.",
  },
  {
    vendor: "RSS / CMS",
    purpose: "Repurpose approved/published content into social, email, SMS-safe, postcard, and sales follow-up drafts.",
    mode: "prepared",
    envVars: ["RSS_REPURPOSING_ENABLED", "CMS_API_KEY", "CMS_WEBHOOK_URL"],
    workflow: [
      "Detect approved or published content.",
      "Generate channel-specific repurposing drafts.",
      "Place all outputs in Human Review Queue.",
      "Only schedule or publish after explicit approval.",
    ],
    sourceUrl: "internal",
    notes:
      "The MVP exports structured plans and keeps publishing manual until a CMS/RSS source is selected.",
  },
];

export const agentDefinitions: AgentDefinition[] = [
  {
    name: "SEO Research Agent",
    job: "Find high-intent SEO opportunities for HomeReach services and local markets.",
    inputs: ["service catalog", "city/category inventory", "sales notes", "competitor notes"],
    outputs: ["SEO opportunities", "top revenue page plans", "metadata", "CTA recommendations"],
    guardrails: ["no unsupported claims", "no keyword stuffing", "human review before publish"],
  },
  {
    name: "Local Landing Page Agent",
    job: "Turn city, county, ZIP, and category opportunities into conversion-focused landing page briefs.",
    inputs: ["inventory", "city data", "service category", "CTA map"],
    outputs: ["landing page briefs", "FAQ", "schema notes", "internal links"],
    guardrails: ["respect availability", "route to existing intake", "no invented pricing"],
  },
  {
    name: "Blog Content Agent",
    job: "Create useful article briefs for direct mail, postcard marketing, EDDM, political mail, and local growth.",
    inputs: ["SEO opportunities", "content intelligence", "product knowledge"],
    outputs: ["blog outlines", "CTA blocks", "image prompts", "social ideas"],
    guardrails: ["human review", "source placeholders", "no fake testimonials"],
  },
  {
    name: "Social Media Agent",
    job: "Repurpose approved content into platform-specific posts and scheduling drafts.",
    inputs: ["approved pages", "approved articles", "postcard concepts", "campaign assets"],
    outputs: ["Facebook posts", "LinkedIn posts", "Instagram captions", "X posts", "GBP posts"],
    guardrails: ["review required", "no auto-publish", "brand tone enforced"],
  },
  {
    name: "Image Creative Agent",
    job: "Generate reusable image prompts and design standards for HomeReach visuals.",
    inputs: ["brand system", "campaign context", "product type"],
    outputs: ["image prompts", "creative standards", "visual QA notes"],
    guardrails: ["no random styles", "no fake logos", "campaign-safe visuals"],
  },
  {
    name: "Postcard Creative Agent",
    job: "Draft real postcard concepts for shared cards, targeted campaigns, and political mail waves.",
    inputs: ["campaign brief", "audience", "geography", "offer", "brand rules"],
    outputs: ["front/back descriptions", "headline", "CTA", "QR placement", "compliance notes"],
    guardrails: ["draft only", "approval before production", "political disclaimer reminder"],
  },
  {
    name: "Political Campaign Agent",
    job: "Prepare lawful aggregate campaign content, geography summaries, mail wave briefs, and proposal language.",
    inputs: ["candidate record", "office", "campaign timeline", "aggregate geography", "route counts"],
    outputs: ["mail plan content", "proposal language", "postcard concepts", "social drafts"],
    guardrails: ["no ideology scoring", "no individual inference", "human approval"],
  },
  {
    name: "CTA Audit Agent",
    job: "Identify unclear or broken revenue CTAs and route them into a fix list.",
    inputs: ["route inventory", "page inventory", "button audit", "manual QA"],
    outputs: ["CTA audit table", "priority fixes", "revenue path test notes"],
    guardrails: ["no duplicate records", "auth respected", "no payment bypass"],
  },
  {
    name: "Revenue Integrity Agent",
    job: "Keep publishing, checkout, review, campaign, admin, and sales handoffs safe.",
    inputs: ["review queue", "Stripe events", "campaign records", "sales tasks"],
    outputs: ["readiness checklist", "blocked actions", "weekly risk notes"],
    guardrails: ["no unapproved publishing", "no checkout without quote validation", "admin-only margin protected"],
  },
  {
    name: "Weekly Growth Report Agent",
    job: "Summarize growth work, review backlog, leads, revenue, broken CTAs, and next revenue opportunities.",
    inputs: ["SEO plan", "reviews", "sales data", "campaign metrics", "Stripe/orders"],
    outputs: ["weekly report", "copyable summary", "top five opportunities"],
    guardrails: ["label sample data", "source metrics", "no fake live performance"],
  },
];

export const ctaAuditBlueprint: CtaAuditItem[] = [
  {
    location: "Homepage",
    label: "Check Availability",
    expectedBehavior: "Start the protected get-started intake and city/category availability flow.",
    currentConnection: "/get-started",
    status: "needs_manual_qa",
    priority: "high",
    revenueImpact: "high",
  },
  {
    location: "Local SEO pages",
    label: "Check City Availability",
    expectedBehavior: "Route buyer to get-started with city/category context preserved when available.",
    currentConnection: "/get-started",
    status: "needs_manual_qa",
    priority: "high",
    revenueImpact: "high",
  },
  {
    location: "Political dashboard",
    label: "Build My Campaign Mail Plan",
    expectedBehavior: "Open the political plan flow or candidate agent, not shared postcard intake.",
    currentConnection: "/political/plan",
    status: "needs_manual_qa",
    priority: "high",
    revenueImpact: "high",
  },
  {
    location: "Admin Growth Engine",
    label: "Export Top 25 CSV",
    expectedBehavior: "Download a CSV planning file for SEO/social workflow review.",
    currentConnection: "/api/admin/growth-engine/top-pages/export",
    status: "connected",
    priority: "medium",
    revenueImpact: "medium",
  },
  {
    location: "Human Review Queue",
    label: "Publish After Approval",
    expectedBehavior: "Remain disabled until integration keys, source, and human approval exist.",
    currentConnection: "review-only blueprint",
    status: "needs_backend_connection",
    priority: "medium",
    revenueImpact: "medium",
  },
  {
    location: "Postcard Creative Engine",
    label: "Send to Ad Designer",
    expectedBehavior: "Move an approved creative brief to existing ad designer workflow.",
    currentConnection: "/admin/ad-designer",
    status: "needs_manual_qa",
    priority: "medium",
    revenueImpact: "high",
  },
];

export const revenuePathTest: RevenuePathStep[] = [
  {
    step: "Visitor lands on SEO, local, political, or service page",
    system: "Website and SEO Engine",
    expectedSignal: "Page loads with clear CTA, metadata, and source-labeled content.",
    guardrail: "No demo claims presented as live proof.",
  },
  {
    step: "Visitor clicks CTA",
    system: "CTA/Button Audit and intake routing",
    expectedSignal: "CTA routes to existing intake, political plan, or lead capture.",
    guardrail: "No dead links and no payment bypass.",
  },
  {
    step: "Customer submits intake",
    system: "Existing get-started intake and Supabase records",
    expectedSignal: "Lead/campaign/intake record is created once.",
    guardrail: "Availability and exclusivity rules remain authoritative.",
  },
  {
    step: "Offer, proposal, or postcard is reviewed",
    system: "Admin, sales, political, and creative review",
    expectedSignal: "Review item or campaign status is visible to staff.",
    guardrail: "Human approval before client-facing proposal, social post, or production.",
  },
  {
    step: "Customer pays",
    system: "Stripe checkout and webhooks",
    expectedSignal: "Payment, order, campaign, and dashboard visibility update.",
    guardrail: "No checkout until quote and required details are complete.",
  },
  {
    step: "Follow-up and reporting update",
    system: "Admin dashboard, sales dashboard, customer dashboard, reports",
    expectedSignal: "Tasks, notifications, and reporting reflect the transaction.",
    guardrail: "Admin-only margin stays private.",
  },
];

export const creativeStandards = [
  {
    name: "General HomeReach",
    rules: ["premium", "clean", "modern", "local", "trustworthy", "simple", "action-oriented"],
  },
  {
    name: "Political",
    rules: ["patriotic", "red/white/blue accents", "campaign-command feel", "serious", "credible"],
  },
  {
    name: "Small Business",
    rules: ["warm", "local", "practical", "results-focused", "simple CTA"],
  },
];

export const weeklyGrowthReportTemplate = [
  "New SEO opportunities found",
  "New local pages drafted",
  "New blog briefs drafted",
  "New social drafts created",
  "New postcard concepts created",
  "New political campaign assets created",
  "Items waiting for review",
  "Items approved or published",
  "Leads and revenue generated",
  "Broken CTAs found",
  "Recommended next actions",
  "Top 5 revenue opportunities",
];

export function getTopFiveRevenueOpportunities() {
  return topRevenuePages.slice(0, 5);
}
