import {
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { businessMemoryProfiles } from "./businessMemory.js";
import { profiles } from "./users.js";

export const growthIntelligenceAdminEntries = pgTable(
  "growth_intelligence_admin_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    entryType: text("entry_type").notNull(),
    location: text("location"),
    clientFit: text("client_fit"),
    notes: text("notes"),
    estimatedOpportunityCents: integer("estimated_opportunity_cents").notNull().default(0),
    priority: integer("priority").notNull().default(50),
    status: text("status").notNull().default("active"),
    industryFit: text("industry_fit").array().notNull().default(sql`'{}'::text[]`),
    geographyFit: text("geography_fit").array().notNull().default(sql`'{}'::text[]`),
    clientFitTags: text("client_fit_tags").array().notNull().default(sql`'{}'::text[]`),
    campaignTypeFit: text("campaign_type_fit").array().notNull().default(sql`'{}'::text[]`),
    budgetFit: text("budget_fit"),
    urgency: text("urgency").notNull().default("medium"),
    createdBy: text("created_by"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    statusIdx: index("growth_intelligence_admin_entries_status_idx").on(table.status, table.entryType, table.priority, table.updatedAt),
  }),
);

export const growthIntelligenceSources = pgTable(
  "growth_intelligence_sources",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceType: text("source_type").notNull(),
    sourceTable: text("source_table"),
    sourceId: text("source_id"),
    label: text("label").notNull(),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    notes: text("notes"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    clientIdx: index("growth_intelligence_sources_client_idx").on(table.clientId, table.sourceType, table.updatedAt),
    sourceUnique: uniqueIndex("growth_intelligence_sources_source_key").on(
      sql`coalesce(${table.clientId}::text, '')`,
      sql`lower(coalesce(${table.clientEmail}, ''))`,
      sql`coalesce(${table.sourceTable}, '')`,
      sql`coalesce(${table.sourceId}, '')`,
      table.sourceType,
    ),
  }),
);

export const growthIntelligenceOpportunities = pgTable(
  "growth_intelligence_opportunities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    adminEntryId: uuid("admin_entry_id").references(() => growthIntelligenceAdminEntries.id, { onDelete: "set null" }),
    opportunityType: text("opportunity_type").notNull(),
    category: text("category").notNull(),
    title: text("title").notNull(),
    whyItMatters: text("why_it_matters").notNull(),
    recommendedAction: text("recommended_action").notNull(),
    estimatedRevenuePotentialCents: integer("estimated_revenue_potential_cents").notNull().default(0),
    confidenceScore: integer("confidence_score").notNull().default(50),
    priorityScore: integer("priority_score").notNull().default(50),
    growthScore: integer("growth_score").notNull().default(50),
    source: text("source").notNull().default("growth_intelligence_engine"),
    sourceTable: text("source_table"),
    sourceId: text("source_id"),
    status: text("status").notNull().default("new_opportunity"),
    priorityLabel: text("priority_label").notNull().default("medium"),
    clientFitSummary: text("client_fit_summary"),
    recommendedCampaignType: text("recommended_campaign_type").notNull().default("general_growth_task"),
    owner: text("owner"),
    nextAction: text("next_action"),
    notes: text("notes"),
    dueAt: timestamp("due_at", { withTimezone: true }),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    campaignCreatedAt: timestamp("campaign_created_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    clientIdx: index("growth_intelligence_opportunities_client_idx").on(table.clientId, table.status, table.priorityScore, table.updatedAt),
    emailIdx: index("growth_intelligence_opportunities_email_idx").on(sql`lower(${table.clientEmail})`, table.status, table.priorityScore, table.updatedAt),
    queueIdx: index("growth_intelligence_opportunities_queue_idx").on(table.status, table.priorityLabel, table.priorityScore, table.updatedAt),
    categoryIdx: index("growth_intelligence_opportunities_category_idx").on(table.category, table.opportunityType, table.status, table.updatedAt),
    profileIdx: index("growth_intelligence_opportunities_profile_idx").on(table.businessMemoryProfileId, table.status, table.updatedAt),
    sourceUnique: uniqueIndex("growth_intelligence_opportunities_source_key").on(
      sql`coalesce(${table.clientId}::text, '')`,
      sql`lower(coalesce(${table.clientEmail}, ''))`,
      sql`coalesce(${table.sourceTable}, '')`,
      sql`coalesce(${table.sourceId}, '')`,
      table.opportunityType,
    ),
  }),
);

export const growthIntelligenceScores = pgTable(
  "growth_intelligence_scores",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    score: integer("score").notNull().default(0),
    color: text("color").notNull().default("yellow"),
    revenuePotentialScore: integer("revenue_potential_score").notNull().default(0),
    clientFitScore: integer("client_fit_score").notNull().default(0),
    timingScore: integer("timing_score").notNull().default(0),
    geographyFitScore: integer("geography_fit_score").notNull().default(0),
    priorAcceptanceScore: integer("prior_acceptance_score").notNull().default(0),
    campaignReadinessScore: integer("campaign_readiness_score").notNull().default(0),
    urgencyScore: integer("urgency_score").notNull().default(0),
    priorityLabel: text("priority_label").notNull().default("medium"),
    currentStatus: text("current_status").notNull().default("needs_data"),
    recommendedAction: text("recommended_action").notNull().default("Review the top growth opportunity."),
    topOpportunityId: uuid("top_opportunity_id").references(() => growthIntelligenceOpportunities.id, { onDelete: "set null" }),
    calculatedAt: timestamp("calculated_at", { withTimezone: true }).notNull().defaultNow(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    clientUnique: uniqueIndex("growth_intelligence_scores_client_key").on(
      sql`coalesce(${table.clientId}::text, '')`,
      sql`lower(coalesce(${table.clientEmail}, ''))`,
    ),
  }),
);

export const growthIntelligenceReports = pgTable(
  "growth_intelligence_reports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    reportingPeriodStart: date("reporting_period_start").notNull(),
    reportingPeriodEnd: date("reporting_period_end").notNull(),
    opportunitiesFound: integer("opportunities_found").notNull().default(0),
    opportunitiesApproved: integer("opportunities_approved").notNull().default(0),
    opportunitiesConverted: integer("opportunities_converted").notNull().default(0),
    estimatedRevenuePotentialCents: integer("estimated_revenue_potential_cents").notNull().default(0),
    actualCampaignsCreated: integer("actual_campaigns_created").notNull().default(0),
    dismissedOpportunities: integer("dismissed_opportunities").notNull().default(0),
    topCategories: jsonb("top_categories").$type<Record<string, unknown>[]>().notNull().default([]),
    topClients: jsonb("top_clients").$type<Record<string, unknown>[]>().notNull().default([]),
    recommendedNextActions: text("recommended_next_actions"),
    createdBy: text("created_by").notNull().default("growth_intelligence_engine"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    clientIdx: index("growth_intelligence_reports_client_idx").on(table.clientId, table.reportingPeriodEnd),
    periodUnique: uniqueIndex("growth_intelligence_reports_period_key").on(
      sql`coalesce(${table.clientId}::text, '')`,
      sql`lower(coalesce(${table.clientEmail}, ''))`,
      table.reportingPeriodStart,
      table.reportingPeriodEnd,
    ),
  }),
);

export const growthIntelligenceClientMatches = pgTable(
  "growth_intelligence_client_matches",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    adminEntryId: uuid("admin_entry_id").references(() => growthIntelligenceAdminEntries.id, { onDelete: "cascade" }),
    opportunityId: uuid("opportunity_id").references(() => growthIntelligenceOpportunities.id, { onDelete: "set null" }),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    matchReason: text("match_reason").notNull(),
    industryFitScore: integer("industry_fit_score").notNull().default(0),
    geographyFitScore: integer("geography_fit_score").notNull().default(0),
    campaignTypeFitScore: integer("campaign_type_fit_score").notNull().default(0),
    budgetFitScore: integer("budget_fit_score").notNull().default(0),
    urgencyScore: integer("urgency_score").notNull().default(0),
    status: text("status").notNull().default("matched"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    entryIdx: index("growth_intelligence_client_matches_entry_idx").on(table.adminEntryId, table.status, table.updatedAt),
    clientIdx: index("growth_intelligence_client_matches_client_idx").on(table.clientId, table.status, table.updatedAt),
    matchUnique: uniqueIndex("growth_intelligence_client_matches_key").on(
      table.adminEntryId,
      sql`coalesce(${table.clientId}::text, '')`,
      sql`lower(coalesce(${table.clientEmail}, ''))`,
    ),
  }),
);

export const growthIntelligenceActions = pgTable(
  "growth_intelligence_actions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    opportunityId: uuid("opportunity_id").references(() => growthIntelligenceOpportunities.id, { onDelete: "cascade" }),
    actionType: text("action_type").notNull(),
    label: text("label").notNull(),
    status: text("status").notNull().default("recorded"),
    actorUserId: uuid("actor_user_id").references(() => profiles.id, { onDelete: "set null" }),
    actorRole: text("actor_role"),
    targetCampaignType: text("target_campaign_type"),
    notes: text("notes"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    opportunityIdx: index("growth_intelligence_actions_opportunity_idx").on(table.opportunityId, table.createdAt),
  }),
);

export const growthIntelligenceDrafts = pgTable(
  "growth_intelligence_drafts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    opportunityId: uuid("opportunity_id").references(() => growthIntelligenceOpportunities.id, { onDelete: "cascade" }),
    clientId: uuid("client_id").references(() => profiles.id, { onDelete: "set null" }),
    clientEmail: text("client_email"),
    businessMemoryProfileId: uuid("business_memory_profile_id").references(() => businessMemoryProfiles.id, { onDelete: "set null" }),
    draftType: text("draft_type").notNull(),
    label: text("label").notNull(),
    content: text("content").notNull(),
    approvalStatus: text("approval_status").notNull().default("draft"),
    copyCount: integer("copy_count").notNull().default(0),
    lastCopiedAt: timestamp("last_copied_at", { withTimezone: true }),
    createdBy: text("created_by").notNull().default("growth_intelligence_draft_generator"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    opportunityIdx: index("growth_intelligence_drafts_opportunity_idx").on(table.opportunityId, table.draftType, table.createdAt),
    clientIdx: index("growth_intelligence_drafts_client_idx").on(table.clientId, table.draftType, table.createdAt),
    draftUnique: uniqueIndex("growth_intelligence_drafts_type_key").on(table.opportunityId, table.draftType),
  }),
);
