import type { WorkforceActivityLog, WorkforceTask } from "./types";

const now = new Date().toISOString();

export const seedWorkforceTasks: WorkforceTask[] = [
  {
    id: "seed-prospecting",
    taskId: "WF-PROSPECTING-001",
    workflowName: "Prospecting Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Prospecting Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/research",
    inputData: {
      chain: "Market focus -> prospect shortlist -> fit scoring -> contact gaps -> review handoff",
      dailyTargets: { targetedMail: 5, supplyfy: 5, political: 5 },
    },
    expectedOutput: "Review-ready prospect shortlist for targeted mail, Supplyfy, and political opportunities. No scraping bypass or outbound action.",
    dependencies: ["AI Assets business context", "CRM records", "approved prospecting SOP"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Prospecting produces review lists only.",
    errorNotes: null,
    relatedCampaign: "Daily revenue prospecting",
    relatedClient: null,
    relatedOpportunity: "Daily action center",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-daily-action-plan",
    taskId: "WF-DAILY-ACTION-001",
    workflowName: "Daily Action Plan Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Daily Action Plan Agent",
    priority: "critical",
    status: "assigned",
    inputPath: "ai-workforce/revenue-integrity",
    inputData: {
      targets: {
        targetedMailProspects: 5,
        supplyfyProspects: 5,
        politicalProspects: 5,
        followUps: 5,
        facebookPosts: 1,
        groupPosts: 1,
      },
    },
    expectedOutput: "One-page daily action plan with prospect counts, drafts needed, follow-ups, revenue estimate, and approval gates.",
    dependencies: ["Revenue Operations", "Daily Outreach", "AI Assets SOPs"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Daily plan is a command brief, not an automated send plan.",
    errorNotes: null,
    relatedCampaign: "Daily revenue actions",
    relatedClient: null,
    relatedOpportunity: "Owner action list",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-shared",
    taskId: "WF-SHARED-POSTCARD-001",
    workflowName: "Shared Postcard Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Shared Postcard Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/outreach",
    inputData: { chain: "City/category research -> offer angle -> Facebook post -> DM follow-up -> intake link -> close sequence -> revenue report" },
    expectedOutput: "Emotionally intelligent local post, DM follow-up, intake CTA, and revenue report outline that frames shared postcards as affordable premium visibility.",
    dependencies: ["AI Assets business context", "Facebook Group Post - Local Visibility"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Starter manifest item.",
    errorNotes: null,
    relatedCampaign: "Shared postcard campaigns",
    relatedClient: null,
    relatedOpportunity: null,
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-follow-up",
    taskId: "WF-FOLLOW-UP-001",
    workflowName: "Follow-Up Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Follow-Up Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/outreach",
    inputData: { chain: "Stale lead review -> best channel -> draft bump -> owner approval -> CRM update" },
    expectedOutput: "Follow-up queue with email, SMS, and DM drafts that require human approval before sending.",
    dependencies: ["Revenue Operations", "Communication ledger", "Approved outreach SOPs"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "No follow-up is sent automatically.",
    errorNotes: null,
    relatedCampaign: "Revenue recovery",
    relatedClient: null,
    relatedOpportunity: "Follow-up due",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-political",
    taskId: "WF-POLITICAL-001",
    workflowName: "Political Campaign Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Political Campaign Agent",
    priority: "critical",
    status: "awaiting_approval",
    inputPath: "ai-workforce/political",
    inputData: { chain: "Candidate/race research -> geographic mail plan -> campaign options -> creative brief -> proposal -> approval -> follow-up" },
    expectedOutput: "Neutral political plan, confidence-building proposal narrative, postcard direction, and compliance notes.",
    dependencies: ["Political Campaign Planning Brief", "Candidate Research Summary"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Political outputs are approval-gated.",
    errorNotes: null,
    relatedCampaign: "Political mail campaigns",
    relatedClient: null,
    relatedOpportunity: null,
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-supplyfy-mini-app",
    taskId: "WF-SUPPLYFY-MINIAPP-001",
    workflowName: "Procurement/Supplyfy Mini App",
    requestor: "HomeReach Admin",
    assignedAgent: "Procurement/Supplyfy Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/procurement",
    inputData: {
      miniApp: "approve-reorder",
      requiredControls: ["supplier comparison", "savings assumptions", "owner approval", "checkout handoff only"],
    },
    expectedOutput: "Approval-cart review with supplier comparison, estimated savings, reorder recommendation, and no spend commitment.",
    dependencies: ["Procurement Agent", "Supplyfy savings SOP", "Owner approval"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Approval cart is review-only.",
    errorNotes: null,
    relatedCampaign: "Supplyfy",
    relatedClient: null,
    relatedOpportunity: "Procurement savings",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-qa",
    taskId: "WF-QA-001",
    workflowName: "QA Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "QA / System Health Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/qa",
    inputData: { chain: "Route audit -> form test -> CTA test -> payment test -> automation test -> mobile test -> issue report" },
    expectedOutput: "Issue report with severity and reproduction steps.",
    dependencies: ["Dashboard QA", "System Health Check"],
    dueDate: null,
    approvalRequired: false,
    completionNotes: "QA findings do not execute changes automatically.",
    errorNotes: null,
    relatedCampaign: "Platform-wide",
    relatedClient: null,
    relatedOpportunity: null,
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-seo",
    taskId: "WF-SEO-001",
    workflowName: "SEO Authority Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Content / Topic Cluster Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/seo-content",
    inputData: { chain: "Market/intent research -> opportunity brief -> page or authority asset draft -> metadata/schema plan -> internal link plan -> quality review -> approval handoff" },
    expectedOutput: "Source-backed SEO opportunity brief with page type, target market, approved offer fit, internal links, CTA, quality gates, and human approval status.",
    dependencies: ["SEO Opportunity Brief", "SEO Engine Registry", "SEO Quality Gates"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "SEO publishing remains approval-gated.",
    errorNotes: null,
    relatedCampaign: "Local SEO authority engine",
    relatedClient: null,
    relatedOpportunity: null,
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-seo-technical",
    taskId: "WF-SEO-TECH-001",
    workflowName: "SEO Authority Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Technical SEO Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/seo-technical",
    inputData: {
      chain: "Technical audit -> sitemap/robots check -> metadata/schema review -> internal link gaps -> implementation-ready fix list",
      commandCenter: "/admin/marketing/seo-command-center",
    },
    expectedOutput: "Prioritized HomeReach technical SEO audit with affected routes, evidence, risk, owner approval gates, and next implementation actions.",
    dependencies: ["SEO Command Center", "Sitemap", "Robots", "SEO Quality Guardrails"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "SEO changes remain review-first before public implementation.",
    errorNotes: null,
    relatedCampaign: "HomeReach organic growth",
    relatedClient: null,
    relatedOpportunity: "Technical SEO readiness",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-seo-local",
    taskId: "WF-SEO-LOCAL-001",
    workflowName: "SEO Authority Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Local SEO Authority Agent",
    priority: "high",
    status: "assigned",
    inputPath: "ai-workforce/seo-local",
    inputData: {
      chain: "City/county opportunity -> proof requirements -> local authority brief -> internal links -> review queue",
      commandCenter: "/admin/marketing/seo-command-center",
    },
    expectedOutput: "Review-ready Ohio local authority brief that improves HomeReach search visibility without thin duplicate local pages.",
    dependencies: ["Ohio authority routes", "Political mail authority routes", "Approved HomeReach business facts"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "Local claims must be source-backed and approved before publishing.",
    errorNotes: null,
    relatedCampaign: "HomeReach local SEO authority",
    relatedClient: null,
    relatedOpportunity: "Ohio city and county authority",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "seed-seo-conversion",
    taskId: "WF-SEO-CONVERSION-001",
    workflowName: "SEO Authority Chain",
    requestor: "HomeReach Admin",
    assignedAgent: "Conversion SEO Agent",
    priority: "high",
    status: "awaiting_approval",
    inputPath: "ai-workforce/seo-growth",
    inputData: {
      chain: "Organic page intent -> proof/CTA audit -> copy recommendations -> lead path QA -> approval",
      commandCenter: "/admin/marketing/seo-command-center",
    },
    expectedOutput: "Conversion SEO review for top organic/revenue pages with CTA clarity, proof gaps, mobile notes, and lead-path risk.",
    dependencies: ["SEO Command Center", "Growth Engine top revenue pages", "CTA Audit Agent"],
    dueDate: null,
    approvalRequired: true,
    completionNotes: "CTA or public copy changes require human approval.",
    errorNotes: null,
    relatedCampaign: "HomeReach inbound lead flywheel",
    relatedClient: null,
    relatedOpportunity: "Organic lead conversion",
    outputId: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedWorkforceLogs: WorkforceActivityLog[] = [
  {
    id: "seed-log",
    taskId: null,
    taskPublicId: "WF-BOOTSTRAP-001",
    agentName: "Orchestrator Agent",
    eventType: "system_bootstrap",
    status: "completed",
    summary: "AI Workforce Operating System initialized with AGENTS.md, skills, task manifest, approval gates, and AI Assets integration.",
    details: { source: "seed" },
    approvalStatus: "not_required",
    relatedOutputId: null,
    createdAt: now,
  },
];
