// ─────────────────────────────────────────────────────────────────────────────
// Mock Conversation Repository
// In-memory implementation of IConversationRepository.
// ─────────────────────────────────────────────────────────────────────────────

import type { AutomationMessage, AutomationMode, ConversationContext, IntentType } from "../../types";
import type {
  IConversationRepository,
  UpsertConversationInput,
  CreateMessageInput,
} from "../interfaces";
import { AutomationEngine } from "../../automation";
import { MOCK_CONVERSATIONS } from "../../../admin/mock-data";

// Seed from existing mock data, enriching with automation fields
function seedConversations(): Map<string, ConversationContext> {
  const map = new Map<string, ConversationContext>();
  MOCK_CONVERSATIONS.forEach((c, i) => {
    const ctx: ConversationContext = {
      leadId:         c.leadId,
      leadName:       c.leadName,
      businessName:   c.businessName,
      city:           c.city,
      category:       c.category,
      phone:          c.phone,
      email:          c.email,
      status:         c.status as ConversationContext["status"],
      automationMode: i === 0 ? "auto" : "manual",
      lastIntent:     i === 0 ? "ready_to_buy" : i === 1 ? "interested" : undefined,
      messages:       c.messages.map((m) => ({
        ...m,
        intent: m.direction === "inbound"
          ? AutomationEngine.detectIntent(m.body).type
          : undefined,
        isAutoGenerated: false,
      })),
    };
    map.set(c.id, ctx);
  });
  return map;
}

// Store: conversationId → ConversationContext
// Messages are embedded on the context for simplicity (normalize in Supabase)
const CONVERSATION_IDS = MOCK_CONVERSATIONS.map((c) => c.id);

export class MockConversationRepository implements IConversationRepository {
  private store: Map<string, ConversationContext> = seedConversations();
  // Map conversationId → full conversation context (id managed separately)
  private ids: string[] = [...CONVERSATION_IDS];

  async getAll(): Promise<ConversationContext[]> {
    return this.ids
      .map((id) => this.store.get(id))
      .filter((c): c is ConversationContext => c !== undefined)
      .sort((a, b) => {
        const aLast = a.messages.at(-1)?.sentAt ?? "";
        const bLast = b.messages.at(-1)?.sentAt ?? "";
        return bLast.localeCompare(aLast);
      });
  }

  async getById(conversationId: string): Promise<ConversationContext | null> {
    return this.store.get(conversationId) ?? null;
  }

  async getByLeadId(leadId: string): Promise<ConversationContext[]> {
    return [...this.store.values()].filter((c) => c.leadId === leadId);
  }

  async upsert(input: UpsertConversationInput): Promise<ConversationContext> {
    const id = input.id ?? `conv-${Date.now()}`;
    const existing = input.id ? (this.store.get(input.id) ?? null) : null;

    const ctx: ConversationContext = {
      leadId:         input.leadId,
      leadName:       input.leadName,
      businessName:   input.businessName,
      phone:          input.phone,
      email:          input.email,
      city:           input.city,
      category:       input.category,
      status:         input.status,
      automationMode: input.automationMode ?? existing?.automationMode ?? "manual",
      lastIntent:     existing?.lastIntent,
      messages:       existing?.messages ?? [],
    };

    this.store.set(id, ctx);
    if (!this.ids.includes(id)) this.ids.push(id);
    return ctx;
  }

  async addMessage(conversationId: string, input: CreateMessageInput): Promise<AutomationMessage> {
    const ctx = this.store.get(conversationId);
    if (!ctx) throw new Error(`Conversation not found: ${conversationId}`);

    const msg: AutomationMessage = {
      id:              `msg-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      direction:       input.direction,
      channel:         input.channel,
      body:            input.body,
      sentAt:          input.sentAt ?? new Date().toISOString(),
      read:            input.direction === "outbound",
      intent:          input.intent,
      isAutoGenerated: input.isAutoGenerated ?? false,
    };

    ctx.messages = [...ctx.messages, msg];
    this.store.set(conversationId, ctx);
    return msg;
  }

  async getMessages(conversationId: string): Promise<AutomationMessage[]> {
    return this.store.get(conversationId)?.messages ?? [];
  }

  async setAutomationMode(conversationId: string, mode: AutomationMode): Promise<void> {
    const ctx = this.store.get(conversationId);
    if (!ctx) return;
    this.store.set(conversationId, { ...ctx, automationMode: mode });
  }

  async setLastIntent(conversationId: string, intent: IntentType): Promise<void> {
    const ctx = this.store.get(conversationId);
    if (!ctx) return;
    this.store.set(conversationId, { ...ctx, lastIntent: intent });
  }

  async markRead(conversationId: string): Promise<void> {
    const ctx = this.store.get(conversationId);
    if (!ctx) return;
    const updated = {
      ...ctx,
      messages: ctx.messages.map((m) =>
        m.direction === "inbound" ? { ...m, read: true } : m
      ),
    };
    this.store.set(conversationId, updated);
  }

  async getUnreadCount(): Promise<number> {
    let count = 0;
    for (const ctx of this.store.values()) {
      count += ctx.messages.filter((m) => m.direction === "inbound" && !m.read).length;
    }
    return count;
  }
}
