// ─────────────────────────────────────────────────────────────────────────────
// HomeReach Engine — Shared Types
//
// All engine modules import from here.
// Designed to map 1:1 to Supabase table schemas when connected.
// ─────────────────────────────────────────────────────────────────────────────

// ── Spots ─────────────────────────────────────────────────────────────────────

export type SpotStatus = "available" | "reserved" | "in-progress" | "sold";

export interface Spot {
  id: string;
  cityId: string;
  cityName: string;
  categoryId: string;
  categoryName: string;
  status: SpotStatus;
  businessId: string | null;
  businessName: string | null;
  reservedUntil: string | null;  // ISO timestamp
  basePrice: number;
  isFullCard: boolean;
}

export interface CityAvailability {
  cityId: string;
  cityName: string;
  totalSpots: number;
  availableSpots: number;
  reservedSpots: number;
  soldSpots: number;
  isFullCardAvailable: boolean;
  fillPercent: number;
  urgencyLevel: "low" | "medium" | "high" | "critical";
  spots: Spot[];
}

export interface CategoryAvailability {
  categoryId: string;
  categoryName: string;
  cityId: string;
  status: SpotStatus;
  reservedUntil: string | null;
  isLocked: boolean;
}

// ── Pricing ───────────────────────────────────────────────────────────────────

export type DiscountType = "founding" | "military" | "promo" | "bundle" | "multispot";

export interface DiscountConfig {
  type: DiscountType;
  label: string;
  amount: number;       // absolute $ or percent
  isPercent: boolean;
  stackable: boolean;   // can combine with other discounts
  expiresAt?: string;   // ISO timestamp; undefined = never expires
}

export interface PricingContext {
  basePrice: number;
  spotCount: number;           // number of spots selected
  isFullCard: boolean;
  isFoundingMember: boolean;
  isMilitary: boolean;
  promoCode?: string;
  bundleIds?: string[];
}

export interface AppliedDiscount {
  type: DiscountType;
  label: string;
  savings: number;            // $ saved
}

export interface PriceResult {
  originalPrice: number;      // before any discounts
  finalPrice: number;         // after all discounts
  totalSavings: number;
  appliedDiscounts: AppliedDiscount[];
  perSpotPrice: number;       // finalPrice / spotCount
  billingLabel: string;       // e.g. "per month, locked in"
  isFoundingRate: boolean;
  displayOriginal: boolean;   // show strikethrough?
}

// ── Reservations ──────────────────────────────────────────────────────────────

export type ReservationStatus = "active" | "expired" | "converted" | "cancelled";

export interface Reservation {
  id: string;
  spotId: string;
  cityId: string;
  categoryId: string;
  businessId: string;
  businessName: string;
  leadId: string;
  status: ReservationStatus;
  createdAt: string;
  expiresAt: string;
  ttlHours: number;
  adminNote?: string;
}

export interface ReservationResult {
  success: boolean;
  reservation?: Reservation;
  error?: "spot_unavailable" | "already_reserved" | "full_card_active";
}

// ── Conversations & Automation ────────────────────────────────────────────────

export type MessageChannel = "sms" | "email";
export type MessageDirection = "inbound" | "outbound";

export type IntentType =
  | "interested"
  | "asking_questions"
  | "objection"
  | "ready_to_buy"
  | "not_interested"
  | "unknown";

export interface DetectedIntent {
  type: IntentType;
  confidence: number;       // 0–1
  keywords: string[];       // matched keywords
  suggestedResponse: string;
}

export interface AutomationMessage {
  id: string;
  direction: MessageDirection;
  channel: MessageChannel;
  body: string;
  sentAt: string;
  read: boolean;
  intent?: IntentType;
  isAutoGenerated?: boolean;
}

export type AutomationMode = "auto" | "manual";

export interface ConversationContext {
  leadId: string;
  leadName: string;
  businessName: string;
  city: string;
  category: string;
  phone: string;
  email: string;
  status: LeadStatus;
  automationMode: AutomationMode;
  lastIntent?: IntentType;
  messages: AutomationMessage[];
  reservationId?: string;
}

// ── Leads ─────────────────────────────────────────────────────────────────────

export type LeadStatus =
  | "lead"
  | "interested"
  | "sold"
  | "churned"
  | "closed_won"
  | "closed_lost";

export interface Lead {
  id: string;
  name: string;
  businessName: string;
  phone: string;
  email: string;
  cityId: string;
  city: string;
  categoryId: string;
  category: string;
  status: LeadStatus;
  source: "outreach" | "waitlist" | "referral" | "inbound";
  lastContact: string;
  notes: string;
  spotId: string | null;
  monthlyValue: number;
  automationMode: AutomationMode;
  reservationId?: string;
  intakeFormSent?: boolean;
  intakeFormCompletedAt?: string;
}

// ── ROI / Analytics ───────────────────────────────────────────────────────────

export interface CampaignMetrics {
  businessId: string;
  month: string;             // "2026-04"
  homesReached: number;
  qrScans: number;
  calls: number;
  formLeads: number;
  estimatedRevenue: number;  // tracked by business owner (optional)
}

// ── Roles & Access ────────────────────────────────────────────────────────────

export type UserRole = "admin" | "sales_agent";

export interface SalesAgent {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: UserRole;
  status: "active" | "inactive";
  assignedCityIds: string[];       // cities this agent manages
  assignedLeadIds: string[];       // leads assigned to this agent
  createdAt: string;

  // Performance (computed / mock)
  dealsClosedThisMonth: number;
  dealsClosedAllTime: number;
  pipelineValue: number;           // sum of monthly value of active leads
  commissionRate: number;          // % of deal value as commission (e.g. 0.10 = 10%)
  commissionEarnedThisMonth: number;
  commissionEarnedAllTime: number;
  followUpsDue: number;            // leads needing follow-up today
}

export interface AgentFollowUp {
  id: string;
  agentId: string;
  leadId: string;
  leadName: string;
  businessName: string;
  city: string;
  category: string;
  dueAt: string;           // ISO timestamp
  note: string;
  completed: boolean;
}

// ── Client Migration ──────────────────────────────────────────────────────────

export type ClientMigrationStatus = "legacy_active" | "legacy_pending" | "new_system";
export type SpotType = "front" | "back" | "anchor" | "full_card";

export interface ClientContract {
  startDate: string;         // ISO date "2026-01-01"
  endDate: string;           // ISO date "2027-01-01"
  remainingMonths: number;
  isNearingRenewal: boolean; // within 60 days of end
  renewalTriggered: boolean;
  renewalNote?: string;
}

export interface MigratedClient {
  id: string;
  businessName: string;
  contactName: string;
  phone: string;
  email: string;
  cityId: string;
  city: string;
  categoryId: string;
  category: string;
  spotId: string | null;
  spotType: SpotType;
  monthlyPrice: number;
  migrationStatus: ClientMigrationStatus;
  contract: ClientContract;
  notes: string;
  migratedAt: string;        // when added to system
  migratedBy: string;        // admin who added them

  // System integration flags
  appearsInDashboard: boolean;
  appearsInROI: boolean;
  billingPrevented: boolean; // true for legacy_active — no new charges
}

// ── Targeted Route Campaigns ──────────────────────────────────────────────────

/** USPS carrier route with household count + demographic signals */
export interface CarrierRoute {
  id: string;
  cityId: string;
  cityName: string;
  routeCode: string;             // e.g. "OH-MED-C001"
  name: string;                  // human-readable neighborhood/area name
  households: number;
  available: boolean;

  /** Demographic indicators — mock for now, real filters added later */
  demographics: {
    medianHomeValue: string;     // "$200k–$300k"
    medianIncome: string;        // "$65k–$85k"
    homeownerPct: number;        // 78
    primaryAgeGroup: string;     // "35–54"
  };

  /** Future-ready targeting fields — structure only, no logic yet */
  targetingFilters: {
    incomeRange?: string;        // "50k-75k" | "75k-100k" | "100k+"
    homeValueRange?: string;     // "150k-250k" | "250k-400k" | "400k+"
    zipCluster?: string;         // zip code grouping
  };
}

/** Pricing tier based on total household reach */
export interface RoutePricingTier {
  id: string;
  label: string;                 // "Starter" | "Growth" | "Scale" | "Enterprise"
  minHouseholds: number;
  maxHouseholds: number;         // Infinity for top tier
  pricePerThousand: number;      // $ per 1,000 households
  description: string;
}

export type TargetedCampaignStatus =
  | "draft"
  | "pending_review"
  | "active"
  | "completed"
  | "cancelled";

/** A full targeted route campaign record */
export interface TargetedCampaign {
  id: string;
  campaignType: "targeted";       // distinguish from shared postcard

  // Business / contact
  businessId: string | null;
  businessName: string;
  contactName: string;
  phone: string;
  email: string;

  // Geography
  cityId: string;
  city: string;
  selectedRouteIds: string[];     // which CarrierRoute.id entries are selected
  totalHouseholds: number;

  // Pricing
  pricePerThousand: number;
  totalPrice: number;
  pricingTierLabel: string;       // e.g. "Growth"

  // Future-ready targeting
  targetingFilters: {
    incomeRange?: string;
    homeValueRange?: string;
    zipCluster?: string;
  };

  // Status + lifecycle
  status: TargetedCampaignStatus;
  createdAt: string;
  startDate?: string;
  endDate?: string;
  notes?: string;

  // Dashboard integration flags
  appearsInAdminDashboard: boolean;
  appearsInClientDashboard: boolean;

  // Reach metrics (populated post-campaign)
  metrics?: {
    homesReached: number;
    responseRate?: number;        // %
    leadsGenerated?: number;
    estimatedROI?: number;        // $
  };
}
