-- ─────────────────────────────────────────────────────────────────────────────
-- HomeReach Migration 062 — Political Command Center: Contracts + E-Sign
--
-- Adds `political_contracts` to record electronically-signed services
-- agreements for political proposals. Captures the minimum UETA / E-SIGN
-- evidence set:
--   • intent + identity    → signer_name, signer_email
--   • timestamp            → signed_at
--   • integrity            → terms_text (verbatim snapshot at sign time)
--   • non-repudiation      → signer_ip (+ unique public_token)
--
-- Strictly additive:
--   • No existing columns dropped, renamed, or retyped.
--   • No existing RLS altered.
--   • Reuses the 059 updated_at helper function.
--
-- Compliance:
--   • terms_text is human-readable plain text (no HTML/SQL injection surface).
--   • Contract surface never collects voter data or persuasion inputs.
--   • The non-political clause in the terms text is the product promise
--     to the client; the clause itself is NOT a persuasion artifact —
--     it's documentation of what HomeReach will not do.
--
-- SAFE TO RE-RUN. All DDL guarded with IF NOT EXISTS / DO blocks.
-- ─────────────────────────────────────────────────────────────────────────────


-- ═════════════════════════════════════════════════════════════════════════════
-- 1. Enum
-- ═════════════════════════════════════════════════════════════════════════════

do $$ begin
  create type public.political_contract_status_enum as enum (
    'pending',
    'signed',
    'canceled',
    'expired'
  );
exception
  when duplicate_object then null;
end $$;


-- ═════════════════════════════════════════════════════════════════════════════
-- 2. political_contracts
-- ═════════════════════════════════════════════════════════════════════════════

create table if not exists public.political_contracts (
  id                  uuid primary key default gen_random_uuid(),

  -- Parentage — a contract is scoped to a specific proposal (and therefore
  -- a specific campaign + candidate). Order is nullable because a contract
  -- can exist before payment; the order is created on approval.
  proposal_id         uuid not null references public.political_proposals(id) on delete cascade,
  campaign_id         uuid not null references public.political_campaigns(id) on delete cascade,
  order_id            uuid references public.political_orders(id) on delete set null,

  -- Status lifecycle.
  status              public.political_contract_status_enum not null default 'pending',

  -- Public token — 32-byte hex generated by app code. One per contract.
  public_token        text,

  -- Verbatim plain-text snapshot of the signed agreement. Never rewritten
  -- after sign (integrity evidence). buildContractTerms() produces this.
  terms_text          text not null,

  -- Evidence captured at sign time. All nullable until signed.
  signer_name         text,
  signer_email        text,
  signer_ip           text,
  signed_at           timestamptz,

  -- Version — supports re-issuing a contract after the proposal is edited.
  -- Default 1; later phases that edit a contract create a new row with
  -- version = previous + 1 rather than mutating the signed copy.
  version             integer not null default 1,

  -- Optional expiration. If null, the contract never auto-expires.
  expires_at          timestamptz,

  -- Presentation + view tracking.
  sent_at             timestamptz,
  viewed_at           timestamptz,

  -- Audit metadata
  created_by          uuid references public.profiles(id) on delete set null,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Enforce one signed contract per proposal (partial unique — a signed row
-- blocks insertion of a second signed row for the same proposal; pending
-- and canceled rows are allowed to co-exist for versioning / re-issue).
create unique index if not exists political_contracts_one_signed_per_proposal_idx
  on public.political_contracts (proposal_id)
  where status = 'signed';

create unique index if not exists political_contracts_public_token_idx
  on public.political_contracts (public_token)
  where public_token is not null;

create index if not exists political_contracts_proposal_idx  on public.political_contracts (proposal_id);
create index if not exists political_contracts_campaign_idx  on public.political_contracts (campaign_id);
create index if not exists political_contracts_order_idx     on public.political_contracts (order_id)
  where order_id is not null;
create index if not exists political_contracts_status_idx    on public.political_contracts (status);
create index if not exists political_contracts_signed_at_idx on public.political_contracts (signed_at desc)
  where signed_at is not null;


-- ═════════════════════════════════════════════════════════════════════════════
-- 3. Row Level Security
--    Mirrors 061: service_role full, admin full, sales_agent scoped read,
--    client = none. Public signing happens via service-role client.
-- ═════════════════════════════════════════════════════════════════════════════

alter table public.political_contracts enable row level security;

drop policy if exists "political_contracts_service" on public.political_contracts;
create policy "political_contracts_service"
  on public.political_contracts for all to service_role using (true) with check (true);

drop policy if exists "political_contracts_admin" on public.political_contracts;
create policy "political_contracts_admin"
  on public.political_contracts for all to authenticated
  using      (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
  with check (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

drop policy if exists "political_contracts_agent_read" on public.political_contracts;
create policy "political_contracts_agent_read"
  on public.political_contracts for select to authenticated
  using (exists (select 1 from public.profiles where id = auth.uid() and role in ('admin','sales_agent')));

-- Sales agents cannot directly insert/update/delete contracts from a user
-- session — all writes go through the service-role path (proposal approval
-- auto-creates; public sign page records evidence). Prevents a sales_agent
-- from fabricating a "signed" row.


-- ═════════════════════════════════════════════════════════════════════════════
-- 4. updated_at trigger (reuse 059 function)
-- ═════════════════════════════════════════════════════════════════════════════

drop trigger if exists trg_political_contracts_updated_at on public.political_contracts;
create trigger trg_political_contracts_updated_at
  before update on public.political_contracts
  for each row execute function public.tg_political_touch_updated_at();
