import type { AgentMiniApp, AgentMiniAppEvent } from "./types";

const now = new Date();

function iso(hoursFromNow: number) {
  return new Date(now.getTime() + hoursFromNow * 60 * 60 * 1000).toISOString();
}

export const seedMiniApps: AgentMiniApp[] = [
  {
    id: "seed-outreach-email",
    tenantId: null,
    miniAppType: "outreach_approval",
    title: "Approve email to Oak Ridge Roofing",
    description: "Review a one-to-one executive email draft before any outreach leaves HomeReach.",
    sourceAgent: "Outreach Agent",
    relatedModule: "outreach-command",
    relatedBusinessId: null,
    relatedContactId: null,
    relatedCampaignId: null,
    relatedClientId: null,
    status: "needs_review",
    priority: "urgent",
    confidenceScore: 86,
    riskLevel: "medium",
    approvalRequired: true,
    estimatedRevenue: 4200,
    estimatedSavings: 0,
    estimatedCost: 0,
    recommendedAction: "Approve the revised email, then queue for manual send review.",
    payloadJson: {
      channel: "email",
      recipient_name: "Megan Wallace",
      recipient_email: "megan@example.com",
      business_name: "Oak Ridge Roofing",
      campaign_name: "Spring storm route density",
      subject: "Storm-season route around Oak Ridge",
      message_body:
        "Megan, I mapped a compact storm-season route around Oak Ridge that could keep your crew visible without a broad ad spend. If it looks useful, I can send the route, mail cost, and geofence option for review.",
      previous_touch_summary: "Website inquiry requested pricing for targeted roofing mail after hail events.",
      call_to_action: "Review route and quote",
      compliance_warning: "Do not send until the recipient, claims, sender identity, and opt-out/permission context are reviewed.",
      approval_status: "needs_review",
      next_action: "Human review, edit if needed, then queue approved send task.",
      related_entity: "Oak Ridge Roofing",
      destination: "Communication ledger and future execution queue",
    },
    editedPayloadJson: null,
    decision: null,
    decisionReason: null,
    assignedUserId: null,
    dueAt: iso(2),
    createdBy: null,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    archivedAt: null,
  },
  {
    id: "seed-outreach-sms",
    tenantId: null,
    miniAppType: "outreach_approval",
    title: "Review SMS follow-up for Lakeside Lawn",
    description: "Approve or revise a short SMS follow-up before any message is sent.",
    sourceAgent: "Follow-Up Agent",
    relatedModule: "outreach-command",
    relatedBusinessId: null,
    relatedContactId: null,
    relatedCampaignId: null,
    relatedClientId: null,
    status: "needs_review",
    priority: "high",
    confidenceScore: 78,
    riskLevel: "high",
    approvalRequired: true,
    estimatedRevenue: 1800,
    estimatedSavings: 0,
    estimatedCost: 0,
    recommendedAction: "Edit for brevity, then schedule only if SMS permission is confirmed.",
    payloadJson: {
      channel: "sms",
      recipient_name: "Tom Avery",
      recipient_phone: "+15555550118",
      business_name: "Lakeside Lawn Care",
      message_body:
        "Tom, this is Josh with HomeReach. I have the Lakeside spring cleanup route ready if you want the quick cost and timing today. Reply STOP to opt out.",
      compliance_warning: "SMS requires confirmed permission and STOP/HELP handling before send.",
      approval_status: "needs_review",
      next_action: "Verify permission, approve, then schedule or queue manual send.",
      related_entity: "Lakeside Lawn Care",
      destination: "Communication ledger and future execution queue",
    },
    editedPayloadJson: null,
    decision: null,
    decisionReason: null,
    assignedUserId: null,
    dueAt: iso(4),
    createdBy: null,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    archivedAt: null,
  },
];

export const seedEvents: AgentMiniAppEvent[] = seedMiniApps.map((app) => ({
  id: `event-${app.id}`,
  miniAppId: app.id,
  eventType: "created",
  previousStatus: null,
  newStatus: app.status,
  actorUserId: null,
  actorType: "system",
  eventSummary: "Seed mini app available until Supabase persistence is configured.",
  eventPayloadJson: { source: "fallback_seed" },
  createdAt: app.createdAt,
}));
