// ─────────────────────────────────────────────────────────────────────────────
// Supabase Conversation Repository
//
// No dedicated conversations table exists in the schema yet.
// Reads inbound messages from outreach_replies for the admin inbox.
// Writes are in-memory (lost on restart) until a conversations table is added.
//
// This keeps the admin inbox functional without crashing while a real
// conversations table migration is pending.
// ─────────────────────────────────────────────────────────────────────────────

import type { AutomationMessage, AutomationMode, ConversationContext, IntentType } from "../../types";
import type { IConversationRepository, UpsertConversationInput, CreateMessageInput } from "../interfaces";
import { db, outreachReplies, outreachContacts, businesses } from "@homereach/db";
import { eq, desc } from "drizzle-orm";

// In-process store for conversations + outbound messages (ephemeral).
// Replaced when a real conversations table migration is run.
const _conversations = new Map<string, ConversationContext>();
const _messages       = new Map<string, AutomationMessage[]>();

export class SupabaseConversationRepository implements IConversationRepository {

  // ── Read ───────────────────────────────────────────────────────────────────

  async getAll(): Promise<ConversationContext[]> {
    // Pull real inbound replies from Supabase, group by contact
    try {
      const rows = await db
        .select({
          replyId:      outreachReplies.id,
          contactId:    outreachReplies.contactId,
          businessId:   outreachReplies.businessId,
          body:         outreachReplies.body,
          receivedAt:   outreachReplies.receivedAt,
          isRead:       outreachReplies.isRead,
          contactName:  outreachContacts.name,
          contactPhone: outreachContacts.phone,
          contactEmail: outreachContacts.email,
          bizName:      businesses.name,
        })
        .from(outreachReplies)
        .leftJoin(outreachContacts, eq(outreachReplies.contactId, outreachContacts.id))
        .leftJoin(businesses,       eq(outreachReplies.businessId, businesses.id))
        .orderBy(desc(outreachReplies.receivedAt))
        .limit(100);

      // Group replies by contactId → one ConversationContext per contact
      const byContact = new Map<string, typeof rows>();
      for (const row of rows) {
        const bucket = byContact.get(row.contactId) ?? [];
        bucket.push(row);
        byContact.set(row.contactId, bucket);
      }

      const contexts: ConversationContext[] = [];
      for (const [contactId, msgs] of byContact) {
        const first = msgs[0]!;
        const convId = `conv-${contactId}`;
        const messages: AutomationMessage[] = msgs.map((m) => ({
          id:              m.replyId,
          direction:       "inbound" as const,
          channel:         "sms" as const,
          body:            m.body,
          sentAt:          m.receivedAt?.toISOString() ?? new Date().toISOString(),
          intent:          "unknown" as const,
          isAutoGenerated: false,
          read:            m.isRead,
        }));

        // Merge any outbound messages stored in memory
        const outbound = (_messages.get(convId) ?? []).filter((m) => m.direction === "outbound");
        const allMessages = [...messages, ...outbound].sort(
          (a, b) => new Date(a.sentAt).getTime() - new Date(b.sentAt).getTime()
        );

        contexts.push({
          id:             convId,
          leadId:         contactId,
          leadName:       first.contactName ?? first.contactPhone ?? "Unknown",
          businessName:   first.bizName ?? "",
          phone:          first.contactPhone ?? null,
          email:          first.contactEmail ?? null,
          city:           "",
          category:       "",
          status:         "active",
          automationMode: "manual",
          channel:        "sms",
          lastIntent:     "unknown",
          lastMessage:    msgs[0]?.body ?? "",
          lastMessageAt:  msgs[0]?.receivedAt?.toISOString() ?? new Date().toISOString(),
          unreadCount:    msgs.filter((m) => !m.isRead).length,
          messages:       allMessages,
        });
      }

      // Merge in any in-memory only conversations (no replies yet)
      for (const [id, ctx] of _conversations) {
        if (!contexts.find((c) => c.id === id)) {
          contexts.push({ ...ctx, messages: _messages.get(id) ?? [] });
        }
      }

      return contexts;
    } catch {
      // Fallback to in-memory if DB not available
      return Array.from(_conversations.values()).map((ctx) => ({
        ...ctx,
        messages: _messages.get(ctx.id) ?? [],
      }));
    }
  }

  async getById(conversationId: string): Promise<ConversationContext | null> {
    const all = await this.getAll();
    return all.find((c) => c.id === conversationId) ?? _conversations.get(conversationId) ?? null;
  }

  async getByLeadId(leadId: string): Promise<ConversationContext[]> {
    const all = await this.getAll();
    return all.filter((c) => c.leadId === leadId);
  }

  // ── Write (in-memory for now) ──────────────────────────────────────────────

  async upsert(input: UpsertConversationInput): Promise<ConversationContext> {
    const existing = _conversations.get(input.id ?? `conv-${input.leadId}`);
    const ctx: ConversationContext = {
      id:             input.id ?? `conv-${input.leadId}`,
      leadId:         input.leadId ?? "",
      leadName:       input.leadName ?? "",
      businessName:   input.businessName ?? "",
      phone:          input.phone ?? null,
      email:          input.email ?? null,
      city:           input.city ?? "",
      category:       input.category ?? "",
      status:         input.status ?? "active",
      automationMode: input.automationMode ?? "manual",
      channel:        input.channel ?? "sms",
      lastIntent:     existing?.lastIntent ?? "unknown",
      lastMessage:    existing?.lastMessage ?? "",
      lastMessageAt:  existing?.lastMessageAt ?? new Date().toISOString(),
      unreadCount:    existing?.unreadCount ?? 0,
      messages:       [],
    };
    _conversations.set(ctx.id, ctx);
    return ctx;
  }

  async addMessage(conversationId: string, input: CreateMessageInput): Promise<AutomationMessage> {
    const msg: AutomationMessage = {
      id:              `msg-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      direction:       input.direction,
      channel:         input.channel ?? "sms",
      body:            input.body,
      sentAt:          input.sentAt ?? new Date().toISOString(),
      intent:          input.intent ?? "unknown",
      isAutoGenerated: input.isAutoGenerated ?? false,
      read:            input.direction === "outbound",
    };

    const existing = _messages.get(conversationId) ?? [];
    _messages.set(conversationId, [...existing, msg]);

    // Update lastMessage on conversation
    const ctx = _conversations.get(conversationId);
    if (ctx) {
      _conversations.set(conversationId, {
        ...ctx,
        lastMessage:   input.body,
        lastMessageAt: msg.sentAt,
      });
    }

    return msg;
  }

  async getMessages(conversationId: string): Promise<AutomationMessage[]> {
    return _messages.get(conversationId) ?? [];
  }

  async setAutomationMode(conversationId: string, mode: AutomationMode): Promise<void> {
    const ctx = _conversations.get(conversationId);
    if (ctx) _conversations.set(conversationId, { ...ctx, automationMode: mode });
  }

  async setLastIntent(conversationId: string, intent: IntentType): Promise<void> {
    const ctx = _conversations.get(conversationId);
    if (ctx) _conversations.set(conversationId, { ...ctx, lastIntent: intent });
  }

  async markRead(conversationId: string): Promise<void> {
    const msgs = _messages.get(conversationId) ?? [];
    _messages.set(
      conversationId,
      msgs.map((m) => (m.direction === "inbound" ? { ...m, read: true } : m))
    );
    const ctx = _conversations.get(conversationId);
    if (ctx) _conversations.set(conversationId, { ...ctx, unreadCount: 0 });

    // Also mark real DB replies as read
    try {
      const contactId = conversationId.replace("conv-", "");
      await db
        .update(outreachReplies)
        .set({ isRead: true })
        .where(eq(outreachReplies.contactId, contactId));
    } catch {
      // Best-effort
    }
  }

  async getUnreadCount(): Promise<number> {
    try {
      const rows = await db
        .select({ isRead: outreachReplies.isRead })
        .from(outreachReplies)
        .where(eq(outreachReplies.isRead, false));
      return rows.length;
    } catch {
      let count = 0;
      for (const ctx of _conversations.values()) {
        count += ctx.unreadCount;
      }
      return count;
    }
  }
}
