// ─────────────────────────────────────────────────────────────────────────────
// Supabase Conversation Repository — PERSISTENT (Migration 17)
//
// Reads and writes ALL messages to the conversations table.
// No more in-memory ephemeral storage — everything survives restarts.
//
// Falls back gracefully to empty state if DB is unavailable.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  AutomationMessage,
  AutomationMode,
  ConversationContext,
  IntentType,
} from "../../types";
import type {
  IConversationRepository,
  UpsertConversationInput,
  CreateMessageInput,
} from "../interfaces";
import {
  db,
  conversations,
  outreachReplies,
} from "@homereach/db";
import { eq, desc, and } from "drizzle-orm";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function rowToMessage(row: {
  id: string;
  direction: string;
  channel: string;
  message: string;
  sentAt: Date | null;
  intent: string | null;
  aiGenerated: boolean;
  isRead: boolean;
}): AutomationMessage {
  return {
    id:              row.id,
    direction:       row.direction as "inbound" | "outbound",
    channel:         row.channel as "sms" | "email",
    body:            row.message,
    sentAt:          row.sentAt?.toISOString() ?? new Date().toISOString(),
    intent:          (row.intent ?? "unknown") as IntentType,
    isAutoGenerated: row.aiGenerated,
    read:            row.isRead,
  };
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// ─────────────────────────────────────────────────────────────────────────────
// Repository
// ─────────────────────────────────────────────────────────────────────────────

export class SupabaseConversationRepository implements IConversationRepository {

  // ── getAll ────────────────────────────────────────────────────────────────

  async getAll(): Promise<ConversationContext[]> {
    try {
      const rows = await db
        .select()
        .from(conversations)
        .orderBy(desc(conversations.sentAt))
        .limit(500);

      // Group by contact key (phone > email > leadId > id)
      const threadMap = new Map<string, typeof rows>();
      for (const row of rows) {
        const key = row.contactPhone ?? row.contactEmail ?? row.leadId ?? row.id;
        const bucket = threadMap.get(key) ?? [];
        bucket.push(row);
        threadMap.set(key, bucket);
      }

      const contexts: ConversationContext[] = [];
      for (const [threadKey, msgs] of threadMap) {
        const sorted = [...msgs].sort(
          (a, b) => new Date(a.sentAt ?? 0).getTime() - new Date(b.sentAt ?? 0).getTime()
        );
        const latest       = msgs[0]!; // DESC order → first = most recent
        const convId       = `conv-${threadKey}`;
        const lastIntentMsg = msgs.find(
          (m) => m.direction === "inbound" && m.intent && m.intent !== "unknown"
        );
        const unreadCount  = msgs.filter(
          (m) => m.direction === "inbound" && !m.isRead
        ).length;

        contexts.push({
          id:             convId,
          leadId:         latest.leadId ?? threadKey,
          leadName:       latest.leadName ?? latest.contactPhone ?? "Unknown",
          businessName:   latest.businessName ?? "",
          phone:          latest.contactPhone ?? null,
          email:          latest.contactEmail ?? null,
          city:           latest.city ?? "",
          category:       latest.category ?? "",
          status:         "active",
          automationMode: (latest.automationMode ?? "manual") as AutomationMode,
          channel:        (latest.channel ?? "sms") as "sms" | "email",
          lastIntent:     (lastIntentMsg?.intent ?? "unknown") as IntentType,
          lastMessage:    latest.message,
          lastMessageAt:  latest.sentAt?.toISOString() ?? new Date().toISOString(),
          unreadCount,
          messages:       sorted.map(rowToMessage),
        });
      }

      return contexts;
    } catch (err) {
      console.error("[ConversationRepo] getAll error:", err);
      return [];
    }
  }

  async getById(conversationId: string): Promise<ConversationContext | null> {
    const all = await this.getAll();
    return all.find((c) => c.id === conversationId) ?? null;
  }

  async getByLeadId(leadId: string): Promise<ConversationContext[]> {
    try {
      const rows = await db
        .select()
        .from(conversations)
        .where(eq(conversations.leadId, leadId))
        .orderBy(desc(conversations.sentAt))
        .limit(200);

      if (rows.length === 0) return [];

      const sorted = [...rows].sort(
        (a, b) => new Date(a.sentAt ?? 0).getTime() - new Date(b.sentAt ?? 0).getTime()
      );
      const latest = rows[0]!;

      return [{
        id:             `conv-${leadId}`,
        leadId,
        leadName:       latest.leadName ?? "Unknown",
        businessName:   latest.businessName ?? "",
        phone:          latest.contactPhone ?? null,
        email:          latest.contactEmail ?? null,
        city:           latest.city ?? "",
        category:       latest.category ?? "",
        status:         "active",
        automationMode: (latest.automationMode ?? "manual") as AutomationMode,
        channel:        (latest.channel ?? "sms") as "sms" | "email",
        lastIntent:     "unknown",
        lastMessage:    latest.message,
        lastMessageAt:  latest.sentAt?.toISOString() ?? new Date().toISOString(),
        unreadCount:    rows.filter((m) => m.direction === "inbound" && !m.isRead).length,
        messages:       sorted.map(rowToMessage),
      }];
    } catch {
      return [];
    }
  }

  // ── upsert ────────────────────────────────────────────────────────────────
  // Conversations derive from messages — no separate context row needed.

  async upsert(input: UpsertConversationInput): Promise<ConversationContext> {
    return {
      id:             input.id ?? `conv-${input.leadId}`,
      leadId:         input.leadId ?? "",
      leadName:       input.leadName ?? "",
      businessName:   input.businessName ?? "",
      phone:          input.phone ?? null,
      email:          input.email ?? null,
      city:           input.city ?? "",
      category:       input.category ?? "",
      status:         input.status ?? "active",
      automationMode: input.automationMode ?? "manual",
      channel:        input.channel ?? "sms",
      lastIntent:     "unknown",
      lastMessage:    "",
      lastMessageAt:  new Date().toISOString(),
      unreadCount:    0,
      messages:       [],
    };
  }

  // ── addMessage — PERSISTENT ───────────────────────────────────────────────

  async addMessage(
    conversationId: string,
    input: CreateMessageInput
  ): Promise<AutomationMessage> {
    const contactKey = conversationId.replace(/^conv-/, "");

    let leadId:       string | null = null;
    let contactPhone: string | null = null;
    let contactEmail: string | null = null;

    if (UUID_RE.test(contactKey))    leadId       = contactKey;
    else if (contactKey.includes("@")) contactEmail = contactKey;
    else                             contactPhone  = contactKey;

    const ctx = await this.getById(conversationId).catch(() => null);

    try {
      const [row] = await db
        .insert(conversations)
        .values({
          leadId:        leadId      ?? ctx?.leadId   ?? null,
          contactPhone:  contactPhone ?? ctx?.phone   ?? null,
          contactEmail:  contactEmail ?? ctx?.email   ?? null,
          leadName:      ctx?.leadName    ?? null,
          businessName:  ctx?.businessName ?? null,
          city:          ctx?.city        ?? null,
          category:      ctx?.category    ?? null,
          channel:       input.channel ?? "sms",
          direction:     input.direction,
          message:       input.body,
          intent:        input.intent ?? null,
          aiGenerated:   input.isAutoGenerated ?? false,
          automationMode: ctx?.automationMode ?? "manual",
          isRead:        input.direction === "outbound",
          sentAt:        input.sentAt ? new Date(input.sentAt) : new Date(),
        })
        .returning();

      return rowToMessage(row!);
    } catch (err) {
      console.error("[ConversationRepo] addMessage error:", err);
      return {
        id:              `msg-fallback-${Date.now()}`,
        direction:       input.direction,
        channel:         (input.channel ?? "sms") as "sms" | "email",
        body:            input.body,
        sentAt:          input.sentAt ?? new Date().toISOString(),
        intent:          (input.intent ?? "unknown") as IntentType,
        isAutoGenerated: input.isAutoGenerated ?? false,
        read:            input.direction === "outbound",
      };
    }
  }

  async getMessages(conversationId: string): Promise<AutomationMessage[]> {
    const ctx = await this.getById(conversationId);
    return ctx?.messages ?? [];
  }

  // ── setAutomationMode ─────────────────────────────────────────────────────

  async setAutomationMode(conversationId: string, mode: AutomationMode): Promise<void> {
    const contactKey = conversationId.replace(/^conv-/, "");
    try {
      if      (UUID_RE.test(contactKey))        await db.update(conversations).set({ automationMode: mode }).where(eq(conversations.leadId,       contactKey));
      else if (contactKey.includes("@"))         await db.update(conversations).set({ automationMode: mode }).where(eq(conversations.contactEmail, contactKey));
      else                                       await db.update(conversations).set({ automationMode: mode }).where(eq(conversations.contactPhone, contactKey));
    } catch (err) { console.error("[ConversationRepo] setAutomationMode:", err); }
  }

  // ── setLastIntent ─────────────────────────────────────────────────────────

  async setLastIntent(conversationId: string, intent: IntentType): Promise<void> {
    const contactKey = conversationId.replace(/^conv-/, "");
    try {
      if (UUID_RE.test(contactKey)) {
        await db
          .update(conversations)
          .set({ intent })
          .where(and(eq(conversations.leadId, contactKey), eq(conversations.direction, "inbound")));
      }
    } catch { /* best-effort */ }
  }

  // ── markRead ──────────────────────────────────────────────────────────────

  async markRead(conversationId: string): Promise<void> {
    const contactKey = conversationId.replace(/^conv-/, "");
    const inbound = and(eq(conversations.direction, "inbound"), eq(conversations.isRead, false));
    try {
      if      (UUID_RE.test(contactKey))  await db.update(conversations).set({ isRead: true }).where(and(eq(conversations.leadId,       contactKey), inbound!));
      else if (contactKey.includes("@")) await db.update(conversations).set({ isRead: true }).where(and(eq(conversations.contactEmail, contactKey), inbound!));
      else                               await db.update(conversations).set({ isRead: true }).where(and(eq(conversations.contactPhone, contactKey), inbound!));

      // Legacy outreach_replies back-compat
      await db.update(outreachReplies).set({ isRead: true }).where(eq(outreachReplies.contactId, contactKey)).catch(() => {});
    } catch (err) { console.error("[ConversationRepo] markRead:", err); }
  }

  // ── getUnreadCount ────────────────────────────────────────────────────────

  async getUnreadCount(): Promise<number> {
    try {
      const rows = await db
        .select({ id: conversations.id })
        .from(conversations)
        .where(and(eq(conversations.direction, "inbound"), eq(conversations.isRead, false)));
      return rows.length;
    } catch { return 0; }
  }
}
