// ─────────────────────────────────────────────────────────────────────────────
// POST /api/conversations/[id]/reply
//
// Persist an outbound reply from the admin inbox and optionally send it
// via Twilio SMS.
//
// Body: { body: string; channel: "sms" | "email"; sendViaTwilio?: boolean }
// ─────────────────────────────────────────────────────────────────────────────

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db, outreachReplies, outreachContacts } from "@homereach/db";
import { eq } from "drizzle-orm";
import { getConversationRepository } from "@/lib/engine/db/factory";
import { AutomationEngine } from "@/lib/engine/automation";

const ReplySchema = z.object({
  body:           z.string().min(1),
  channel:        z.enum(["sms", "email"]).default("sms"),
  sendViaTwilio:  z.boolean().optional().default(false),
  isAutoGenerated: z.boolean().optional().default(false),
});

export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { id: conversationId } = await context.params;
    const body = await req.json();
    const data = ReplySchema.parse(body);

    const repo   = getConversationRepository();
    const engine = new AutomationEngine(repo);

    // ── Persist the outbound message ──────────────────────────────────────────
    const message = await engine.sendReply(
      conversationId,
      data.body,
      data.channel,
      data.isAutoGenerated
    );

    // ── Persist to outreach_replies table as outbound record ──────────────────
    // (Store in DB so it survives server restarts — use a sentinel businessId
    //  derived from the conversation's contact record)
    try {
      const contactId = conversationId.replace("conv-", "");
      const [contact] = await db
        .select({ businessId: outreachContacts.businessId })
        .from(outreachContacts)
        .where(eq(outreachContacts.id, contactId))
        .limit(1);

      if (contact) {
        await db.insert(outreachReplies).values({
          contactId,
          businessId: contact.businessId,
          channel:    data.channel,
          body:       `[OUTBOUND] ${data.body}`,
          receivedAt: new Date(),
          isRead:     true,
        });
      }
    } catch (persistErr) {
      // Non-fatal — message was saved in-memory, log and continue
      console.error("[conversations/reply] DB persist failed:", persistErr);
    }

    // ── Optionally send via Twilio ─────────────────────────────────────────────
    let smsSid: string | undefined;
    if (data.sendViaTwilio && data.channel === "sms") {
      try {
        const conv = await engine.getConversation(conversationId);
        if (conv?.phone) {
          const result = await AutomationEngine.sendSms(conv.phone, data.body);
          smsSid = result.sid;
          if (!result.success) {
            console.error(`[conversations/reply] Twilio send failed for ${conversationId}`);
          }
        }
      } catch (smsErr) {
        console.error("[conversations/reply] SMS send error:", smsErr);
      }
    }

    return NextResponse.json({ success: true, message, smsSid });
  } catch (err) {
    console.error("[POST /api/conversations/[id]/reply]", err);
    if (err instanceof z.ZodError) {
      return NextResponse.json({ error: err.flatten() }, { status: 400 });
    }
    return NextResponse.json({ error: "Failed to send reply" }, { status: 500 });
  }
}
