// ─────────────────────────────────────────────────────────────────────────────
// POST /api/conversations/[id]/reply
//
// Persist an outbound reply from the admin inbox and optionally send it
// via Twilio SMS.
//
// Body: { body: string; channel: "sms" | "email"; sendViaTwilio?: boolean }
// ─────────────────────────────────────────────────────────────────────────────

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db, outreachReplies, outreachContacts } from "@homereach/db";
import { eq } from "drizzle-orm";
import { getConversationRepository } from "@/lib/engine/db/factory";
import { AutomationEngine } from "@/lib/engine/automation";
import { requireAdminOrSalesAgent } from "@/lib/auth/api-guards";
import { logPlatformAuditEvent } from "@/lib/audit/platform-audit";
import { createServiceClient } from "@/lib/supabase/service";

const ReplySchema = z.object({
  body:           z.string().min(1),
  channel:        z.enum(["sms", "email"]).default("sms"),
  sendViaTwilio:  z.boolean().optional().default(false),
  isAutoGenerated: z.boolean().optional().default(false),
});

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

async function canAccessConversation(userId: string, role: string | undefined, conversationId: string) {
  if (role === "admin") return true;
  if (role !== "sales_agent") return false;

  const leadId = conversationId.replace(/^conv-/, "");
  if (!UUID_RE.test(leadId)) return false;

  const supabase = createServiceClient();
  const { data } = await supabase
    .from("sales_leads")
    .select("id")
    .eq("id", leadId)
    .eq("assigned_agent_id", userId)
    .maybeSingle();

  return Boolean(data);
}

export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const guard = await requireAdminOrSalesAgent();
    if (!guard.ok) return guard.response;

    const { id: conversationId } = await context.params;
    const currentUser = guard.user!;
    const role = currentUser.app_metadata?.user_role as string | undefined;
    if (!(await canAccessConversation(currentUser.id, role, conversationId))) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await req.json();
    const data = ReplySchema.parse(body);

    if (data.sendViaTwilio && data.isAutoGenerated) {
      return NextResponse.json(
        { error: "AI-generated outbound messages require human approval before sending." },
        { status: 409 },
      );
    }

    const repo   = getConversationRepository();
    const engine = new AutomationEngine(repo);

    // ── Persist the outbound message ──────────────────────────────────────────
    const message = await engine.sendReply(
      conversationId,
      data.body,
      data.channel,
      data.isAutoGenerated
    );

    // ── Persist to outreach_replies table as outbound record ──────────────────
    // (Store in DB so it survives server restarts — use a sentinel businessId
    //  derived from the conversation's contact record)
    try {
      const contactId = conversationId.replace("conv-", "");
      const [contact] = await db
        .select({ businessId: outreachContacts.businessId })
        .from(outreachContacts)
        .where(eq(outreachContacts.id, contactId))
        .limit(1);

      if (contact) {
        await db.insert(outreachReplies).values({
          contactId,
          businessId: contact.businessId,
          channel:    data.channel,
          body:       `[OUTBOUND] ${data.body}`,
          receivedAt: new Date(),
          isRead:     true,
        });
      }
    } catch (persistErr) {
      // Non-fatal — message was saved in-memory, log and continue
      console.error("[conversations/reply] DB persist failed:", persistErr);
    }

    // ── Optionally send via Twilio ─────────────────────────────────────────────
    let smsSid: string | undefined;
    if (data.sendViaTwilio && data.channel === "sms") {
      try {
        const supabase = createServiceClient();
        const { data: controls } = await supabase
          .from("system_controls")
          .select("all_paused,sms_paused,outreach_test_mode")
          .eq("id", 1)
          .maybeSingle();

        if (controls?.all_paused || controls?.sms_paused || controls?.outreach_test_mode) {
          const reason = controls?.all_paused
            ? "global_system_pause"
            : controls?.sms_paused
              ? "sms_channel_pause"
              : "outreach_test_mode";
          await logPlatformAuditEvent({
            actorType: "human",
            actorId: currentUser.id,
            module: "communications",
            actionType: "conversation_sms_send_blocked",
            entityType: "conversation",
            entityId: conversationId,
            channel: "sms",
            resultStatus: "blocked",
            approvalState: data.isAutoGenerated ? "needs_review" : "approved",
            severity: "high",
            message: `Conversation SMS send blocked by ${reason}.`,
            metadata: { reason },
          });

          return NextResponse.json({ success: true, message, smsBlocked: true, reason });
        }

        const conv = await engine.getConversation(conversationId);
        if (conv?.phone) {
          const result = await AutomationEngine.sendSms(conv.phone, data.body);
          smsSid = result.sid;
          if (!result.success) {
            console.error(`[conversations/reply] Twilio send failed for ${conversationId}`);
          }
        }
      } catch (smsErr) {
        console.error("[conversations/reply] SMS send error:", smsErr);
      }
    }

    return NextResponse.json({ success: true, message, smsSid });
  } catch (err) {
    console.error("[POST /api/conversations/[id]/reply]", err);
    if (err instanceof z.ZodError) {
      return NextResponse.json({ error: err.flatten() }, { status: 400 });
    }
    return NextResponse.json({ error: "Failed to send reply" }, { status: 500 });
  }
}
