import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/service";

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/conversations
// Builds conversation threads from sales_events + sales_leads.
// Uses Supabase JS (HTTP) — no Drizzle, reliable in Vercel serverless.
// ─────────────────────────────────────────────────────────────────────────────

export async function GET() {
  try {
    const db = createServiceClient();

    // Get all leads that have been contacted or replied
    const { data: leads, error: leadsErr } = await db
      .from("sales_leads")
      .select("id, business_name, contact_name, phone, email, city, category, status, last_contacted_at, last_reply_at")
      .in("status", ["contacted", "replied", "interested", "payment_sent", "closed"])
      .order("last_reply_at", { ascending: false, nullsFirst: false })
      .order("last_contacted_at", { ascending: false, nullsFirst: false })
      .limit(200);

    if (leadsErr || !leads?.length) {
      return NextResponse.json({ conversations: [] });
    }

    const leadIds = leads.map(l => l.id);

    // Get all events for these leads
    const { data: events } = await db
      .from("sales_events")
      .select("id, lead_id, action_type, channel, message, created_at, agent_id")
      .in("lead_id", leadIds)
      .order("created_at", { ascending: true });

    // Group events by lead_id
    const eventsByLead: Record<string, typeof events> = {};
    for (const ev of events ?? []) {
      if (!ev.lead_id) continue;
      (eventsByLead[ev.lead_id] ??= []).push(ev);
    }

    // Build conversation threads
    const conversations = leads.map(lead => {
      const evs = eventsByLead[lead.id] ?? [];

      const messages = evs
        .filter(e => e.message)
        .map(e => ({
          id:              e.id,
          direction:       (["reply_received", "conversation_started"].includes(e.action_type) ? "inbound" : "outbound") as "inbound" | "outbound",
          channel:         (e.channel ?? "sms") as "sms" | "email",
          body:            e.message ?? "",
          sentAt:          e.created_at,
          intent:          "unknown" as const,
          isAutoGenerated: false,
          read:            true,
        }));

      const lastMsg   = messages[messages.length - 1];
      const unread    = messages.filter(m => m.direction === "inbound" && !m.read).length;
      const channel   = (lead.phone ? "sms" : "email") as "sms" | "email";
      const convStatus = lead.status === "replied" ? "interested" : lead.status === "closed" ? "closed_won" : "lead";

      return {
        id:             `conv-${lead.id}`,
        leadId:         lead.id,
        leadName:       lead.contact_name ?? lead.business_name,
        businessName:   lead.business_name,
        phone:          lead.phone ?? "",
        email:          lead.email ?? "",
        city:           lead.city ?? "",
        category:       lead.category ?? "",
        status:         convStatus,
        automationMode: "manual" as const,
        channel,
        lastIntent:     undefined,
        lastMessage:    lastMsg?.body ?? "Contacted",
        lastMessageAt:  lead.last_reply_at ?? lead.last_contacted_at ?? new Date().toISOString(),
        unreadCount:    unread,
        messages,
      };
    });

    // Sort: replied first (have inbound messages), then by recency
    conversations.sort((a, b) => {
      const aHasReply = a.messages.some(m => m.direction === "inbound");
      const bHasReply = b.messages.some(m => m.direction === "inbound");
      if (aHasReply !== bHasReply) return aHasReply ? -1 : 1;
      return new Date(b.lastMessageAt).getTime() - new Date(a.lastMessageAt).getTime();
    });

    return NextResponse.json({ conversations });
  } catch (err) {
    console.error("[GET /api/conversations]", err);
    return NextResponse.json({ error: "Failed to load conversations" }, { status: 500 });
  }
}
